### ISSUE TITLE
[automation] IOE when a script is > 99,999 characters

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-core#1574] opened 2020-07-31 01:44 UTC
After saving a script that has more than 99,999 characters, the following exception will occur and the script will not load...

```
2020-07-30 16:42:55.076 [DEBUG] [org.eclipse.smarthome.core.service.AbstractWatchService] - in queue: {rb=[file:/opt/openhab2/conf/automation/jsr223/jruby/personal/test.rb], groovy=[file:/opt/openhab2/conf/automation/jsr223/groovy/personal/testScript.groovy, file:/opt/openhab2/conf/automation/jsr223/groovy/personal/HelloWorld.groovy]}
2020-07-30 16:42:55.077 [TRACE] [org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl] - scriptUnloaded() is not defined in the script
2020-07-30 16:42:55.077 [INFO ] [org.eclipse.smarthome.core.service.AbstractWatchService] - Loading script 'python/personal/test/test_script_2.py'
2020-07-30 16:42:55.263 [DEBUG] [org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl] - Added ScriptEngine for language 'py' with identifier: file:/opt/openhab2/conf/automation/jsr223/python/personal/test/test_script_2.py
2020-07-30 16:42:55.264 [ERROR] [org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/opt/openhab2/conf/automation/jsr223/python/personal/test/test_script_2.py': java.io.IOException: java.io.IOException: Mark invalid
2020-07-30 16:42:55.264 [DEBUG] [org.eclipse.smarthome.core.service.AbstractWatchService] - Script loaded: python/personal/test/test_script_2.py
```
I've run into this a few times now when my test scripts get too big. I just create a new script and have not dug much into the cause or debugged it. The error comes after calling [engine.eval(scriptData)](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java#L152). It would be helpful [if there was a stack trace](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java#L165), but [my PR was not allowed](https://github.com/openhab/openhab-core/pull/715/files#diff-be6194caea904e0d40dcf9273827ee93R161). This is where I would start analyzing why this is occurring. If I find time, I'll look deeper.

I have noticed this for a long while and it currently occurs on 2.5.7. Here is a test file... [too_many_chars.py.txt](https://github.com/openhab/openhab-core/files/5004607/too_many_chars.py.txt).

**Comment by kaikreuzer** [comment] 2020-07-31 12:02
> It would be helpful if there was a stack trace, but my PR was not allowed.

Why do you say so? It is marked as WIP and it is [waiting for further updates from you](https://github.com/openhab/openhab-core/pull/715#issuecomment-623679035). Am I missing something?

**Comment by J-N-K** [comment] 2022-05-07 13:28
```
0 = {StackTraceElement@23689} "org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:226)"
1 = {StackTraceElement@23690} "org.python.jsr223.PyScriptEngine.compileScript(PyScriptEngine.java:107)"
2 = {StackTraceElement@23691} "org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:64)"
3 = {StackTraceElement@23692} "java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)"
4 = {StackTraceElement@23693} "org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl.loadScript(ScriptEngineManagerImpl.java:189)"
```

The issue is in the Python script engine, not in openHAB. I check that e.g. the JS Scripting add-on can process a file similar to the one above without any issues.

**Closed by J-N-K** 2022-05-07 13:28 UTC
