### ISSUE TITLE
Basic UI is missing favicon

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab-core#83] opened 2016-11-25 18:40 UTC
Using build 612, I am setting up a very small sitemap. The generated pages are missing their favicon:

    $ curl -v http://127.0.0.1:8080/basicui/images/favicon.ico
    * Hostname was NOT found in DNS cache
    *   Trying 127.0.0.1...
    * Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
    > GET /basicui/images/favicon.ico HTTP/1.1
    > User-Agent: curl/7.38.0
    > Host: 127.0.0.1:8080
    > Accept: */*
    >
    < HTTP/1.1 404 Not Found

**Comment by kaikreuzer** [comment] 2016-11-26 12:43
Duplicate of https://github.com/openhab/openhab-distro/issues/308

**Closed by kaikreuzer** 2016-11-26 12:43 UTC
