### ISSUE TITLE
openHAB directory is not relocatable

### ISSUE THREAD

**Issue by dottedmag** [openhab/openhab-core#542] opened 2019-02-06 19:59 UTC
openHAB writes absolute paths to `userdata` and hence moving its directory is not trivial (one has to do something like `sed`ing the `userdata`).

Here's an example from my test installation:
```
% grep -r /Users/dottedmag . | grep -v logs
Binary file ./userdata/cache/org.eclipse.osgi/framework.info.96 matches
./userdata/config/org/jupnp.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.jupnp.cfg"
./userdata/config/org/eclipse/smarthome/audio.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.eclipse.smarthome.audio.cfg"
./userdata/config/org/eclipse/smarthome/voice.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.eclipse.smarthome.voice.cfg"
./userdata/config/org/ops4j/pax/web.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.ops4j.pax.web.cfg"
./userdata/config/org/ops4j/pax/web.config:org.ops4j.pax.web.config.file="/Users/dottedmag/w/home-automation/openhab/runtime/etc/jetty.xml"
./userdata/config/org/ops4j/pax/url/mvn.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.ops4j.pax.url.mvn.cfg"
./userdata/config/org/ops4j/pax/url/mvn.config:org.ops4j.pax.url.mvn.defaultRepositories="file:/Users/dottedmag/w/home-automation/openhab/runtime/system@id\=system.repository@snapshots,\ file:/Users/dottedmag/w/home-automation/openhab/userdata/tmp/kar@id\=kar.repository@multi@snapshots,\ file:/Users/dottedmag/w/home-automation/openhab/userdata/system@id\=child.system.repository@snapshots"
./userdata/config/org/ops4j/pax/url/mvn.config:org.ops4j.pax.url.mvn.localRepository="/Users/dottedmag/w/home-automation/openhab/userdata/tmp/mvn"
./userdata/config/org/ops4j/pax/logging.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.ops4j.pax.logging.cfg"
./userdata/config/org/apache/karaf/log.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.log.cfg"
./userdata/config/org/apache/karaf/jaas.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.jaas.cfg"
./userdata/config/org/apache/karaf/features.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.features.cfg"
./userdata/config/org/apache/karaf/features/repos.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.features.repos.cfg"
./userdata/config/org/apache/karaf/kar.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.kar.cfg"
./userdata/config/org/apache/karaf/kar.config:karStorage="/Users/dottedmag/w/home-automation/openhab/userdata/tmp/kar"
./userdata/config/org/apache/karaf/shell.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.shell.cfg"
./userdata/config/org/apache/karaf/shell.config:hostKey="/Users/dottedmag/w/home-automation/openhab/userdata/etc/host.key"
./userdata/config/org/apache/karaf/command/acl/scope_bundle.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.command.acl.scope_bundle.cfg"
./userdata/config/org/apache/karaf/command/acl/jaas.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.command.acl.jaas.cfg"
./userdata/config/org/apache/karaf/command/acl/kar.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.command.acl.kar.cfg"
./userdata/config/org/apache/karaf/command/acl/bundle.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.command.acl.bundle.cfg"
./userdata/config/org/apache/karaf/command/acl/shell.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.command.acl.shell.cfg"
./userdata/config/org/apache/karaf/command/acl/system.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.command.acl.system.cfg"
./userdata/config/org/apache/karaf/command/acl/config.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.command.acl.config.cfg"
./userdata/config/org/apache/karaf/command/acl/feature.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.karaf.command.acl.feature.cfg"
./userdata/config/org/apache/felix/fileinstall/351e53bd-e924-46e3-a384-9feb7eef114e.config:felix.fileinstall.dir="/Users/dottedmag/w/home-automation/openhab/addons"
./userdata/config/org/apache/felix/fileinstall/351e53bd-e924-46e3-a384-9feb7eef114e.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.felix.fileinstall-deploy.cfg"
./userdata/config/org/apache/felix/fileinstall/351e53bd-e924-46e3-a384-9feb7eef114e.config:felix.fileinstall.tmpdir="/Users/dottedmag/w/home-automation/openhab/userdata/tmp/bundles"
./userdata/config/org/apache/felix/fileinstall/64e8fb94-2b2a-49ff-b884-770f384aec11.config:felix.fileinstall.dir="/Users/dottedmag/w/home-automation/openhab/addons"
./userdata/config/org/apache/felix/fileinstall/64e8fb94-2b2a-49ff-b884-770f384aec11.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.felix.fileinstall-deploy.cfg"
./userdata/config/org/apache/felix/fileinstall/64e8fb94-2b2a-49ff-b884-770f384aec11.config:felix.fileinstall.tmpdir="/Users/dottedmag/w/home-automation/openhab/userdata/tmp/bundles"
./userdata/config/org/apache/felix/eventadmin/impl/EventAdmin.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/org.apache.felix.eventadmin.impl.EventAdmin.cfg"
./userdata/config/jmx/acl/org/apache/karaf/bundle.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/jmx.acl.org.apache.karaf.bundle.cfg"
./userdata/config/jmx/acl/org/apache/karaf/config.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/jmx.acl.org.apache.karaf.config.cfg"
./userdata/config/profile.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/profile.cfg"
./userdata/config/com/eclipsesource/jaxrs/connector.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/com.eclipsesource.jaxrs.connector.cfg"
./userdata/config/com/eclipsesource/jaxrs/swagger/config.config:felix.fileinstall.filename="file:/Users/dottedmag/w/home-automation/openhab/userdata/etc/com.eclipsesource.jaxrs.swagger.config.cfg"
./userdata/tmp/instances/instance.properties:item.0.loc = /Users/dottedmag/w/home-automation/openhab/userdata
```

Note that majority of these are keys `felix.fileinstall.dir` and `felix.fileinstall.filename` — can these be fixed _en masse_? There are few other absolute paths:

```
% grep -r /Users/dottedmag . | grep -v logs| grep -v felix.fileinstall
Binary file ./userdata/cache/org.eclipse.osgi/framework.info.96 matches
./userdata/config/org/ops4j/pax/web.config:org.ops4j.pax.web.config.file="/Users/dottedmag/w/home-automation/openhab/runtime/etc/jetty.xml"
./userdata/config/org/ops4j/pax/url/mvn.config:org.ops4j.pax.url.mvn.defaultRepositories="file:/Users/dottedmag/w/home-automation/openhab/runtime/system@id\=system.repository@snapshots,\ file:/Users/dottedmag/w/home-automation/openhab/userdata/tmp/kar@id\=kar.repository@multi@snapshots,\ file:/Users/dottedmag/w/home-automation/openhab/userdata/system@id\=child.system.repository@snapshots"
./userdata/config/org/ops4j/pax/url/mvn.config:org.ops4j.pax.url.mvn.localRepository="/Users/dottedmag/w/home-automation/openhab/userdata/tmp/mvn"
./userdata/config/org/apache/karaf/kar.config:karStorage="/Users/dottedmag/w/home-automation/openhab/userdata/tmp/kar"
./userdata/config/org/apache/karaf/shell.config:hostKey="/Users/dottedmag/w/home-automation/openhab/userdata/etc/host.key"
./userdata/tmp/instances/instance.properties:item.0.loc = /Users/dottedmag/w/home-automation/openhab/userdata
```

**Comment by maggu2810** [comment] 2019-02-07 09:12
That's not caused by any openHAB Core bundle but by "Karaf" that is used by the openHAB Distribution for the OSGi container runtime management.

openHAB Distribution sets the `userdata` directory to be used as Karaf's data directory.

See: https://github.com/openhab/openhab-distro/blob/14a9fd15f45960a7651bbc299b9f8ee876d6a8e0/distributions/openhab/src/main/resources/bin/oh2_dir_layout#L35

So, perhaps this issue should be moved to openHAB Distribution or (IMHO better) you should ask the Karaf team if it plans to support the moving to another directory of a already started Karaf distribution.

I assume you can reproduce it using Karaf without any openHAB related stuff (so the standard distribution), too.

**Comment by dottedmag** [comment] 2019-02-07 09:41
The majority of paths are in Karaf, however there are few others, let's have a look at them too:

```
./userdata/config/org/ops4j/pax/web.config:org.ops4j.pax.web.config.file="/Users/dottedmag/w/home-automation/openhab/runtime/etc/jetty.xml"
./userdata/config/org/ops4j/pax/url/mvn.config:org.ops4j.pax.url.mvn.defaultRepositories="file:/Users/dottedmag/w/home-automation/openhab/runtime/system@id\=system.repository@snapshots,\ file:/Users/dottedmag/w/home-automation/openhab/userdata/tmp/kar@id\=kar.repository@multi@snapshots,\ file:/Users/dottedmag/w/home-automation/openhab/userdata/system@id\=child.system.repository@snapshots"
./userdata/config/org/ops4j/pax/url/mvn.config:org.ops4j.pax.url.mvn.localRepository="/Users/dottedmag/w/home-automation/openhab/userdata/tmp/mvn"
./userdata/config/org/apache/karaf/kar.config:karStorage="/Users/dottedmag/w/home-automation/openhab/userdata/tmp/kar"
./userdata/config/org/apache/karaf/shell.config:hostKey="/Users/dottedmag/w/home-automation/openhab/userdata/etc/host.key"
./userdata/tmp/instances/instance.properties:item.0.loc = /Users/dottedmag/w/home-automation/openhab/userdata
```

It is in `org.ops4j.pax` configuration, one file in cache, and one temp file. I'll see whether cache and temp files are relevant.

**Comment by dottedmag** [comment] 2019-02-07 09:45
I have open a https://github.com/openhab/openhab-distro/issues/860 for distro issues. Let's keep this one open until we figure out if cache/temp/pax absolute paths come from `userdata` absolute path too.

**Comment by maggu2810** [comment] 2019-02-07 10:03
The cache, the temp, `org.ops4j.pax` and all the other configurations are provided by the Karaf distribution.
IIRC there is a processor that replaces variables etc. in configurations to absolute paths.

**Comment by splatch** [comment] 2019-08-27 16:48
@dottedmag The userdata/cache directory can be omitted. It is a cache and can be safely dropped before any roundtrips.

**Comment by wborn** [comment] 2019-09-28 20:48
Let's close this because it duplicates https://github.com/openhab/openhab-distro/issues/860.
The way data these files are managed depend on the OSGi environment (Karaf).

**Closed by wborn** 2019-09-28 20:48 UTC
Labels: karaf
