### ISSUE TITLE
DSL rules with "System started" condition not executed

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1637] opened 2020-09-12 11:05 UTC
When using the [demo.rules](https://github.com/openhab/openhab-distro/blob/0d9e3273e42bbd907c18bb99d22acda56ce805b5/features/distro-resources/src/main/resources/rules/demo.rules#L75-L129) file the rules with the "System started" don't seem to be executed at startup.
They do get executed when I manually trigger the rules from the UI.

It's most likely caused by https://github.com/openhab/openhab-core/pull/1451

**Comment by J-N-K** [comment] 2020-09-12 12:00
„System started“ is not available in JavaScript either. Not sure about Jython.

**Comment by openhab-5iver** [comment] 2020-09-12 15:55
This was moved to #1509 and should make the 'System started' trigger available for all languages which has always been available when using the Jython helper libraries.

**Comment by wborn** [comment] 2020-09-12 16:51
It's probably due to the disclaimer:

> disclaimer: No start level events are defined in this PR yet, so the trigger itself is still rather useless

**Comment by kaikreuzer** [comment] 2020-09-12 17:25
@wborn I have tried the demo setup (changed logging to INFO for rule events) and I see at least some rules being triggered at startup:
```
2020-09-12 15:29:32.462 [INFO ] [smarthome.event.StartlevelEvent     ] - Startlevel '20' reached.
2020-09-12 15:29:35.749 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-1' has been added.
2020-09-12 15:29:35.749 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-1 updated: UNINITIALIZED
2020-09-12 15:29:35.750 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-1 updated: INITIALIZING
2020-09-12 15:29:35.754 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-1 updated: IDLE
2020-09-12 15:29:35.755 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-2' has been added.
2020-09-12 15:29:35.755 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-2 updated: UNINITIALIZED
2020-09-12 15:29:35.755 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-2 updated: INITIALIZING
2020-09-12 15:29:35.756 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-2 updated: IDLE
2020-09-12 15:29:35.756 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-3' has been added.
2020-09-12 15:29:35.756 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-3 updated: UNINITIALIZED
2020-09-12 15:29:35.756 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-3 updated: INITIALIZING
2020-09-12 15:29:35.757 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-3 updated: IDLE
2020-09-12 15:29:35.757 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-4' has been added.
2020-09-12 15:29:35.758 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-4 updated: UNINITIALIZED
2020-09-12 15:29:35.758 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-4 updated: INITIALIZING
2020-09-12 15:29:35.758 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-4 updated: IDLE
2020-09-12 15:29:35.758 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-5' has been added.
2020-09-12 15:29:35.759 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-5 updated: UNINITIALIZED
2020-09-12 15:29:35.759 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-5 updated: INITIALIZING
2020-09-12 15:29:35.759 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-5 updated: IDLE
2020-09-12 15:29:35.759 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-6' has been added.
2020-09-12 15:29:35.759 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-6 updated: UNINITIALIZED
2020-09-12 15:29:35.760 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-6 updated: INITIALIZING
2020-09-12 15:29:35.760 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-6 updated: IDLE
2020-09-12 15:29:35.760 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-7' has been added.
2020-09-12 15:29:35.760 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-7 updated: UNINITIALIZED
2020-09-12 15:29:35.761 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-7 updated: INITIALIZING
2020-09-12 15:29:35.762 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-7 updated: IDLE
2020-09-12 15:29:35.762 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-8' has been added.
2020-09-12 15:29:35.763 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-8 updated: UNINITIALIZED
2020-09-12 15:29:35.763 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-8 updated: INITIALIZING
2020-09-12 15:29:35.765 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-8 updated: IDLE
2020-09-12 15:29:35.765 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-9' has been added.
2020-09-12 15:29:35.765 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-9 updated: UNINITIALIZED
2020-09-12 15:29:35.766 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-9 updated: INITIALIZING
2020-09-12 15:29:35.766 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-9 updated: IDLE
2020-09-12 15:29:35.766 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-10' has been added.
2020-09-12 15:29:35.766 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-10 updated: UNINITIALIZED
2020-09-12 15:29:35.767 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-10 updated: INITIALIZING
2020-09-12 15:29:35.767 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-10 updated: IDLE
2020-09-12 15:29:35.767 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-11' has been added.
2020-09-12 15:29:35.767 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-11 updated: UNINITIALIZED
2020-09-12 15:29:35.768 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-11 updated: INITIALIZING
2020-09-12 15:29:35.768 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-11 updated: IDLE
2020-09-12 15:29:35.768 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-12' has been added.
2020-09-12 15:29:35.769 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-12 updated: UNINITIALIZED
2020-09-12 15:29:35.769 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-12 updated: INITIALIZING
2020-09-12 15:29:35.769 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-12 updated: IDLE
2020-09-12 15:29:35.769 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'demo-13' has been added.
2020-09-12 15:29:35.769 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-13 updated: UNINITIALIZED
2020-09-12 15:29:35.770 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-13 updated: INITIALIZING
2020-09-12 15:29:35.770 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-13 updated: IDLE
2020-09-12 15:29:40.768 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-10 updated: RUNNING
2020-09-12 15:29:40.769 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-11 updated: RUNNING
2020-09-12 15:29:40.772 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-10 updated: IDLE
2020-09-12 15:29:40.772 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - demo-11 updated: IDLE
```
So you see that a startlevel is in place and it causes rules to be added and run.

**Comment by wborn** [comment] 2020-09-12 18:13
Did you also check the sitemap in Basic UI? I did not see all the items having proper state until I manually triggered those startup rules.

**Comment by kaikreuzer** [comment] 2020-09-12 19:08
Hm, you're right, I do not see temperatures being initialized...

**Comment by wborn** [comment] 2020-09-16 21:35
This issue is caused by a [very dirty hack](https://github.com/openhab/openhab-core/blob/81e82e7d4473f0eb73878135d97e3c9c46c85659/bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java#L121-L132).
When the 5 second delay is increased, the rules are properly instantiated and can also process the start level event.

**Comment by kaikreuzer** [comment] 2020-09-17 06:31
Oh oh, I faintly remember 😇 .
As a quick fix, we might just increase that. For the release, it would be nice to figure out a way to automatically determine the right moment for this start level event, which really is a bit tricky to do...

**Comment by wborn** [comment] 2020-09-17 09:07
Yes it's probably best to increase the delay for now so the impact of this issue is reduced.

I also noticed that this is sometimes an issue for rules created in the UI depending on how fast everything starts.

Another change in behavior I noticed is that previously rules with a "System started" condition were also executed after .rules files were saved. That may actually have fixed a bug but the change may not be immediately clear to users upgrading from OH2. It's still possible to run those rules by running them manually via the UI.

Users creating rules with startlevel triggers in the UI will also have a hard time to get these working because they need to know that they specifically have to enter "20" as the [handler does an equals check](https://github.com/openhab/openhab-core/blob/81e82e7d4473f0eb73878135d97e3c9c46c85659/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java#L96-L99) and the UI doesn't help them either :wink: :

![startlevel](https://user-images.githubusercontent.com/12213581/93450021-bebcfb00-f8d5-11ea-9b2d-0df10cedad3a.png)

**Comment by lolodomo** [comment] 2020-10-26 23:19
I just started to play with DSL rules in OH3.
This is really cool to be able to disable/enable each rule.

Unfortunately, I can confirm that my rule with trigger "System started" is randomly run at OH startup; sometimes it is run, sometimes it isn't.
Was it supposed to be fixed by the increase of the delay ?

**Comment by wborn** [comment] 2020-10-26 23:45
It fixed the issue for me but I can imagine the delay needs to be longer if your hardware is slower or you have more rules etc. to load. That's why I kept this issue open since the delay will not work for every setup and it causes unnecessary waiting on faster setups. 

The issue is that not all rules may have been instantiated when the `StartlevelEvent` is posted so in that case they will not be triggered.

**Comment by lolodomo** [comment] 2020-10-26 23:54
What looks strange is that my tests were run on a RPI3 with only 5 little rules.
I am basing on a log (call to logInfo in the rule) to say whether the rule was run or not.

**Comment by jewesta** [comment] 2020-11-04 03:07
> Another change in behavior I noticed is that previously rules with a "System started" condition were also executed after .rules files were saved. That may actually have fixed a bug but the change may not be immediately clear to users upgrading from OH2.

Just wanted to give a user‘s perspective. It took me a while to figure out that this no longer worked in OH 3. Until I found & read this discussion I thought it was a bug. I had always assumed that triggering „System started“ on „rules saved“ had been done on purpose. Consequently this has always been part of my workflow. It was a very convenient (albeit „hacky“) way of e.g. quickly „injecting“ values into items. I have also modelled all my rules with System started triggers as to be tolerant of repeated „rule saved“ events. Triggering a rule from the UI is cumbersome in comparison. Not saying it was perfect in OH 2 but I would argue that it is breaking something that was not necessarily a bad thing and it is a change that will probably surprise many.

**Comment by lolodomo** [comment] 2020-11-12 14:06
> This issue is caused by a [very dirty hack](https://github.com/openhab/openhab-core/blob/81e82e7d4473f0eb73878135d97e3c9c46c85659/bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java#L121-L132).
> When the 5 second delay is increased, the rules are properly instantiated and can also process the start level event.

Ah ok, the dirty hack is already identified.
Due to this hack, if the start level 20 is triggered too early, before the rule stuff is ready, the rules with trigger "System started" will never be run.

In case the dirty hack cannot be replaced by something more clever, either we have to increase the delay (currently 15 seconds)  to a value reasonable for a slow machine like a RPI, or make it a configuration setting for the user.

**Comment by lolodomo** [comment] 2020-11-12 14:11
Just by curiosity, was this dirty hack with the delay of XX seconds already present in OH2 ? Or is it something new in OH3 ?

**Comment by lolodomo** [comment] 2020-11-12 14:29
In the same class (containing the dirty hack), I see that what is triggering the sent of the start level event is the ready mark set just after reloading the rules:
https://github.com/openhab/openhab-core/blob/0d1a15ef3470bcf350ed88679447e0f7e7adeafe/bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java#L167
Is `modelRepository.reloadAllModelsOfType("rules");` run synchrounously or asynchronously ?
If run asynchronously, the problem will be there as it will trigger the dirty hack when the rulme stuff is not ready.

**Comment by jewesta** [comment] 2020-11-23 22:39
I have 16 .rules files in my OH3 installation and am apparently affected by this issue. My OH installation is running on a Mac mini exclusively. But I assume that the relatively many individual .rules files add additional overhead for loading each file which leads to loading of all rules taking longer than 15 seconds.

Having read this whole thread: Did I understand it correctly that one workaround would be to create a "system started" rule via UI? In other words, UI based rules with a trigger "start level 20" should be executed regardless of this bug? Thanks!

**Closed** 2020-12-12 13:34 UTC
Labels: DSL rules, automation, bug

**Comment by ahielg** [comment] 2020-12-29 11:54
It still happens in v3.0.0
https://community.openhab.org/t/trigger-system-started-not-working/110813

**Comment by chris922** [comment] 2021-01-07 19:30
@kaikreuzer : Could it be that `System started` will not be invoked when changing rules or items files? I just found this comment from you maybe related to this:

> I was also thinking about adding an additional "rule loaded" trigger, to bring back the 2.x functionality that a rule is executed once whenever being modified. 

https://github.com/openhab/openhab-core/pull/1914#issuecomment-743758023

**Comment by Flole998** [comment] 2021-01-09 16:09
> @kaikreuzer : Could it be that `System started` will not be invoked when changing rules or items files? I just found this comment from you maybe related to this:
> 
> > I was also thinking about adding an additional "rule loaded" trigger, to bring back the 2.x functionality that a rule is executed once whenever being modified.
> 
> [#1914 (comment)](https://github.com/openhab/openhab-core/pull/1914#issuecomment-743758023)

I'm seeing the same thing (and this is causing issues for me), so I would love to see such an option (or the old behavior restored).

**Comment by kaikreuzer** [comment] 2021-01-09 23:05
It is quite complicated, especially as rules often need to be auto-reloaded when other files like items change.
My advice is hence to rather use the "run now" feature, whenever you require to run a rule at a specific moment.

**Comment by Flole998** [comment] 2021-01-09 23:10
You mean the button in the Webinterface? I should click that button for every rule when I reload the rules file?

To give a little background: I have rules that schedule a timer which runs the rule at a specific (dynamic) interval. Obviously when reloading the rule and if it isn't started initially this will stop working. This was working fine on OH 2.5.

There is a log entry "reloading xyz.rules", what is complicated about turning that into an event for all rules in that file?

**Comment by jewesta** [comment] 2021-01-10 07:17
@Flole998 I was caught off guard by this change as well. And I agree with you that it would be useful to have a trigger event based on the life cycle of a rule.

Having said this: Please remember that openHAB is an open source project and that the maintainers are not service providers sitting around twiddling their thumbs. 🙂 (Clarification: I‘m not a maintainer.) Sometimes problems appear to have easy solutions on the surface. But refactoring done on the OH3 engine might have made implementing the old behaviour impossible or very difficult.

To offer a suggestion: Use a SystemStarted switch item and use „item SystemStarted changed from OFF to ON“ instead of „System started“ as a trigger in your rules. Or use both only in your rules that need special timer initialization. Then have a specific rule that triggers the SystemStarted item on system start (maybe with a slight delay). By doing so you can now trigger the system start event separately, thereby initializing your rules. So you could have just one single rule that needs manual triggering via the UI.

I know this is not ideal.

If you need further assistance I suggest you create a topic in the community forums. You could mention this issue in the topic for reference.

**Comment by cweitkamp** [comment] 2021-01-10 16:13
I think we can split this discussion into two topics:

First one is the missing execution of Rules having "System started" or "System Start Level reached" after a Thing or an Item has added / updated / deleted. And in this case I am with @kaikreuzer and it may be sufficient to manually run related Rules - unless we want to introduce conditions to listen on the event bus for Thing added / updated / deleted or Item added / updated / deleted events.

Second topic is the missing feature that a Rule having above mentioned trigger runs immediately after it was changed. This imo could be detected easier and should be reintroduced in the new rule engine. wdyt?

Just for the record: IIRC the "System started" trigger in general does not exist anymore. It is transformed to a "System Start Level reached" trigger with start level 20. At least for DSL rules. Please correct me if I am wrong.

**Comment by Flole998** [comment] 2021-01-10 16:52
Yes, the "system started" trigger in a rule file is displayed in the Webinterface as "start level 20 reached", so most likely that's translated internally. 20 is probably not the ideal value but that doesn't really matter as there's a way to use different levels.

**Comment by kaikreuzer** [comment] 2021-01-11 21:46
>  IIRC the "System started" trigger in general does not exist anymore. It is transformed to a "System Start Level reached" trigger with start level 20.

For backward compatibility reasons it is still called "System started" within DSLs, but internally a "start level 20" trigger is indeed created - and as this start level is only reached once, it leads to the effect that the rule is not executed upon reload (which imho is also the more correct behavior for something called "system started").

> the missing feature that a Rule having above mentioned trigger runs immediately after it was changed. This imo could be detected easier and should be reintroduced in the new rule engine. wdyt?

Yes, that would be my comment from #1914: "I was also thinking about adding an additional "rule loaded" trigger, to bring back the 2.x functionality that a rule is executed once whenever being modified."
I'm not at all against this idea - it should be a trigger that is then also available within the UI; although this poses the question, what "loaded" actually means in that context. And as I've mentioned: I already tried to implement it, but noticed that it was more complex than expected, so I considered it too risky before the 3.0.0 release.

**Comment by dathbe** [comment] 2021-01-13 07:31
Am I right that this ("system started" triggers not actually executing when the rules file is updated) is still an issue?  I just started the upgrade process to 3.0 and it doesn't seem to be working for me.  The trigger works fine when OH is actually restarted, but it does not seem to work when the rules file is updated.  I have a couple rules that involve timers that need to be re-run every time anything of the config files change.  This works as expected in OH2.5, but doesn't appear to work yet in 3.0.  Is there a work-around?  Thanks!

**Comment by stefan-muc** [comment] 2021-01-13 14:39
> Am I right that this ("system started" triggers not actually executing when the rules file is updated) is still an issue?

From its name it should never trigger when a rule file is updated - see @kaikreuzer comment above. I also stumbled across this (in my opinion also wrong) behavior of  a "system started" rule triggered on rule file update, so I'm glad this issue got resolved.

So if you need a "rule loaded" trigger, maybe wait until @kaikreuzer moves forward with his implementation or let the system that changes your config files do a separate trigger afterwards?

**Comment by dathbe** [comment] 2021-01-13 16:06
> From its name it should never trigger when a rule file is updated

https://www.openhab.org/docs/configuration/rules-dsl.html#system-based-triggers

"System started is triggered upon openHAB startup, **after the rule file containing the System started trigger is modified**, or after item(s) are modified in a .items file."
