### ISSUE TITLE
[OH3] DSL rule failing sometimes at startup

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1777] opened 2020-10-31 11:05 UTC
OH3 snapshot 1995

Here ius a part of my DSL file:
```
import java.util.regex.Pattern

var Pattern patternVoice

rule "Démarrage"
when
	System started
then
	logInfo("Rule","Démarrage début")
	patternVoice = Pattern::compile("(donner|passer en hors gel|passer en mode confort|passer en mode réduit) (le |la |les |l'|du )(.*) (du |de la |de l'|dans le |dans la |dans l')(.*)")
	logInfo("Rule","Démarrage fin")
end
```
And here is what happens at startup:
```
11:53:52.167 [INFO ] [org.openhab.core.model.script.Rule   ] - Démarrage début
11:53:52.177 [ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'maison3-7' failed: An error occurred during the script execution: Cannot assign a value in null context. in maison3
```

**It does not occur at each restart, only sometimes.**

If I run later the rule from Main UI, it works as expected.
So there is probably something started too early at startup ?

**Comment by wborn** [comment] 2020-10-31 11:12
It doesn't seem to be something new according to these [community search results](https://community.openhab.org/search?q=Cannot%20assign%20a%20value%20in%20null%20context).

**Comment by lolodomo** [comment] 2020-10-31 11:15
Maybe this is new for the new rule engine ?
At least, now an issue is opened :) and I hope it can be solved ;)

**Comment by lolodomo** [comment] 2020-11-12 13:02
"Cannot assign a value in null context" : isn't it something that should help what's wrong here ?

Is it this method that is called with a null parameter ?
https://github.com/openhab/openhab-core/blob/584c85a07f760216b2c42f482a7800bfe064b0d3/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java#L56
Could it be linked to the fact that my rule trigger is "System started" ?
@wborn @kaikreuzer : Maybe the rule is called too early when this "context" is still not yet set ?

**Comment by lolodomo** [comment] 2020-11-12 13:06
If the problem is linked to trigger "System started", could the framework waits for this "context" to be ready (not null) before triggering the rule ?

**Comment by lolodomo** [comment] 2020-11-12 13:38
https://github.com/openhab/openhab-core/blob/0d1a15ef3470bcf350ed88679447e0f7e7adeafe/bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java#L177
It looks like there is a hardcoded delay of 15 seconds set before triggering the start level trigger. That might be the problem. Why 15 seconds ? Maybe we should increase it to be more secure ?

**Comment by lolodomo** [comment] 2020-11-12 13:40
Could the delay be at least something that the user could setup ? For RPI, this could then be increased by the user.

**Comment by lolodomo** [comment] 2020-11-12 19:23
May the problem be relative to the global part of the DSL rule (declaration of the variable `patternVoice`) not yet loaded when the "system started" rule is run ?

**Comment by cweitkamp** [comment] 2020-11-21 19:54
Is this a duplicate of #1637?

**Comment by lolodomo** [comment] 2020-11-21 20:04
No, this issue mentions an error when the rule is run while the other mentions the rule being not always run.
That is two different problems.

**Closed** 2020-12-12 13:34 UTC
Labels: DSL rules, automation, bug
