### ISSUE TITLE
NPEs in snapshot 1276

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#343] opened 2018-05-15 07:26 UTC
Starting at snapshot #1276, I keep seeing NPEs. First two are 'unforced' (I believe triggerd by ZWave message receipt), last two happen if I issue ZWave commands on specific items.
Garten_Auge2_Temp is a battery device (to only send updates every 1 or 2 hours) so item state was possibly (likely even) uninitialized at that stage, but can't tell for sure.
TempAussen is a group to contain Garten_Auge2_Temp.

Don't think it's ZWave related. Didn't change zwave binding (development version) nor devices, just upgraded from #1275. NPEs seem to have disapperead after going back to #1274.

```

2018-05-15 08:33:40.540 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener 'org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl@1e043a2' about state update of item TempAussen: null
java.lang.NullPointerException: null
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetChangeRules(RuleTriggerManager.java:336) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetRules(RuleTriggerManager.java:427) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.getRules(RuleTriggerManager.java:198) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.stateChanged(RuleEngineImpl.java:202) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.core.items.GenericItem$1.run(GenericItem.java:251) [101:org.eclipse.smarthome.core:0.10.0.201805141751]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-05-15 08:33:40.541 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener 'org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl@1e043a2' about state update of item Garten_Auge2_Temp: null
java.lang.NullPointerException: null
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetChangeRules(RuleTriggerManager.java:336) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetRules(RuleTriggerManager.java:427) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.getRules(RuleTriggerManager.java:198) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.stateChanged(RuleEngineImpl.java:202) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.core.items.GenericItem$1.run(GenericItem.java:251) [101:org.eclipse.smarthome.core:0.10.0.201805141751]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]








2018-05-15 08:43:39.283 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'EventSubscriber.receive()' on 'org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl@1e043a2': null
java.lang.NullPointerException: null
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetCommandRules(RuleTriggerManager.java:378) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetRules(RuleTriggerManager.java:437) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.getRules(RuleTriggerManager.java:210) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.receiveCommand(RuleEngineImpl.java:222) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.receive(RuleEngineImpl.java:437) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [101:org.eclipse.smarthome.core:0.10.0.201805141751]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [101:org.eclipse.smarthome.core:0.10.0.201805141751]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-05-15 08:43:39.297 [ERROR] [me.core.internal.events.EventHandler] - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: null
java.lang.NullPointerException: null
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetCommandRules(RuleTriggerManager.java:378) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetRules(RuleTriggerManager.java:437) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.getRules(RuleTriggerManager.java:210) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.receiveCommand(RuleEngineImpl.java:222) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.receive(RuleEngineImpl.java:437) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [101:org.eclipse.smarthome.core:0.10.0.201805141751]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [101:org.eclipse.smarthome.core:0.10.0.201805141751]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by kaikreuzer** [comment] 2018-05-15 07:35
Duplicate of https://github.com/eclipse/smarthome/issues/5578

**Closed by kaikreuzer** 2018-05-15 07:35 UTC
