### ISSUE TITLE
SSE breaks due to BundleException in SseActivator.start() on first startup

### ISSUE THREAD

**Issue by ScottKinSF** [openhab/openhab-core#597] opened 2019-02-23 18:17 UTC
My test system is running OH 2.5.0-SNAPSHOT s1530 on up-to-date OpenHABian on an RPi3. When the bundle org.openhab.core.io.rest.sse is started, the following exception is logged:
```
2019-02-23 11:07:57.836 [ERROR][lisher@754ba872][org.openhab.core.io.rest.sse        ] - FrameworkEvent ERROR - org.openhab.core.io.rest.sse
org.osgi.framework.BundleException: Exception in org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start() of bundle org.openhab.core.io.rest.sse.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309) ~[?:?]
        at org.eclipse.osgi.container.Module.doStart(Module.java:581) ~[?:?]
        at org.eclipse.osgi.container.Module.start(Module.java:449) ~[?:?]
        at org.eclipse.osgi.framework.util.SecureAction$23.run(SecureAction.java:474) ~[?:?]
        at org.eclipse.osgi.framework.util.SecureAction$23.run(SecureAction.java:1) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:472) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.start(ModuleContainer.java:750) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:741) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:511) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:457) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1001) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1382) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1) ~[?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
Caused by: java.lang.LinkageError: ClassCastException: attempting to castbundleresource://33.fwk1627821297/javax/ws/rs/ext/RuntimeDelegate.class to bundleresource://33.fwk1627821297/javax/ws/rs/ext/RuntimeDelegate.class
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:146) ~[?:?]
        at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120) ~[?:?]
        at javax.ws.rs.core.MediaType.valueOf(MediaType.java:179) ~[?:?]
        at org.glassfish.jersey.media.sse.SseFeature.<clinit>(SseFeature.java:62) ~[?:?]
        at org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start(SseActivator.java:49) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772) ~[?:?]
        ... 18 more
```
To be sure this was not a version upgrade issue, I cleared cache and tmp after stopping OH, then restarted OH.

**Comment by wborn** [comment] 2019-02-24 02:21
You'll occasionally run into this on the first startup. It's the same issue as: https://github.com/eclipse/smarthome/issues/6682

**Comment by ScottKinSF** [comment] 2019-02-25 22:52
Just wanted to confirm that after another restart this exception did not occur.

**Comment by cweitkamp** [comment] 2019-05-13 06:53
This exception still occurs in OH 2.5.0 build 1589, when installing a binding via Paper UI. I can see a `ClassCastException` in the logs:

```
2019-05-13 08:44:26.190 [ERROR] [org.openhab.core.io.rest.sse        ] - FrameworkEvent ERROR - org.openhab.core.io.rest.sse
org.osgi.framework.BundleException: Exception in org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start() of bundle org.openha
b.core.io.rest.sse.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309) ~[?:?]
        at org.eclipse.osgi.container.Module.doStart(Module.java:581) ~[?:?]
        at org.eclipse.osgi.container.Module.start(Module.java:449) ~[?:?]
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.start(ModuleContainer.java:750) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:741) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:511) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:457) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1001) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1382) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1) ~[?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
Caused by: java.lang.LinkageError: ClassCastException: attempting to castbundleresource://34.fwk17043482/javax/ws/rs/ext/RuntimeDeleg
ate.class to bundleresource://34.fwk17043482/javax/ws/rs/ext/RuntimeDelegate.class
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:146) ~[?:?]
        at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120) ~[?:?]
        at javax.ws.rs.core.MediaType.valueOf(MediaType.java:179) ~[?:?]
        at org.glassfish.jersey.media.sse.SseFeature.<clinit>(SseFeature.java:62) ~[?:?]
        at org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start(SseActivator.java:47) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772) ~[?:?]
        ... 15 more
2019-05-13 08:44:28.029 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-kodi': Error restarting b
undles:
        Exception in org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start() of bundle org.openhab.core.io.rest.sse.
```

**Comment by kaikreuzer** [comment] 2019-05-13 07:10
I am seeing the same and much more often than before - it is not just "sporadic" anymore.

**Comment by wborn** [comment] 2019-05-26 12:15
It looks like https://github.com/openhab/openhab-core/pull/739 might also fix this. I see the `SseActivator` is removed in that PR. :-)

**Comment by maggu2810** [comment] 2019-06-09 17:07
Test workaround: 
https://github.com/maggu2810/openhab-core/commit/fbe127de0444eb0fed4fe8fc1cf0edeead0d99d2

**Comment by wborn** [comment] 2019-06-09 20:28
I gave the workaround a try but still ran into an exception after a couple of clean installs:

```
org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
	Exception in org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start() of bundle org.openhab.core.io.rest.sse.
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1005)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1058)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:994)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: org.osgi.framework.BundleException: Exception in org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start() of bundle org.openhab.core.io.rest.sse.
		at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800)
		at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
		at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
		at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
		at org.eclipse.osgi.container.Module.doStart(Module.java:581)
		at org.eclipse.osgi.container.Module.start(Module.java:449)
		at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
		at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
		at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:161)
		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1149)
		at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:997)
		... 6 more
	Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.glassfish.jersey.media.sse.SseFeature
		at org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start(SseActivator.java:75)
		at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
		at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
		at java.security.AccessController.doPrivileged(Native Method)
		at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
		... 16 more
```

The line number (SseActivator.java:75) matches with the updated code. More workarounds are more than welcome! :-)

**Comment by maggu2810** [comment] 2019-06-09 21:21
Please enable the trace logging for `org.eclipse.smarthome.io.rest.sse.internal`.
What needs to be done to reproduce that error?

**Comment by maggu2810** [comment] 2019-06-09 21:48
@wborn I assume your error is another story and should not occur at all.

`Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.glassfish.jersey.media.sse.SseFeature`

I don't expect a NCDFE. The package of that class should be present (by OSGi) but the respective class is missing. So, does a bundle export that package without this class, too?

**Comment by wborn** [comment] 2019-06-09 21:59
Most of the time it can be reproduced when starting the openHAB runtime for the first time and then immediately selecting the Demo package. The second time openHAB is started after a clean install or update it no longer occurs.

I'll attach some trace logging if it helps.

> I don't expect a NCDFE.

I think the class is there but it probably fails when initializing the `SERVER_SENT_EVENTS_TYPE` field:

```java
public class SseFeature implements Feature {
    /**
     * {@link String} representation of Server sent events media type. ("{@value}").
     */
    public static final String SERVER_SENT_EVENTS = "text/event-stream";
    /**
     * Server sent events media type.
     */
    public static final MediaType SERVER_SENT_EVENTS_TYPE = MediaType.valueOf(SERVER_SENT_EVENTS);
```

When checking `MediaType.valueOf` you'll see there's some non-trivial logic being executed.

**Comment by maggu2810** [comment] 2019-06-09 22:14
Yes, that should be addressed by my commit or at least worked around (a try).

But your comment does not show a stack trace that enters the `valueOf` method (compare with the above ones that return a LinkageError).

**Comment by openhab-5iver** [comment] 2019-06-09 22:20
FWIW, after a cache clearing and a few restarts, I did not see any SSEActivator errors after applying Markus' workaround.

**Comment by wborn** [comment] 2019-06-09 22:35
Here's the logging while reproducing the `NoClassDefFoundError`:

[logging.txt](https://github.com/openhab/openhab-core/files/3270026/logging.txt)

After starting the runtime you can setup the logging, install the demo package and tail the logging with this one liner:

`log:set trace org.eclipse.smarthome.io.rest.sse.internal && feature:install openhab-package-demo && log:tail`

**Comment by maggu2810** [comment] 2019-06-09 22:40
The logic has been wrong of the while check.
Please create the log again using 4ade3cd4cb4aaa5c0338780a33528139b4e09bfc

**Comment by wborn** [comment] 2019-06-09 23:27
With the proper logic the workaround now works all the time (20x) for me! :-) 
So would be nice to see a PR with this workaround. :+1: 

I've been testing this with a fast desktop. We can always increase the `millisMax` value if it doesn't always work for users with slower hardware like Raspberry Pi's.

**Comment by maggu2810** [comment] 2019-06-10 07:35
See #863

**Closed** 2019-06-10 09:28 UTC
Labels: REST/SSE, bug
