### ISSUE TITLE
Wrong TimeZone in DateTime item

### ISSUE THREAD

**Issue by HerzScheisse** [openhab/openhab-core#832] opened 2019-05-25 22:31 UTC
Hi,
I Hope this is the right place here in the openhab core issue tracker.

I'm running on the snapshot #1600 and figured some strange timezone errors with DateTime items and really spent alomst a day to be sure that its not my fault of doing things the wrong way... 

My item file:
```DateTime TestTime "[%1$tA, %1$td.%1$tm.%1$tY %1$tH:%1$tM]"```
the part in my rules
```
    val String time = transform("JSONPATH", "$.data[0].position.since", json)
    var DateTime JDT_time = parse(time.toString)
    var DateTimeType DTT_time = new DateTimeType(JDT_time.toString)
    TestTime.postUpdate(DTT_time)
```
I get the time string from the API in this format:
```2019-05-25T17:53:10+00:00```

the logger prints me the DTT_time in this format:
```2019-05-25T17:53:10.000+0000```

Basic UI sitemap shows me:
```Samstag, 25.05.2019 17:53```

HABPanel widget code:
```{{itemValue('TestTime') | date:"EEE HH:mm"}}```
is resulting in
```Sa. 19:53``` <--- THIS is the correct value with my +2 timezone

I douple/triple checked all timezone settings and made sure they are in Europe/Berlin
- In PaperUI
- In openhabian config
- also added in /etc/default/openhab2 the EXTRA_JAVA_OPTS="-Duser.timezone=Europe/Berlin"

I dont know why i get the correct Date in HabPanel but NOT in BasicUI in my sitemap...

Is this a issue? or did i missed something?

Thanks for your help.

**Comment by maggu2810** [comment] 2019-05-27 07:43
It seems the Basic UI does not convert the timestamp that has been parsed into the timezone you would like to use.
I assume it is more UI related.

**Comment by lolodomo** [comment] 2019-07-20 07:23
Basic UI is not manipulating dates but only displays formatted dates as text it receives from the server. I would assume the formatting is wrong on server side. The timezones is ignored ?

**Comment by cweitkamp** [comment] 2019-07-20 07:37
@HerzScheisse May I ask you to extend your rule and log the value for `TestTime` too? Additionaly it would make sense to have a look which timezone is use for both:

```
logInfo("test", "timezone: {}", TestTime.getZonedDateTime().getZone()")
```

**Comment by lolodomo** [comment] 2019-07-20 07:44
When the page is loaded, here is where the label is computed:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java#L548
So we just call the method format from the state using the pattern provided in the item.

**Comment by lolodomo** [comment] 2019-07-20 07:51
The SSE event that includes the formatted text as label is going through the same code.

**Comment by lolodomo** [comment] 2019-07-20 07:55
Here is where the formatting is done:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java#L133

**Comment by lolodomo** [comment] 2019-07-20 08:02
I think the problem is not in server or Basic UI but probably more in the way the DateTimeType is built in th erule.
When the constructor is called with a string as a parameter, this method is called:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java#L87
Don't know if the correct timezone is used in this case.

**Comment by lolodomo** [comment] 2019-07-20 08:12
This might be just a bad format of the string built by `transform("JSONPATH", "$.data[0].position.since", json)`

**Comment by HerzScheisse** [comment] 2019-07-22 06:48
> @HerzScheisse May I ask you to extend your rule and log the value for `TestTime` too? Additionaly it would make sense to have a look which timezone is use for both:
> 
> ```
> logInfo("test", "timezone: {}", TestTime.getZonedDateTime().getZone()")
> ```
Hi @cweitkamp 
Sorry i cant test this anymore.
After the problems with the date, i switched to the new rule engine with javascript jsr223 rules. there are alot more possibilities there. and i'm very happy that i switched to the NRE

**Comment by cweitkamp** [comment] 2019-07-22 15:14
No problem. I wrote a test rule on my own. Parsing the string from your API  "2019-05-25T17:53:10+00:00" results in TimeZone "Z" (normalized ZoneOffset showing the time in ‘UTC+/-’). The framework itself does not apply your timezone "Europe/Berlin". If you want to change the given timestamp to your timezone you have to take care on your own:

```
    @Test
    public void formattingTest() {
        DateTimeType dt1 = new DateTimeType("2019-05-25T17:53:10+00:00");
        assertThat(dt1.toFullString(), is(dt1.toString()));
        assertThat(dt1.toString(), is("2019-05-25T17:53:10.000+0000"));

        assertThat(dt1.format(null), is("2019-05-25T17:53:10"));
        assertThat(dt1.format("%1$td.%1$tm.%1$tY %1$tH:%1$tM"), is("25.05.2019 17:53"));

        assertThat(dt1.format(Locale.GERMAN, "%1$td.%1$tm.%1$tY %1$tH:%1$tM"), is("25.05.2019 17:53"));

        DateTimeType dt2 = new DateTimeType(dt1.getZonedDateTime().withZoneSameInstant(ZoneId.of("Europe/Berlin")));
        assertThat(dt2, not(is(dt1)));
        assertThat(dt2.toString(), is("2019-05-25T19:53:10.000+0200"));

        assertThat(dt2.format(null), is("2019-05-25T19:53:10"));
        assertThat(dt2.format("%1$td.%1$tm.%1$tY %1$tH:%1$tM"), is("25.05.2019 19:53"));

        assertThat(dt2.format(Locale.GERMAN, "%1$td.%1$tm.%1$tY %1$tH:%1$tM"), is("25.05.2019 19:53"));
    }
```

I do not know why HABPanel shows the DateTime in your expected timezone. Maybe a feature. From my point of view either the framework as well as Basic UI currently are doing it correctly. It could be worth moving this issue to https://github.com/openhab/openhab-webui and discuss if it is a valid enhancement for Basic UI. IMO over here we can close it because the framework should not automatically apply a local timezone.

**Comment by lolodomo** [comment] 2019-07-22 15:36
I am not sure but I think the right way to do it (in the rule) would be to instantiate a DateTimeType not with a String as parameter but with a ZonedDateTime.
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java#L83
Or with a Calendar as parameter: https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java#L74

**Comment by cweitkamp** [comment] 2019-07-22 20:53
That does not matter. The String will be parsed internally by `ZonedDateTime.parse()` to an appropriate instance of it.

I would suggest to add some small extensions to the `DateTimeType` to make it easier for users and/or developers to handle different timezone (e.g. a ctor which converts a given String directly into the target timezone and a method to convert the state into a different timezone). Wdyt?

 ```
public DateTimeType(String value, String/ZoneId zone) {
    // TODO
}

public DateTimeType toZone(String/ZoneId zone) {
    // TODO
}
```

**Comment by lolodomo** [comment] 2019-07-27 08:08
If I correctly analyzed the issue, the problem is more general and not restricted to dates built in a rule like in the example. Any date built (by a binding for example) with a different timezone than the local timezone will not be formatted with the local timezone (and so not displayed with the local timezone in Basic UI). The real problem is the format method of DateTimeType IMHO. We are using a simple String.format and of course this is just missing the timezone. The conversion to the local timezone should occur by default in this format method.
Just doing a quick search, it looks like DateTimeFormatter could be a better way to achieve what we want, rather than String.format.

**Comment by lolodomo** [comment] 2019-07-27 08:44
In fact, I see that the two constructors with Calendar and ZonedDateTime are using withFixedOffsetZone() which converts to the local timezone if I correctly understand it.
The constructor with String as parameter is not applying the same withFixedOffsetZone().
So maybe, the solution would be to replace at this line
https://github.com/openhab/openhab-core/blob/1acb9c8ff223d1670486d1b2903a4a36acdfd150/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java#L111
by:
`zonedDateTime = date.withFixedOffsetZone();`
WDYT ?

**Comment by lolodomo** [comment] 2019-07-27 08:51
Maybe a better option would be to use withZoneSameLocal in the format method ?

**Comment by lolodomo** [comment] 2019-07-27 09:11
Any date built with a different timezone than the locale timezone will have this problem.

I think the problem is in the format method. We should consider a conversion to the local timezone in the format method to format the zoned date time to the local timezone.

I also see that withFixedOffsetZone() is not applied to ZonedDateTime built from a string while it is for those built from Calendar or ZonedDateTime. Don't know if thios is a bug or not.

**Comment by lolodomo** [comment] 2019-07-27 09:38
WDYT about doing that in the format method:
`return String.format(pattern, zonedDateTime.toLocalDateTime().atZone(ZoneId.systemDefault()));`

**Comment by lolodomo** [comment] 2019-07-27 09:51
Or maybe rather:
`return String.format(pattern, zonedDateTime.withZoneSameInstant(ZoneId.systemDefault()));`

**Comment by lolodomo** [comment] 2019-07-27 10:16
Of course, as this changes the result of format method, we will have to search where this method is called in core and bindings.

We could also add a second format method with ZoneId as parameter and keep the existing method unchanged. In this case, we are sure to break nothing. Then we will just have to change the UI backend to use the new method for DateTimeType states.

**Comment by cweitkamp** [comment] 2019-07-27 11:33
Now we got something to dig deeper into: the internal representation. We first should be sure that all the different ctors result in the same internal respresentation before changing the format method. The outcome should be the same regardless if one passes a `Calendar`, a `ZonedDateTime` or a `String`. May I ask you to check that?

**Comment by lolodomo** [comment] 2019-07-27 20:03
After searching where DateTimeType.format could be used in openhab2, core, webui, zwave and zigbee repos, I only found its usage only in:

* knx binding (sure)
* neeo binding (potentially)
* habot UI (potentially)
* core UI which is the place where we want the change

**Comment by lolodomo** [comment] 2019-07-27 20:22
@kaikreuzer @sja (sorry I am not sure who is maintening the KNX binding): do you see any problem if DateTimeType.format would finally consider the system timezone in this method:
https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java#L948

**Comment by kaikreuzer** [comment] 2019-07-27 20:35
I am not fully clear on what "consider the system timezone" means here, so I cannot judge the effect on the KNX binding. In general, I would expect this method to not do any kinds of time zone adjustments, because on the KNX side, there isn't such a thing as a time zone information - so whatever value is passed in should imho be kept as it is.

**Comment by lolodomo** [comment] 2019-07-27 20:56
If the KNX binding is not providing any timezone, DateTimeType will build a ZonedDateTime with the default system timezone:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java#L209
So in this case,  my proposed change will have absolutely no impact at all.
By the way, this is a missing use case in our tests. I will add it (date without timezone).

**Comment by lolodomo** [comment] 2019-07-27 22:59
I can confirm that a DaTimeType built from a string has a different zone ID than the equivalent built from a ZonedDateTime due to the lack of withFixedOffsetZone() when parsing the string.
This can be fixed easily.

**Comment by lolodomo** [comment] 2019-07-29 18:03
In complement to my PR that enhanced DateTimeType with additional methods, I am preparing another PR that enhance the testing of the REST sitemap API, showing in particular that the built widget labels for DateTime items ignore the local time zone but just format the date/time considering the current time zone in the DateTimeType channel state.

**Closed** 2019-08-17 20:28 UTC
Labels: UI
