### ISSUE TITLE
PaperUI does not Refresh the display when under "Control" an in a special "Location"

### ISSUE THREAD

**Issue by lubeda** [openhab/openhab-core#123] opened 2017-02-19 11:08 UTC
When i am under Control and have a certain Location selected e.g. Living room and i click on the refresh button. The Control display is empty and no lacations are shown.

I have to click to Inbox and then again to Control to get my Locations back

**Comment by kaikreuzer** [comment] 2017-02-19 11:33
Duplicate of https://github.com/eclipse/smarthome/issues/2885

**Closed by kaikreuzer** 2017-02-19 11:33 UTC
