### ISSUE TITLE
CustomLogging an Idea

### ISSUE THREAD

**Issue by agh251256** [openhab/openhab-core#2393] opened 2021-05-30 16:59 UTC
I don't know, I'm right here with my idea.
Is it possible changing the file org.ops4j.pax.logging.cfg from
`org.ops4j.pax.logging.log4j2.config.file=${karaf.etc}/log4j2.xml
`
to

`org.ops4j.pax.logging.log4j2.config.file=${karaf.etc}/log4j2.xml
org.ops4j.pax.logging.log4j2.config.file=${openhab-conf}/logging/customlog.xml
`
with an examplefile?

The idea is never changing the original files if customer will make his own log. I think openhab-conf is the dir under linux /etc/openhab for site configuration.

Its only an idea

**Comment by kaikreuzer** [comment] 2021-05-30 19:48
I guess this is a duplicate of https://github.com/openhab/openhab-distro/issues/516, right?

**Comment by agh251256** [comment] 2021-05-30 21:57
I don`t know


----- Originale Nachricht -----
Von: Kai Kreuzer ***@***.***>
Gesendet: 30.05.2021 - 21:48
An: openhab/openhab-core ***@***.***>
Betreff: Re: [openhab/openhab-core] CustomLogging an Idea (#2393)

> I guess this is a duplicate of https://github.com/openhab/openhab-distro/issues/516, right?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/openhab/openhab-core/issues/2393#issuecomment-851051673


-- 
Andreas Guhr
----------------------
um mein Signaturzertifikat auf Echtheit prüfen zu können, benötigen Sie das Wurzel(Root)zertifikat von CAcert: https://www.cacert.org/index.php?id=3

**Closed** 2021-05-31 05:20 UTC
Labels: duplicate
