### ISSUE TITLE
[sitemap] Add labelcolor and visibility to a single button of a Buttongrid

### ISSUE THREAD

**Issue by Hajuskin** [openhab/openhab-core#4173] opened 2024-03-06 21:52 UTC
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem
I use the new Buttongrid element to build a page in Basic UI as an overview for most of my switchable items. This is a great way to have a dense layout. I use a rule to actually switch the items represented by the buttons, but the state of a switch is of course not shown.

## Your suggestion
Having the ability to use the `labelcolor` and `visibility` syntax for every single button of a Buttongrid could be very useful for having a compact overview of  e.g. open doors/windows, triggered motion sensors or in my case switchable items with their states represented by the buttons label color.

So the syntax could be something like:
`buttons=[row_1:column_1:command_1="description_1":labelcolor=[switch_item1==ON="green", switch_item1==OFF="gray"], ...`
or
`buttons=[row_1:column_1:command_1="description_1":visibility=[tamper_item1==ON], ...`

## Your environment

```yaml

```

**Comment by lolodomo** [comment] 2024-04-21 06:44
labelcolor, iconcolor, visibility parameters can only be applied to a sitemap element. It is handled at sitemap element level in core framework.
To achieve your request, we should create a new sitemap element `Button` as a sub element of a `Buttongrid`. The current `buttons` parameter of `Buttongrid` will then be replaced by a list of `Button` inside `Buttongrid`. Then each `Button` element, like any other sitemap element could have parameters `labelcolor`, `iconcolor`, `visibility`.
The syntax would be something like that:
```
Buttongrid label= {
    Button line=X column=Y item=xxx command=xxx label="xxx" icon=xxx labelcolor=[xxx] iconcolor=[xxx] visibility=[xxx]
    Button line=X column=Y item=xxx command=xxx label="xxx" icon=xxx labelcolor=[xxx] iconcolor=[xxx] visibility=[xxx]
    Button line=X column=Y item=xxx command=xxx label="xxx" icon=xxx labelcolor=[xxx] iconcolor=[xxx] visibility=[xxx]
}
```
It even makes the syntax easier for the user.
It has also the advantage that each button can be linked to a different item.
Today, I believe we should have gone in that direction at the beginning.

We could keep backward compatibility by making the `buttons` parameter optional. If no `Button` are declared but a `buttons` parameter is set, we can consider the current behaviour.

It is relatively easy to enhance in the core framework, I can do it. The biggest changes are to be implemented in each sitemap UI. I could do it for Basic UI. @openhab/android-maintainers : are you interested to implement this enhancement in the Android app ?

@openhab/ios-maintainers for information (if I am not wrong, Buttongrid is not yet implemented in the iOS app).

**Comment by mueller-ma** [comment] 2024-04-21 08:02
The suggested syntax is much more readable than the current one 👍 

Adapting the Android app should be doable.

**Comment by lolodomo** [comment] 2024-04-30 13:14
@mueller-ma : it is probably too late for 4.2 regarding all the changes to do ? I am not sure if we break the sitemap REST API or if we keep the current API response structure when `buttons` parameter is used and have a new one when buttons are sub-elements of the `Buttongrid` ? I imagine it will be better to have a (new) unique structure of response not depending on whether the buttons were declared in the `buttons` parameter or as sub-elements. But then this will become a breaking change for the Android app. WDYT ?

**Comment by mueller-ma** [comment] 2024-05-05 20:40
Yes, maybe it's the best to update the API when using the new syntax.

**Comment by lolodomo** [comment] 2024-05-07 08:39
This will lead to something even more powerful than today, with buttons in the grid that can be linked to different items, with buttons that can be stateless or stateful, and with conditional icon / color / visibility.

**Comment by lolodomo** [comment] 2024-05-08 10:09
In the core PR I just proposed, I increased the version of REST API so that you can know if new structure is supported by the server. Sitemap REST API response still contains a list of `MappingDTO` in field `mappings` if the old `buttons` parameter is used.
It includes a list of `WidgetDTO` in field `widgets` in case the grid contains Button elements.

**Comment by lolodomo** [comment] 2024-05-09 12:08
The proposed syntax for the Button is :
```
Button item=<item> [label=<label>] [icon=<icon>] row=<row> column=<column> [stateless] click=<cmd> [release=<cmd>] [labelcolor=[...]] [valuecolor=[...]] [iconcolor=[...]]
Button item=<item> [label=<label>] [staticIcon=<icon>] row=<row> column=<column> [stateless] click=<cmd> [release=<cmd>] [labelcolor=[...]] [valuecolor=[...]] [iconcolor=[...]]
Button item=<item> [label=<label>] [icon=[...]] row=<row> column=<column> [stateless] click=<cmd> [release=<cmd>] [labelcolor=[...]] [valuecolor=[...]] [iconcolor=[...]]
```
Required parameters are: item, row, column and click.
Optional parameters are: label, icon, stateless, release, labelcolor, valuecolor and iconcolor.

**Comment by lolodomo** [comment] 2024-05-11 10:31
Fully implemented in Basic UI now.

The only current limit is that Basic UI only supports one button at a certain position in the grid. So you can now use the visibility parameter to show or hide a button in the grid but you can't define several buttons at the same position with different visibility conditions in order to switch between buttons. I could try to enhance that later but with the constraint that there will be always only one visible button at a position in the grid.

**Comment by lolodomo** [comment] 2024-05-18 14:42
> Adapting the Android app should be doable.

@mueller-ma : it is now merged, so you can work on it for Android when you like.
I will update sitemap documentation.

**Comment by mherwege** [comment] 2024-05-18 15:10
@lolodomo Do I get this right that the UI sitemap builder needs to be changed as well to support this additional functonality?

**Comment by lolodomo** [comment] 2024-05-18 15:12
Yes @mherwege , correct.

**Comment by mherwege** [comment] 2024-05-18 15:15
And the old version of the still works as well? I don’t think that is appropriate for UI configuration. I need to think about how to cope with this.

**Comment by lolodomo** [comment] 2024-05-18 15:23
> And the old version of the API still works as well?

Yes, both are accepted.
You can even combine both.

**Comment by lolodomo** [comment] 2024-05-18 17:55
> The only current limit is that Basic UI only supports one button at a certain position in the grid. So you can now use the visibility parameter to show or hide a button in the grid but you can't define several buttons at the same position with different visibility conditions in order to switch between buttons at a certain position in the grid. I could try to enhance that later but with the constraint that there will be always only one visible button at a position in the grid.

Finally implemented: openhab/openhab-webui#2580

**Comment by lolodomo** [comment] 2024-05-21 11:20
I discovered an issue when the Buttongrid + Button are in a sub-page. It leads to this error when the sitemap is loaded:
```
Linkable widget should not contain Button, Button is allowed only in Buttongrid
```
and the Buttongrid is then not rendered by Basic UI.
Of course the error is wrong as all my Button elements are in a Buttongrid element.

**Comment by jimtng** [comment] 2024-05-21 14:01
> I discovered an issue in the sitemap validation code I added, when the Buttongrid + Button are in a sub-page. It leads to this error when the sitemap is loaded and validated:
> 
> ```
> Linkable widget should not contain Button, Button is allowed only in Buttongrid
> ```
> 
> and the Buttongrid is then not rendered in Basic UI.

I noticed this when the `Buttongrid` isn't assigned an item like this:
```
sitemap test {
  Frame {
    Buttongrid {
      Button item=TestSwitch1 row=1 column=1 click="ON" label="ON" visibility=[TestSwitch1!=ON]
      Button item=TestSwitch1 row=1 column=1 click="OFF" label="OFF" visibility=[TestSwitch1==ON]
    }
  }
}
```

But when I assigned an item to Buttongrid, it worked fine. In both cases, they're nested inside a Frame.
```
sitemap test {
  Frame {
    Buttongrid item=TestSwitch1 {
      Button item=TestSwitch1 row=1 column=1 click="ON" label="ON" visibility=[TestSwitch1!=ON]
      Button item=TestSwitch1 row=1 column=1 click="OFF" label="OFF" visibility=[TestSwitch1==ON]
    }
  }
}
```

**Comment by lolodomo** [comment] 2024-05-21 15:27
Yes, I noticed the same. Strange that it depends on presence of item parameter...

**Comment by lolodomo** [comment] 2024-05-21 17:35
In fact, the problem is when there is no parameter set for the Buttongrid element. Adding any parameter (item or label or labelcolor or iconcolor ...) solves the issue. It does not depend if the Buttongrid element is on the main page or a sub-page.
I did not notice the problem because my Buttongrid elements have at least one parameter when testing (even if some have no item parameter).

**Comment by lolodomo** [comment] 2024-05-21 18:54
> In fact, the problem is when there is no parameter set for the Buttongrid element. Adding any parameter (item or label or labelcolor or iconcolor ...) solves the issue. It does not depend if the Buttongrid element is on the main page or a sub-page.
> I did not notice the problem because my Buttongrid elements have at least one parameter when testing (even if some have no item parameter).

Bug is fixed by #4240

**Comment by lolodomo** [comment] 2024-05-22 07:16
> > ```
> > 2. Is there a plan to make the `Button` widget to "default" to the item specified in its parent`Buttongrid` when one is not specified? In a way this would reduce the flexibility but at the same time also saves typing / duplication when we still want to control the same item but with the added flexibility of using the `Button` widgets (e.g. custom coloring)
> > ```
> 
> 
> I hesitated when implementing. I don't remember exactly but I probably give up because it could lead to have no item neither on Button nor on Buttongrid. But thinking of it, in this case, the UI could simply log a message and do nothing when clicking a button.
> I am ok to change that.

See #4241

**Comment by jimtng** [comment] 2024-05-22 12:55
> Wouldn't it be easier to just make the Button widget to set its item parameter to its parent's at creation time when one is not provided? Is it because the code is generated by xtext?

Although it's not quite "pure" in logic, we can sneak that code into here:
https://github.com/openhab/openhab-core/blob/873bb53cbc12bf7624499f66170bfc90a10c35d6/bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/validation/SitemapValidator.xtend#L123

**Comment by lolodomo** [comment] 2024-05-22 16:35
@jimtng : I am very probably give up the idea because I don't want to "patch" the model (I don't think we already did that in the past) and we absolutely need the item set at each Button level to have all the stuff working. Everything is based on attachment of a widget to an item.

**Comment by lolodomo** [comment] 2024-06-30 11:32
Documentation is now completed.
IMHO, this feature request can now be closed.

**Comment by lolodomo** [comment] 2024-07-14 19:10
@openhab/core-maintainers : is it possible to close this feature request as completed?

**Closed** 2024-07-14 20:27 UTC
Labels: enhancement, sitemap
