### ISSUE TITLE
Snapshot #1637 crashes on the way up.

### ISSUE THREAD

**Issue by olemr** [openhab/openhab-core#921] opened 2019-07-12 11:49 UTC
[openhab.log](https://github.com/openhab/openhab-core/files/3386291/openhab.log)

Cyclic restarts.
Had to revert back to M1

x64 Ubuntu Server system.

**Comment by wborn** [comment] 2019-07-22 08:31
This issue is a duplicate of #924, which is fixed by #928 which reverts #905.

**Closed by wborn** 2019-07-22 08:31 UTC
Labels: bug, duplicate
