### ISSUE TITLE
Unclear error message on parsing sitemap file

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-core#3003] opened 2022-06-16 10:19 UTC
I move a `.sitemap` file to `/etc/openhab/sitemaps`.  OpenHAB logs:
```
2022-06-16 13:17:33.931 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'abc.sitemap'
2022-06-16 13:17:34.081 [ERROR] [ab.core.service.AbstractWatchService] - Error handling update of file '/etc/openhab/sitemaps/abc.sitemap': begin 0, end 2, length 1.
java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 1
        at java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[?:?]
        at java.lang.String.substring(String.java:1874) ~[?:?]
        at org.openhab.core.ui.internal.items.ItemUIRegistryImpl.getWidget(ItemUIRegistryImpl.java:670) ~[?:?]
        at org.openhab.core.io.rest.sitemap.SitemapSubscriptionService.collectWidgets(SitemapSubscriptionService.java:270) ~[?:?]
        at org.openhab.core.io.rest.sitemap.SitemapSubscriptionService.modelChanged(SitemapSubscriptionService.java:321) ~[?:?]
        at org.openhab.core.model.sitemap.internal.SitemapProviderImpl.modelChanged(SitemapProviderImpl.java:106) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:301) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:139) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:249) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:312) ~[?:?]
        at org.openhab.core.service.WatchQueueReader.lambda$3(WatchQueueReader.java:323) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

It is unclear, where the error in the sitemap file is.

**Comment by dilyanpalauzov** [comment] 2022-06-16 10:23
This is solved the problem the following way: I rename the sitemap file from `abc.sitemap` to `ab.sitemap` and on the first line of the file change `abc` with `ab`.  It does help, as the new file loads without problems. 

When I introduce an error in the sitemap file, OpenHAB logically refuses to load the file.  I guess, when I remove the error, OpenHAB continues however to refuse loading the file.

**Comment by J-N-K** [comment] 2022-06-16 13:07
Works fine for me:

```
15:05:56.754 | INFO  | OH-file-processing-1 | el.core.internal.ModelRepositoryImpl | 186 | Loading model 'default.sitemap'
15:05:56.837 | WARN  | OH-file-processing-1 | el.core.internal.ModelRepositoryImpl | 186 | Configuration model 'default.sitemap' has errors, therefore ignoring it: [3,24]: no viable alternative at input 'period1h'

15:06:06.724 | INFO  | OH-file-processing-3 | el.core.internal.ModelRepositoryImpl | 186 | Loading model 'default.sitemap'
```

Can you share both the sitemap with errors and the fixed one that is not loaded?

**Comment by dilyanpalauzov** [comment] 2022-06-16 13:29
I create
```
cat /etc/openhab/sitemaps/abc.sitemap 
sitemap abc label="X2" {
        Switch item=rm label="ABC"
}
```
The problem is not the sitemap file itself, as it is correct.  The problem is, that a sitemap with the same name existed in the past, openHAB remembered something and whenever I recreate abc.sitemap with any content, the above erros are printed.

The fix is to use just a different filename/sitemap name.

**Comment by J-N-K** [comment] 2022-06-16 15:42
First step, create a new broken sitemap. A `}` is missing and the filename does not match the sitemap name

```
sitemap xyz label="Hauptmenue" {
	Frame label="X" {
		Chart item=CO2Gehalt period=1h yAxisDecimalPattern="##0.#E00"
	
}
```

Second step, the missing `}` is added:

```
sitemap xyz label="Hauptmenue" {
	Frame label="X" {
		Chart item=CO2Gehalt period=1h yAxisDecimalPattern="##0.#E00"
	
        }
}
```

Third step, the wrong sitemap name is corrected:

```
sitemap abc label="Hauptmenue" {
	Frame label="X" {
		Chart item=CO2Gehalt period=1h yAxisDecimalPattern="##0.#E00"
	}
}
```

log:

```
17:37:24.432 | INFO  | openHAB Dir Watcher  | el.core.internal.ModelRepositoryImpl | 186 | Loading model 'abc.sitemap'
17:37:24.445 | WARN  | openHAB Dir Watcher  | el.core.internal.ModelRepositoryImpl | 186 | Configuration model 'abc.sitemap' has errors, therefore ignoring it: [5,1]: mismatched input '<EOF>' expecting '}'
17:39:25.438 | INFO  | OH-file-processing-6 | el.core.internal.ModelRepositoryImpl | 186 | Loading model 'abc.sitemap'
17:39:45.429 | INFO  | OH-file-processing-6 | el.core.internal.ModelRepositoryImpl | 186 | Loading model 'abc.sitemap'
```

Looks like it works with a recent milestone. I'll close this issue here. If you can provide steps to reproduce the "can't load sitemap after fixing error", please open a new issue.

**Closed by J-N-K** 2022-06-16 15:42 UTC
Labels: awaiting feedback
