### ISSUE TITLE
Google Assistant reacts on all Tags, not only on Metatags

### ISSUE THREAD

**Issue by Tobster77** [openhab/openhab-core#2015] opened 2020-12-27 15:01 UTC
I took a OH3 final release candidate installation and added my Tradfri bridge. Then I added some lights as equipment in my model and found the following unexpected behaviour:

Google Assistant seems to react upon the tags of a point, not only the metatags! When you have a non-semantic tag such as “Lighting” that is added automatically by some bindings such as Tradfri, Google Assistant will detect it and automatically add the point.

I expect that this would only happen with the dedicated metatags for Google Assistant, but whether I am not getting it, or the tag system is buggy at that point. 

The issue can be resolved by manually removing the "lighting" non-semantic tag.

I opened a discussion here https://community.openhab.org/t/oh3-mainui-how-to-register-and-exclude-items-for-google-assistant-and-amazon-alexa/111107/7 in case it's my fault...

**Comment by seimenb** [comment] 2020-12-27 19:09
I can confirm the same issue.
With OH3 I have done some improvements to the items definition, due to the semantic modeling. 
And as a result the GA now can recognize my lock even though the lock does not provide any ``ga=`` tag!
I believe it is because of the semantic ``["Lock"]`` tag.
It doesn't feel right if GA can auto-detect locks in the OH configuration without intending it.

``Switch AL_Entre_Treppenhaus_Tueroeffner "Türöffner Entre" <mylock> (gAL_Entre_Treppenhaus, gAL_Zugang) ["Lock"] ``

![image](https://user-images.githubusercontent.com/48569432/103177844-58edf100-487e-11eb-9e9f-0679ac06a0da.png)

**Comment by seimenb** [comment] 2020-12-27 19:22
@Tobster77 Maybe we should state the problem here? 
[https://github.com/openhab/openhab-google-assistant/issues](https://github.com/openhab/openhab-google-assistant/issues)

**Comment by michikrug** [comment] 2020-12-28 23:13
Yes, please move the issue to the mentioned repo.

Tags were kept for backward compatibility to the former version of the GA integration.
Unfortunately, this was not well documented so far. This is why I added two sentences in my PR: https://github.com/michikrug/openhab-google-assistant/blob/refactoring/README.md#L267

From my perspective, I would completely remove the support for tags in the GA integration and only rely on metadata.

But this discussion should be continued in the respective repo.

**Comment by kaikreuzer** [comment] 2020-12-29 08:19
> Yes, please move the issue to the mentioned repo.

Unfortunately, I can't for some reason. Please close this issue and simply copy the text over to a new issue at https://github.com/openhab/openhab-google-assistant/issues. Thanks!

**Comment by Tobster77** [comment] 2021-01-01 12:30
Thanks, guys! I created a new bug report [here ](https://github.com/openhab/openhab-google-assistant/issues/183)

**Closed** 2021-01-01 12:30 UTC
Labels: external bug
