### ISSUE TITLE
Two restarts needed after clearing cache

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-core#1205] opened 2019-11-11 22:09 UTC
After an OH upgrade or clearing the cache, there are many errors that come up in the log [I will include a log entry the next time I clear the cache]. After restarting again, the errors do not occur. I believe this has been occurring since S1566 (ESH reintegration). #865 has some details on one of the issues this causes.

IMO, this is something that should be resolved before the 2.5 release and go into the [milestone issue tracking](https://github.com/orgs/openhab/projects/2).

I think this is occurring for me due to having jar files in the addons directory.
```
2019-11-28 10:04:02.270 [INFO ] [javassist] - FrameworkEvent INFO - javassist
java.io.IOException: Exception in opening zip file: /mnt/data/openhab/openhab2-1749/userdata/cache/org.eclipse.osgi/27/0/bundleFile
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:321) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.basicOpen(ZipBundleFile.java:93) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getZipFile(ZipBundleFile.java:106) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.checkedOpen(ZipBundleFile.java:65) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getEntry(ZipBundleFile.java:240) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:560) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:538) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:525) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:446) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
	at org.jvnet.hk2.internal.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:77) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:348) ~[?:?]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:577) ~[?:?]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557) ~[?:?]
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230) ~[?:?]
	at java.lang.reflect.WeakCache.get(WeakCache.java:127) ~[?:?]
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419) ~[?:?]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719) ~[?:?]
	at org.jvnet.hk2.internal.ProxyUtilities$3.run(ProxyUtilities.java:134) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.jvnet.hk2.internal.ProxyUtilities.secureCreate(ProxyUtilities.java:129) ~[?:?]
	at org.jvnet.hk2.internal.ProxyUtilities.generateProxy(ProxyUtilities.java:208) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:1994) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88) ~[?:?]
	at org.glassfish.jersey.internal.inject.ContextInjectionResolver.resolve(ContextInjectionResolver.java:126) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:945) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:979) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:969) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:617) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[?:?]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347) ~[?:?]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:681) ~[?:?]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.run(ServletContainerBridge.java:54) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:?]
Caused by: java.io.FileNotFoundException: /mnt/data/openhab/openhab2-1749/userdata/cache/org.eclipse.osgi/27/0/bundleFile (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:169) ~[?:?]
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:304) ~[?:?]
	... 52 more
2019-11-28 10:04:02.495 [INFO ] [javassist] - FrameworkEvent INFO - javassist
java.io.IOException: Exception in opening zip file: /mnt/data/openhab/openhab2-1749/userdata/cache/org.eclipse.osgi/27/0/bundleFile
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:321) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.basicOpen(ZipBundleFile.java:93) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getZipFile(ZipBundleFile.java:106) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.checkedOpen(ZipBundleFile.java:65) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getEntry(ZipBundleFile.java:240) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:560) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:538) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:525) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:446) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
	at org.jvnet.hk2.internal.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:77) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:348) ~[?:?]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:577) ~[?:?]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557) ~[?:?]
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230) ~[?:?]
	at java.lang.reflect.WeakCache.get(WeakCache.java:127) ~[?:?]
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419) ~[?:?]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719) ~[?:?]
	at org.jvnet.hk2.internal.ProxyUtilities$3.run(ProxyUtilities.java:134) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.jvnet.hk2.internal.ProxyUtilities.secureCreate(ProxyUtilities.java:129) ~[?:?]
	at org.jvnet.hk2.internal.ProxyUtilities.generateProxy(ProxyUtilities.java:208) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:1994) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88) ~[?:?]
	at org.glassfish.jersey.internal.inject.ContextInjectionResolver.resolve(ContextInjectionResolver.java:126) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:945) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:979) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:969) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:617) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[?:?]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347) ~[?:?]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:681) ~[?:?]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.run(ServletContainerBridge.java:54) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:?]
Caused by: java.io.FileNotFoundException: /mnt/data/openhab/openhab2-1749/userdata/cache/org.eclipse.osgi/27/0/bundleFile (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:169) ~[?:?]
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:304) ~[?:?]
	... 52 more
```

These exceptions also occur on OH shutdown...
```
2019-11-28 10:05:59.388 [INFO ] [org.eclipse.jetty.server.handler.ContextHandler] - Stopped HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.core.ui_2.5.0.201911090306 [189], contextID=default]}
2019-11-28 10:05:59.390 [INFO ] [org.eclipse.jetty.server.handler.ContextHandler] - Stopped HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.core.ui_2.5.0.201911090306 [189], contextID=custom]}
2019-11-28 10:05:59.433 [INFO ] [org.quartz.core.QuartzScheduler] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED shutting down.
2019-11-28 10:05:59.433 [INFO ] [org.quartz.core.QuartzScheduler] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED paused.
2019-11-28 10:05:59.434 [INFO ] [org.quartz.core.QuartzScheduler] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED shutdown complete.
2019-11-28 10:05:59.472 [INFO ] [org.apache.karaf.shell.impl.action.osgi.CommandExtension] - Unregistering commands for bundle org.openhab.core.karaf/2.5.0.201911090307
2019-11-28 10:05:59.629 [INFO ] [javassist] - FrameworkEvent INFO - javassist
java.io.IOException: Exception in opening zip file: /mnt/data/openhab/openhab2-1749/userdata/cache/org.eclipse.osgi/27/0/bundleFile
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:321) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.basicOpen(ZipBundleFile.java:93) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getZipFile(ZipBundleFile.java:106) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.checkedOpen(ZipBundleFile.java:65) ~[?:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getEntry(ZipBundleFile.java:240) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:560) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:538) ~[?:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:525) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:446) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
	at org.jvnet.hk2.internal.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:77) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:348) ~[?:?]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:577) ~[?:?]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557) ~[?:?]
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230) ~[?:?]
	at java.lang.reflect.WeakCache.get(WeakCache.java:127) ~[?:?]
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419) ~[?:?]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719) ~[?:?]
	at org.jvnet.hk2.internal.ProxyUtilities$3.run(ProxyUtilities.java:134) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.jvnet.hk2.internal.ProxyUtilities.secureCreate(ProxyUtilities.java:129) ~[?:?]
	at org.jvnet.hk2.internal.ProxyUtilities.generateProxy(ProxyUtilities.java:208) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:1994) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88) ~[?:?]
	at org.glassfish.jersey.internal.inject.ContextInjectionResolver.resolve(ContextInjectionResolver.java:126) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:945) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:979) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:969) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:617) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[?:?]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347) ~[?:?]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:681) ~[?:?]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.run(ServletContainerBridge.java:54) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:?]
Caused by: java.io.FileNotFoundException: /mnt/data/openhab/openhab2-1749/userdata/cache/org.eclipse.osgi/27/0/bundleFile (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:169) ~[?:?]
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:304) ~[?:?]
	... 52 more
2019-11-28 10:06:03.497 [INFO ] [org.ops4j.pax.web.service.internal.HttpServiceFactoryImpl] - Unbinding bundle: [org.openhab.core.io.http_2.5.0.201911090304 [148]]
2019-11-28 10:06:03.527 [INFO ] [org.ops4j.pax.web.service.internal.HttpServiceFactoryImpl] - Unbinding bundle: [org.openhab.core.audio_2.5.0.201911090304 [135]]
2019-11-28 10:06:03.528 [INFO ] [org.eclipse.jetty.server.handler.ContextHandler] - Stopped HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.core.audio_2.5.0.201911090304 [135], contextID=default]}
2019-11-28 10:06:03.545 [INFO ] [org.apache.karaf.shell.impl.action.osgi.CommandExtension] - Unregistering commands for bundle org.apache.karaf.event/4.2.6
2019-11-28 10:06:03.549 [INFO ] [org.ops4j.pax.web.service.internal.HttpServiceFactoryImpl] - Unbinding bundle: [com.eclipsesource.jaxrs.publisher_5.3.1.201602281253 [20]]
2019-11-28 10:06:03.550 [INFO ] [org.ops4j.pax.web.service.jetty.internal.HttpServiceContext] - ServletContext service already removed
```
This is not a complete list of the errors.

**Comment by wborn** [comment] 2019-11-30 09:56
This seems like a duplicate of https://github.com/openhab/openhab-distro/issues/974. OHC doesn't have anything to do with bundle caching. Bundle caching is a feature provided by the OSGi framework (Equinox/Felix) used in the distribution using OHC.

We track these issues for openHAB in openhab-distro because that repo has files that determine what OSGi framework and Karaf version is used for the openHAB distribution. So this might not even be an issue for a 3rd party that has a distribution using OHC with Felix instead of Equinox.

**Closed by wborn** 2019-11-30 09:56 UTC

**Comment by openhab-5iver** [comment] 2019-11-30 10:42
Thank you, @wborn! I completely forgot about that other issue, but you are correct that this particular error is a dup. I've been doing some development work and these kept popping up in my test environment, so I copied them here. I have not needed to restart my production environment for a while, so I have not gathered the list of errors. 

This issue has been reported a few times in the forum and in other GH issues, but I had not seen an issue opened specifically for it. Every time I clear the cache on my production setup, I have to restart twice to get things running properly.
