### ISSUE TITLE
USB locking issues

### ISSUE THREAD

**Issue by BasvanH** [openhab/openhab-core#383] opened 2018-08-14 19:51 UTC
Hello,

I noticed my Zwave en Zigbee USB nodes are sometimes down. After going to Karaf, I notice these error messages. They repeat every 10 to 20 seconds.

```
RXTX fhs_lock() Error: opening lock file: /var/lock/LCK…ttyUSB0: File exists. It is mine

0 k testRead() Lock file failed
RXTX fhs_lock() Error: opening lock file: /var/lock/LCK…ttyACM0: File exists. It is mine

0 k testRead() Lock file failed
```

My environment:
- Synology NAS with Docker.
- Running debian build 1322, upgraded to 1330 same errors.
- USB interfaces in /dev are set to 777. 

Things tried to solve issue:
- Upgraded to 1330
- Reboot NAS
- Reboot Openhab
- Searched for simular cases, but all are old and irrelevant.
- Have one person op community who has same errors: https://community.openhab.org/t/rxtx-fhs-lock-error-opening-lock-file-var-lock-lck-ttyusb0-file-exists-it-is-mine/49117

What could be the cause of this issue?

Regards,
Bastiaan

**Comment by kaikreuzer** [comment] 2018-08-16 13:03
Sounds pretty much like a duplicate of https://github.com/openhab/openhab2-addons/issues/671, so I would suggest to move all discussions there.

**Closed by kaikreuzer** 2018-08-16 13:03 UTC

**Comment by 3-8UUID** [comment] 2023-05-24 03:02
> 

why this https://github.com/openhab/openhab2-addons/issues/671 link is 404
