### ISSUE TITLE
orphaned links after deleting item

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#1454] opened 2020-05-03 05:11 UTC
When deleting an item through the rest api and the item has links those links do not get deleted automatically. They remain orphaned and still point to the deleted item.
When an item is deleted, all links that point to the item should be deleted, too.

[HABApp Issue](https://github.com/spacemanspiff2007/HABApp/issues/150)

**Comment by J-N-K** [comment] 2020-05-03 07:03
This should not be done automatically. A typo would lead to the removal of links, which is at least unexpected if you correct that one later.

**Comment by cdjackson** [comment] 2020-05-03 08:10
It has been [discussed in the past within ESH](https://github.com/eclipse/smarthome/issues/1018) and agreed that for managed items, they should be removed automatically. 

@J-N-K are you manually configuring your system through files? If so, then you are right that they shouldn't be removed, but if everything is done through the UI then this should be automatic - right?

**Comment by J-N-K** [comment] 2020-05-03 08:15
@cdjackson indeed, the problem is larger for unmanaged items (I have all things managed, all items unmanaged).

I still think that a button „compress“ in the UI would be sufficient. Especially if there is no „undo“ for restoring deleted items and their links.

What happens in case of a re-name? Are the links updated automatically or removed?

**Comment by cdjackson** [comment] 2020-05-03 08:25
I would say that the system should rename the links if you rename the item. My personal feeling is that users shouldn’t need to know the inner workings of links etc, so shouldn’t have to worry about compressing them or maintaining their system. I know for you this is fine, but for “mere mortals” (ie the majority of users) this would be unexpected I think.

Also, I would argue (with the expectation of being shot down here :) ) that you shouldn’t rename UIDs. IMHO the UIDs should be maintained over life as they propagate through the system and it becomes messy if you change things (eg persistence is now out of step). I know of course that this will not be how people use their system, but I do think that there should be a unique reference applied throughout the life of “stuff” (be it items, things etc) - but that’s a larger topic to tackle and probably not one to get in to here :)

**Comment by spacemanspiff2007** [comment] 2020-05-03 09:10
Imho rename is equal to delete item and add new item.
So the links of the item have to be created again once the item has been added.

I see no benefit in keeping the orphaned links around.

**Comment by spacemanspiff2007** [comment] 2020-05-03 09:29
> Also, I would argue (with the expectation of being shot down here :) ) that you shouldn’t rename UIDs. IMHO the UIDs should be maintained over life as they propagate through the system and it becomes messy if you change things (eg persistence is now out of step). I know of course that this will not be how people use their system, but I do think that there should be a unique reference applied throughout the life of “stuff” (be it items, things etc) - but that’s a larger topic to tackle and probably not one to get in to here :)

I stumbled upon this a couple of times. This could be fixed be always assigning unique uids to everything. The name is then more an alias which is used to conveniently look up things.
It's definitely possible but requires a new approach how things are configured and is out of scope here.

**Comment by cdjackson** [comment] 2020-05-03 09:40
> I stumbled upon this a couple of times. This could be fixed be always assigning unique uids to everything. The name is then more an alias which is used to conveniently look up things.

Agreed - this is fundamentally what I'm getting at, but I can't imagine that is a direction that the OH maintainers will want to go as it's a significant change to the concept. I would argue that this is how it's meant to be now (a UID should, IMHO, be unique for life) but I'm pretty sure that's not how it is generally used.

**Comment by J-N-K** [comment] 2022-05-13 22:44
After thinking about it, isn't this an UI issue? When removing links from channels, the UI asks if the item should also be removed. Shouldn't it be the same when removing the item: the UI asks if links should also be removed?

**Comment by spacemanspiff2007** [comment] 2022-05-14 03:46
Could you elaborate the use case for keeping the links that point to a non existing item?
Imho this is dangerous as it leads to hard to track down errors:


> I delete the item, then a couple of days later I add it again and out of nowhere it is linked.
> This doesn't make sense at all.

**Comment by J-N-K** [comment] 2022-05-14 08:52
It sounds a bit inconsistent to remove them implicitly. Imagine we have two items: `ItemA` and `ItemB`. `ItemA` is managed, `ItemB` and `ItemC` are not managed. All are linked to channel `Binding1:ThingType1:Thing1:Channel1`.

```test.items
String ItemA { channel="Binding1:ThingType1:Thing1:Channel1" }
String ItemB
```

The links for `ItemB` and `ItemC` are created in the UI.

Now I remove `ItemC`. Following your proposal, the link would be removed automatically, if I re-create `ItemC` a week later, there will be no links. This is fine.

Now I rename the items file, which is effectively removing the model and re-creating it. If the link from `ItemB` was removed automatically on item removal (which would be consistent, because it is a managed link), it would be missing and needs to be re-created. I didn't check if we'll run into issues on shutdown, when the `GenericItemProvider` is removed, but this could probably be solved. Another issue - like mentioned above - is a typo when editing: while editing, you type `Item_B`, the file is saved automatically (which a lot of editors do), you correct the typo, but because `ItemB` was not present in the model for a short time, the link has been deleted. 

If we omit automatic removal of links for unmanaged items, deleting `ItemB` intentionally and re-creating it a week later, it would be linked. This is inconsistent with the behavior of `ItemC`.

The way we have it now is more consistent: links are removed if explicitly requested. In the case of `ItemA` this is done by removing the .items model where the link was defined, managed links must be removed the way they were created - via UI.

**Comment by spacemanspiff2007** [comment] 2022-05-14 13:41
> The links for `ItemB` and `ItemC` are created in the UI.

I am surprised it's possible to successfully create the link for `ItemB` in the GUI. That's a major inconsistency and should be removed.
File based should be file based and UI based should be UI based.

Let's assume we fix this inconsistency.
What is the use case of keeping a link around that has no destination?

If I delete an item from the GUI I still get an orphaned link even though in the GUI there is the possibility to modify an item.
Metadata get's deleted when the item is removed, too so I think the behavior is inconsistent.


---

> Edit: That said, I'm still thinking that unmanaged items/things (and probably other configuration) should be removed completely.

Depends who you ask. I'm a huge fan of it so please don't :wink: .

**Comment by J-N-K** [comment] 2022-05-14 14:07
No, it's not an inconsistency. I didn't check if you can add the link for an unmanaged thing, but I believe (in fact that's what I did for years) having items unmanaged and things managed is quite common. So it depends on the view if adding the links should be done from the thing-side (managed) or from the item-side (unmanaged). 

Requiring using unmanaged links (i.e. in the .items model) would shift the problem to the other side: if you remove the thing, the link stays, because it is configured in the file and can't be removed and a thing with the same UID will be automatically linked. If that is fine, what is the difference to creating a new item with the same name? In fact I believe that re-creation of a thing with the same name is quite common e.g. if discovery is used.

**Comment by spacemanspiff2007** [comment] 2022-05-15 04:19
> So it depends on the view if adding the links should be done from the thing-side (managed) or from the item-side (unmanaged).

Precisely! I think we have to establish if a link should be a property of a `Thing`, a property of an `Item` or something free floating. I am not talking about the implementation but where it should belong logically wise.
If that is properly defined then the desired behavior is clear.

I am always thinking of a link as more of an item property because I link an item to a thing.
For me this made the most sense because the link causes the item to change its state.
The state and the thing that makes the state change are tighter connected than the source of the state changing event.

---

> We could provide REST support for that (e.g. an endpoint `DELETE /links/{itemName}` that deletes all links for an item

I don't think that's necessary. It's just a loop over `links?itemName=itemName`

> or a parameter to `DELETE /items/{itemName}` that links should be removed, too).

That's a great idea! It would already simplify things on the `HABApp` side.

**Comment by spacemanspiff2007** [comment] 2022-05-16 16:47
> Profiles are a property on the Link.

Could you provide an example? I've never seen them or the usage of it.

> You can have one channel linked to more than one Item and you can have one Item linked to more than one different Channels which also, to me, implies that links are their own thing and not a property on Items or Things

But that's just the type of relation and works for every logical assignment.

---

Let's take a step back: Why do you create a link? 

The link is created so 
- the item can change it's state. 
  Here it's clear that the link is logically assigned to the item because the sole purpose of the link is that the item can do something.
- the item state can be sent e.g. to a device.
   Again the link is logically assigned to the item (state) because the purpose of the link is that the item can do something.
  One could argue that the link is logically assigned to the device but since a device can represent multiple item states the state of the item binds stronger than the states of the item.

Can you think of other use cases?

**Comment by J-N-K** [comment] 2022-05-16 17:48
@rkoshak, thanks for that. It pretty much is the same what I think: You create items, you create things (and possibly channels) and you create links between them. Similar to items and things, links are not created automatically, they are created by user-choice. And because of that they should not be deleted automatically. 

We should make deleting them easier (as I said the UI should give the choice "delete a thing only", "delete a thing and all associated links", "delete an item" and "delete an item with all associated links"). We should provide REST endpoints that make it easy to do so. This is also consistent with the file-based behavior: you have to remove links manually. 

And probably it would be a good idea (also keeping in mind the mislead metadata discussion we had in #1447) to add some house-keeping functionality, that allows to remove orphaned links or metadata (similar to what e.g. many mail clients provide as "compress folder" to remove deleted mails from a folder).

**Comment by spacemanspiff2007** [comment] 2022-05-17 06:58
> so I'll just do a full dump.

Thank you very much for the detailed explanation. Though a short link and an e.g. the `follow` profile would have be enough - I don't want to take too much from your time 😄 .
I was thinking of something else when you mentioned profiles - of course I know them 😕 .

They are like transformations for the event that gets forwarded by the link and thus belong to the link.
For this discussion however they change nothing. 

> But they are here to stay and because they exist, they really make the most sense when the Link is considered to be it's own thing instead of a part of either the Item or the Thing Channel.

To clarify - I am not doubting that the link should be an own object. My suggestion is that the link should be a child of an item relationship wise. 

> You can use those exact same arguments from the Thing side. You create a link so:
>    * a thing's channel can publish the devices state.
>    * a thing can receive a command from an Item.

But in rules you can directly trigger directly on channel events (at least I've done that ages ago) and with actions you can send commands to a thing without a link. 
Additionally even without any links at all a thing can be used to manage and change settings of the physical device.
So a thing is still useful without a link but an item without a link is useless (in this context).

> Links have their own independent:
>    * storage and registry
>    * configuration
>    * REST API endpoint
>    * visual representation in MainUI

The first three are an implementation detail. I'm not that firm in the new GUI but (please correct me if I am wrong) the only place you explicitly see the links is under item -> Channel Links. Under the thing view you see the thing channels and only then the channel links. The emphasis with the thing seems to be on the channels and with the item on the links.

> This is also consistent with the file-based behavior: you have to remove links manually.

You are talking about a mixture of file based and GUI configuration.
For real file based configuration you define the link explicitly on the item side and it gets deleted when you remove the item.
```
Color Bedroom_Light { channel="hue:0210:1:bulb1:color" }
```

---

I'm a fan of well defined relations because they make things easier since they introduce a well defined life cycle. Even if it's a many to many relations almost always one part of the relation binds stronger and should/can be used to define the life cycle.
Free floating is always very hard and a source for confusion. 

If there are no major drawbacks I still think it's worth to relate things closer to the item because it'll make things easier in the long run. However since I'm not writing the code here that's just make-a-wish.

None the less we all agreed that it should be possible to remove the links on item deletion and that's something. 👍

**Comment by rkoshak** [comment] 2022-05-17 17:03
> But in rules you can directly trigger directly on channel events (at least I've done that ages ago) and with actions you can send commands to a thing without a link.

In both of those cases those are a special type of Channel that cannot be used in a Link. And you can do the same with an Item without a link. Not all Items require a link nor do Items require a link to be useful. I fail to see any argument for making it a child of an Item that doesn't also equally apply to the Thing/Channel perspective. 

> So a thing is still useful without a link but an item without a link is useless (in this context).

Roughly 10% of all my Items have no link. I don't find them to be useless at all. I find them to be exceptionally useful. Maybe that's the root of the disagreement. The only difference between an Item that has a link and one that doesn't is where the updates/commands come from and go to (perhaps nowhere in some cases but nowhere is somewhere too). Such Items can trigger rules, show a status on the UI, be used in rules to make decisions, etc. just like Items with a link.

As for dismissing the implementation of links, implementation matters. They way it's implemented, internally, is the whole reason why orphaned links are possible. 

> I'm not that firm in the new GUI but (please correct me if I am wrong) the only place you explicitly see the links is under item -> Channel Links. Under the thing view you see the thing channels and only then the channel links. The emphasis with the thing seems to be on the channels and with the item on the links.

From the Item you see:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/6385096/168862645-90b90cd5-84ac-4390-b8a0-f538ef28e30f.png">

Clicking on that you see the screen shot from above of the Link's setting page.

From the Thing's Channel tab you see

<img width="748" alt="image" src="https://user-images.githubusercontent.com/6385096/168862938-ddd2bae7-8c8f-4661-b87d-7e86b9d60701.png">

The blue circle shaped badge shows the count of links to that channel. Opening up the Channel you see the individual links and can access other Channel configuration options.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/6385096/168863177-b0b6cc90-bef2-4eb8-9cbb-22f81fefaaed.png">

Again, clicking on that link will take you to the Link's setting page. From the Link's setting page you can navigate to either the Item or the Channel by clicking on those.

From either the Item or the Channel you can see *that* there is a link. From either the Item or the Channel you can create a Link. But you cannot navigate from the Item to the Channel or vise versa without first going through the Link's page. 

It's probably a mistake to talk about the Link as being associated with a Thing at all. It's really only associated with Channels. 

> The emphasis with the thing seems to be on the channels and with the item on the links.

I wouldn't say that. The Link is to/from the Channel so obviously it needs to be shown with the Channel. How it's shown on the Channels is a choice based on usability, not emphasis. Have you seen how many Channels some of these Things can have? If the Channel Config and Links are not collapsed the Channel tab becomes very hard to use to find the Channel you want.

**Comment by spacemanspiff2007** [comment] 2022-05-18 03:53
> Roughly 10% of all my Items have no link. I don't find them to be useless at all. I find them to be exceptionally useful. Maybe that's the root of the disagreement. The only difference between an Item that has a link and one that doesn't is where the updates/commands come from and go to (perhaps nowhere in some cases but nowhere is somewhere too). Such Items can trigger rules, show a status on the UI, be used in rules to make decisions, etc. just like Items with a link.

I'm aware that one has items without a link and why they are used. That's why I added a ``(in this context)``. I am talking about interaction with external devices since this is the only reason to have links on an item. 
In terms of interaction with a device an item without a link is useless. A thing however is still useful as it can be used to e.g. manage the device. Additionally the thing can still be used to execute actions e.g. from a rule.
That's a strong indicator that the lifecycle of the link should be connected to the item.

> As for dismissing the implementation of links, implementation matters. They way it's implemented, internally, is the whole reason why orphaned links are possible.

To understand why something is currently happening the implementation matters (of course).
But I am suggesting how things should behave and for target behavior the current implementation is not relevant.

I am yet to see the drawbacks of logically adding the links to an item. 
Everything will work as before but some inconsistencies in behavior will be gone.

**Comment by rkoshak** [comment] 2022-05-18 13:52
> In terms of interaction with a device an item without a link is useless.

Unless that Item tiggers a rule that sends command to other Items, calls executeCommandLine, makes an HTTP call, saves a value to Persistence, etc. An Item doesn't need a link to be useful nor does it need a link to cause some sort of interaction with external devices.

And even if that were not the case, I'm not sure how that or the fact that Things provide Channels that can't be linked to Items is relevant to whether a Link is a subproperty on an Item or its own entity. In both Items and Things, there are situations where it makes sense to use either without a Link. Narrowing the definition of a "useful Item in this context"  is begging the question. If we are going to consider Things in all their uses, we should consider Items in all their uses too and when doing so, neither the Item nor the Thing has a greater claim on the link.

> Everything will work as before but some inconsistencies in behavior will be gone.

But as discussed above, some new inconsistencies in behavior will be introduced. And in the normal course of the average user using openHAB, those new inconsistencies will be more likely to be encountered than is the case now.

**Comment by spacemanspiff2007** [comment] 2022-05-19 04:05
Let's try from another angle

---

Openhab has the option to specially define items in files. It's a great tool that allows stateless configuration of openhab.

If I have the following entry and load it into openhab I can always be sure (if the file is successfully loaded) that there will be an item with the name ``SunRise``.
```
DateTime    SunRise    {channel="astro:sun:home:rise#start"}
```
If I ask you to what kind of channels the item is linked you have to answer "I don't know - at least one link to the astro binding".
And that's the inconsistency and issue.

In the `*.items` file you define explicitly what kind of links the item should have and it's the complete configuration of what should be added. It's stateless meaning that the internals of openhab should exactly reflect the contents from the `*.items` file.
If it wouldn't be stateless it would later be possible e.g. to change the label, groups, icon, etc..

> We'd replace the problem of the occasional orphaned link with making it impossible to use managed Links with unmanaged Items.

Yes - that should have never been possible in the first place and should be the long time goal. 
The `*.items` file syntax clearly states that the link configuration should be in the file.

Imho this would also be easily possible with a soft migration:
Issue a warning in the logs on startup that they have to be added to to the `*.items` file and one version later make it an error.

**Comment by J-N-K** [comment] 2022-05-19 04:13
The reason they are defined in files at all is that they had to be retrofitted to the old OH1 way of configuring links between bindings and items. This is not a design-decision that can be used to say „they belong here“. In contrast, the `ItemChannelLinkRegistry` is located in the `org.openhab.core.thing` bundle, which brings them closer to things than items.

As I said earlier: in my opinion the files should be removed as they cause more issues than we gain from them. Therefore I would veto a change that moves configuration from the UI to files. This will clearly not happen.

**Comment by spacemanspiff2007** [comment] 2022-05-19 05:50
> Therefore I would veto a change that moves configuration from the UI to files. This will clearly not happen.

Just to clarify so we have the same understanding (you're response reads ambiguous):
I'm saying if an item is defined in the file the corresponding way to define a link should be in the file, too.
I am not saying all link configurations should be done in files.

**Comment by J-N-K** [comment] 2022-05-19 15:51
IMO this is a step backward.

**Comment by rkoshak** [comment] 2022-05-19 16:13
Given that OH has supported managed Links for unmanaged Items since OH 2.0, any change along those lines would be a significant breaking change. I know for a fact there is a population of OH users who do this and making it so this cannot be done would break their configs.

**Closed** 2022-07-19 07:24 UTC
Labels: enhancement, PR pending
