### ISSUE TITLE
<item>.PostUpdate() and other APIs and Quantity() do not support Strings using scientific notation

### ISSUE THREAD

**Issue by MikeTheTux** [openhab/openhab-core#3917] opened 2023-12-11 19:44 UTC
I was sent over to ohc with my issue from [#16034](https://github.com/openhab/openhab-addons/issues/16034)

I've implemented a rule, where `<item>.history.deltaSince()` returns a very small BigDecimal `-1e-10` (almost `-0.0`).
In a next step I would like to update an Item of type `Number:Energy`.

When using the following syntax, it fails because the implicit `toString()` returns a string in scientific notation:
```
items.Inverter_Energy_Today.postUpdate(value + " Wh");
```

Example to reproduce, using a javascript `number` instead of the wrapped Java `BigDecimal` that `<item>.history.deltaSince()` returns:
```
const value = -1e-10;
items.Inverter_Energy_Today.postUpdate(value + " Wh");
```

```
[WARN ] [rnal.defaultscope.ScriptBusEventImpl] - State '-1e-10 Wh' cannot be parsed for item 'Inverter_Energy_Today'.
```

The following doesn't work as well:
```
const value = -1e-10;
const qnt = Quantity(value + " W*h");
items.Inverter_Energy_Today.postUpdate(qnt);
```

```
[ERROR] [hab.automation.script.file.energy.js] - Failed to execute rule Inverter_ToFromGrid_Power: QuantityError: Failed to create QuantityType from -1e-10 W*h: java.lang.IllegalArgumentException: Invalid Quantity value: -1e-10 W*h: QuantityError: Failed to create QuantityType from -1e-10 W*h: java.lang.IllegalArgumentException: Invalid Quantity value: -1e-10 W*h
	at o (@openhab-globals.js:2)
	at O (@openhab-globals.js:2)
	at c (@openhab-globals.js:2)
	at getQuantity (@openhab-globals.js:2)
	at execute (energy.js:590)
	at execute (@openhab-globals.js:2)
```

Workarounds for my use-case (number almost zero):

```
const value = -1e-10;
items.Inverter_Energy_Today.postUpdate(value.toFixed() + " Wh");
```

or 

```
const value = -1e-10;
const qnt = Quantity(value.toFixed() + " W*h");
items.Inverter_Energy_Today.postUpdate(qnt);
```

For java `BigDecimal` `.toPlainString()` can be used.

See [stackoverflow.com](https://stackoverflow.com/questions/1685680/how-to-avoid-scientific-notation-for-large-numbers-in-javascript) regarding the full complexity on JS and numbers in scientific notation.

The usage of the scientific notation is quite unpredictable and therefore error-prone.
Can the `Quantity` type as well as `<item>.postUpdate()` and other APIs support `strings` in scientific notation in order to be more robust?

## Your Environment
* openHAB 4.0.4
* JavaScript Scripting rules

**Comment by spacemanspiff2007** [comment] 2023-12-12 04:26
Related to #3883

**Comment by J-N-K** [comment] 2023-12-31 20:21
I can't reproduce that. I used exactly your setup (a `Number:Energy` item, the JS script from above) and the result with 4.2.0-SNAPSHOT: 

```
21:19:07.362 | INFO  | OH-eventexecutor-1-1 | openhab.event.ItemStateChangedEvent  | 178 | Item 'Inverter_Energy_Today' changed from NULL to -1.0E-13 kWh
```

I also wrote a unit test

```
    @Test
    public void testScientificNotation() {
        UnitProvider unitProvider = mock(UnitProvider.class);
        when(unitProvider.getUnit(any())).thenAnswer(i -> Units.WATT_HOUR);
        NumberItem numberItem = new NumberItem("Energy", "test", unitProvider);

        State state = TypeParser.parseState(numberItem.getAcceptedDataTypes(), "-1e-10 Wh");
        assertNotNull(state);
    }
```

and that did also pass. Can you try again with a recent snapshot?

**Comment by MikeTheTux** [comment] 2024-01-02 20:58
I'm now on OH4.1.0 and cannot reproduce the issue as well:
I did several tests, using quantity, number as well as string.

`State '-1e-10 Wh' cannot be parsed` warning never showed up again.

**Comment by J-N-K** [comment] 2024-01-02 21:16
I'll close the issue. If it ever occurs again, please file a new issue and tag me.

**Closed by J-N-K** 2024-01-02 21:16 UTC
Labels: bug, awaiting feedback
