### ISSUE TITLE
[persistence] Persistence groups only work when the group is defined within the same items file.

### ISSUE THREAD

**Issue by baku104788** [openhab/openhab-core#1437] opened 2020-04-20 13:19 UTC
Previously I had persistence groups that I used across multiple files. Example persist strategy below

```
Strategies {
default = everyChange, restoreOnStartup
}

Items {
persistChanges* : strategy = everyChange
persistAndRestore* : strategy = everyChange, restoreOnStartup
}
```
items1.items
```
Group persistAndRestore
Switch statusone (persistAndRestore)
```

items2.items
```
//will not be persisted as the group isn't defined in this items file.
Switch statustwo (persistAndRestore)
```

Before 2.4M3 this worked perfectly. Post 2.4M3 this stopped working and I couldn't figure out why until now. It turns out that you need to define the group at the top of each .items file where I have items within the group that need to be persisted.  Simply defining the group in one .items file and then using it on items across files does not work.  My guess is that this may impact other group based actions in the core when they span files. This can easily be reproduced on any newer version of OH

**Comment by cweitkamp** [comment] 2022-01-01 11:26
Is this still an issue for you? For me it is working flawlessly for years.

**Comment by baku104788** [comment] 2022-01-01 17:09
Honestly I couldn't tell you. with the new openhab 3 release I no longer use .items files.

**Comment by cweitkamp** [comment] 2022-01-01 17:24
Thanks for the feedback. I would suggest to close this issue for now.

Feel free to reopen it whenever you think the problem is still there.

**Closed by cweitkamp** 2022-01-01 17:24 UTC
Labels: persistence, awaiting feedback
