### ISSUE TITLE
Start rule execution *after* items are loaded

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#216] opened 2017-09-26 06:40 UTC
Please enforce to start executing rules only  *after* items are loaded.
At current, the order is more or less coincidential (bundles are loaded as defined per Karaf dependencies), but at least for me (using thing and items FILES), it's consistently loading rules first.

Now while to reorder makes sense from an abstract point of view (as the 'natural' order of dependencies is things - items - rules), there's also practical implications.
The problem to load rules early is that it has a major impact on startup performance, and it can even lead to a startup failing completely.
You might only get to see the latter on slow machines or in exceptionally large or complex setups, and/or when you use many files to define things and items instead of using PaperUI, but I have this problem.
See [this issue](https://github.com/openhab/openhab-distro/issues/531) for details also on startup times.

So as rules depend on items anyway, it would make sense to forcefully move the loading of rules to the end of the startup process (and in case you start work on it anyway, preferrably also enforce to load items after things).
The conclusion that it would be helpful and possible was a result of a discussion with David Graeff.
I'm unsure if it could be done through Karaf config alone, there's the feature files that can be used to declare dependencies, but David is the expert, he mentioned this needs to be applied in the OH core  and that this is sort of a hack, but he also mentioned that it was already done occasionally to solve other issues.

**Comment by mstormi** [comment] 2017-10-10 08:21
Just found [ESH #3771](https://github.com/eclipse/smarthome/issues/3771) which points to [ESH #1896](https://github.com/eclipse/smarthome/issues/1896).
Said to be worked on, but there was no progress for several months.

**Comment by kaikreuzer** [comment] 2018-02-07 10:38
Right, this needs to be fixed in ESH, so let's close this as a duplicate of eclipse/smarthome#1896.

**Closed by kaikreuzer** 2018-02-07 10:38 UTC
