### ISSUE TITLE
2.5.3 Negative numbers not supported in items configuration

### ISSUE THREAD

**Issue by yfre** [openhab/openhab-core#1501] opened 2020-05-25 12:43 UTC
OpenHAB 2.5.3
Homekit binding

i would like to make min & max temperature configurable for a thermostat item (homekit binding)
following line works

`Number 	temperature  {homekit="TemperatureSensor" [minValue=10, maxValue=27] }
`
but if i want to use negative numbers i get parsing error. 
this line

`Number 	temperature  {homekit="TemperatureSensor" [minValue=-10, maxValue=27] }
`

leads to this exception

`2020-05-25 14:03:13.852 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'test.items' has errors, therefore ignoring it: [8,106]: no viable alternative at input '-'`

is it known limitation? or is there a way to provide negative numbers

**Comment by openhab-5iver** [comment] 2020-05-25 15:45
Have you asked the maintainer(s) of the [homekit addon](https://github.com/openhab/openhab-addons/issues)? Neither of the [Homekit](https://www.openhab.org/addons/integrations/homekit/#item-configuration) nor [Alexa](https://www.openhab.org/docs/ecosystem/alexa/#temperaturesensor-temperature) documentation show anything about minValue/maxValue for TemperatureSensor.

> or is there a way to provide negative numbers

Without looking through the code, if this is actually functional, then I would try using strings instead of numbers, or maybe [range="-10:27"]. The definition of metadata in Items is not without issues though, so this could very well be a problem. Have you tried setting the metadata through the REST API or scripted automation?

**Comment by yfre** [comment] 2020-05-25 16:02
im working on the homekit addon. but the issue is unrelated to the addons - the exception happens at the moment of item configuration refresh, i.e. saving an *.items file. 

String would work but then it appears as a String type in the metadata.getConfiguration, which is wrong. Of course i could try to convert all strings to numbers as workaround, but maybe the bug can be easily fixed. 

it looks like the .items parser is based on eclipse EMF, so, there should be somewhere an grammar for parser and we just need to add "-" there.

**Comment by openhab-5iver** [comment] 2020-05-25 18:45
> im working on the homekit addon

Sorry for that... you are not the person listed in CODEOWNERS.

> so, there should be somewhere an grammar for parser and we just need to add "-" there.

I can set and read metadata values with negative numbers using Jython, so it does appear to be just an issue with the Item definition [at this line](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.item/src/org/openhab/core/model/Items.xtext#L67).

```
from core.log import logging, LOG_PREFIX
from core.metadata import set_metadata, get_metadata, get_key_value

LOG = logging.getLogger("{}.TEST_2".format(LOG_PREFIX))

set_metadata("Virtual_Switch_1", "Test", {"key1": -5})
LOG.warn(get_metadata("Virtual_Switch_1", "Test"))
LOG.warn(get_key_value("Virtual_Switch_1", "Test", "key1"))
LOG.warn(get_key_value("Virtual_Switch_1", "Test", "key1") == -5)
```
```
2020-05-25 14:22:45.197 [WARN ] [jython.TEST_2] - Metadata [key=Test:Virtual_Switch_1, value=string, configuration=[key1=-5]]
2020-05-25 14:22:45.198 [WARN ] [jython.TEST_2] - -5
2020-05-25 14:22:45.198 [WARN ] [jython.TEST_2] - True
```

**Comment by yfre** [comment] 2020-05-25 19:39
that was quick.  exactly, [this](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.item/src/org/openhab/core/model/Items.xtext#L67) is the line that makes the issue.
"-" is missing on the first part of the characters. not sure whether on purpose or not. 

i think, we dont need to fix it in 2.5.  it should not get that cold until release 3.0 to make a need for negative temperatures. but it would nice to fix in 3.0.

**Comment by openhab-5iver** [comment] 2020-05-25 19:47
It wouldn't be fixed in 2.5.0, since development has moved to 3.0. 

I am not familiar with Xtext, so it would be best for a maintainers to look at this. I think @wborn may be the most fluent in this area. Of course, you could always submit your own PR!

**Comment by cweitkamp** [comment] 2020-05-27 11:34
Thanks for reporting and digging into it. I could reproduce your issue in a small unit test.

If we compare the grammar to the one for Things there is exactly the "-" sign missing.

https://github.com/openhab/openhab-core/blob/1f4e374ece9d8d72f5bc77d647152b9430ca7524/bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/Thing.xtext#L96

We have options to solve it.

1. Add the "-" sign to the terminal `ID` in the Items grammar. This could lead to an impact on the Item names because the terminal `ID` is used to define allowed characters for it too.
2. Add an optional "-" sign for the `NUMBER` definition like this

```
NUMBER returns ecore::EBigDecimal:
    ('-')? ID ('.' ID )?
;
```

**Comment by openhab-5iver** [comment] 2020-05-27 20:11
IMO, the second option looks much better than the first. If {, }, and : were also added, I think it would implement #992. Testing now!

**Closed** 2020-06-24 20:06 UTC
Labels: DSL, PR pending, bug
