### ISSUE TITLE
Saving items file causes excessive CPU utilization

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-core#1908] opened 2020-12-09 16:39 UTC
I described a problem in the community forum here.
https://community.openhab.org/t/openhab-3-0-milestone-5-discussion/109612/53

I'm opening an issue now, as I've been able to reproduce the problem on a fresh install of OH3 build 2050 using nothing other than one items file containing 405 item definitions.

I see sustained high cpu and memory utilization whenever I save changes to an items file. It’s especially severe (high CPU and memory for several minutes) when the items file contains a large number of items (e.g. > 400).

The problem manifests itself a couple different ways.

- If I try to shutdown openHAB immediately after I save an .items file, it takes 1.5 minutes for OH to shutdown. And, it only shuts down because the systemctl timeout causes systemctl to kill the openHAB process (the timeout is currently 90 seconds).

- After saving changes to one items file, if I immediately save changes to another items file, the normal “Loading model…” log message doesn’t show up in the log file right away. It shows up a few minutes later after OH finishes whatever it’s doing with the first file.

- Looking at cpu utilization in top or pidstat, I see elevated cpu utilization for anywhere from 30 seconds to several minutes, depending on the number of items in the file.

Here’s an example from VisualVM. You can see very stable/normal cpu and memory utilization. The red arrows represent when I saved the items file, and you can see where the process of loading the items is consuming 1 of the 4 cpus in my box for about 3 minutes.

![items-cpu](https://user-images.githubusercontent.com/19286354/101658355-ef16c000-3a12-11eb-8961-fdd39efe4e51.jpg)

![items-memory](https://user-images.githubusercontent.com/19286354/101658382-f6d66480-3a12-11eb-86b6-260a7053d760.jpg)

**Comment by kaikreuzer** [comment] 2020-12-09 18:05
Could you provide a demo.items file that can be dropped on a plain fresh openHAB install to reproduce it?

**Comment by mhilbush** [comment] 2020-12-09 18:29
I can provide the file I used. it's basically a complete version of [this file](http://next.openhab.org/addons/bindings/weathercompany/#items-example) from the docs. Is that ok?

**Comment by mhilbush** [comment] 2020-12-09 18:33
[weathercompany.items.txt](https://github.com/openhab/openhab-core/files/5667907/weathercompany.items.txt)

**Comment by mhilbush** [comment] 2020-12-09 18:41
And just to be clear. Here's what I do.

- Install openHAB ( I unzip the distro zip file into a directory)
- drop the weathercompany.items file into the conf/items directory
- start openHAB (I use start_debug.sh) and wait for it to settle down to steady state
- edit the weathercompany.items file (I just add a newline at the top of the file)

**Comment by mhilbush** [comment] 2020-12-09 19:11
One other thing I just noticed... If I remove all the channel links from the items file, the file is processed normally (i.e. fast).

**Comment by kaikreuzer** [comment] 2020-12-09 19:50
That's a very interesting observation - thanks!

**Comment by mhilbush** [comment] 2020-12-09 20:21
Also, I went back to a backup of build 1937 (sorry, I know it's pretty old). It doesn't exhibit this behavior. I'm guessing the issue was introduced recently, otherwise, I'm sure a lot of people would've noticed it.

**Comment by kaikreuzer** [comment] 2020-12-09 20:27
@wborn & @cweitkamp Does that ring any bell for you? Any recently merged change that could have introduced that behavior?

**Comment by mhilbush** [comment] 2020-12-09 20:29
I just installed a backup of build 2037. That build also has the issue.

So, as best I can tell, it was introduced after 1937 and before 2037. I wish I could narrow down further, but those are the only backups I have.

**Comment by mhilbush** [comment] 2020-12-09 20:31
Sorry, it was build 1935, not 1937. I will correct the above comments.

**Comment by wborn** [comment] 2020-12-10 00:12
Based on my profiler I've prevented the call to `getAll()` in `ChannelLinkNotifier.removed` (added in #1634) and also cached the UID string representation in `AbstractUID` since it is used very frequently in code when `getAll()` is called:

![profiled](https://user-images.githubusercontent.com/12213581/101704280-a8fa4480-3a84-11eb-99ff-51dd2a852599.png)

It's a lot faster with the changes in #1909.

**Closed** 2020-12-10 09:20 UTC

**Comment by mhilbush** [comment] 2020-12-10 13:02
Looks good @wborn. Thanks for the quick fix.

I have one items file that contains 840 items. That one still takes a couple seconds to load, but I don't think that's much different than 2.x.

BTW, what profiling tool were you using to produce the above results?

**Comment by wborn** [comment] 2020-12-10 13:43
I'm always using [JProfiler](https://www.ej-technologies.com/products/jprofiler/overview.html) for profiling. I tried some others with openHAB but IIRC they didn't work well with OSGi. You can use it for free during a trial period. You can attach it to a running VM (probably requires OH to run in debug mode nowdays), then go to "CPU Views" and then hit the record button to get similar results:

![Screenshot from 2020-12-10 14-37-45](https://user-images.githubusercontent.com/12213581/101779539-b4398880-3af5-11eb-80d2-315ac2ac6480.png)


It's very easy and saves a lot of time and discussion/speculation of what might be happening. :wink:
