### ISSUE TITLE
System Ready Event

### ISSUE THREAD

**Issue by mjcumming** [openhab/openhab-core#400] opened 2018-09-16 23:02 UTC
It would be nice to have an event that triggers once all items have been loaded and all bindings are ready to be used versus using the System Started event where the state of items, groups and bindings is unknown.

**Comment by thedannymullen** [comment] 2018-09-17 01:14
I agree!  This issue has been trouble for me also. 

I love the idea of system started only happening after the system has actually started.

**Comment by kaikreuzer** [comment] 2018-09-17 06:31
Looks like a duplicate of https://github.com/eclipse/smarthome/issues/1896.

**Closed by kaikreuzer** 2018-09-17 06:31 UTC
