### ISSUE TITLE
JettyServerWrapper logs warnings when creating temp dirs on Windows

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-core#3425] opened 2023-03-05 13:09 UTC
I am working on BasicUI development (openhab-webui repository), and I am getting the following warning message on startup:

```
13:53:06.619 [WARN ] [ce.jetty.internal.JettyServerWrapper] - Can't create temporary directory for OsgiContextModel{HS,id=OCM-17,name='context:1470141928',path='/',bundle=org.apache.felix.webconsole,context=WebContainerContextWrapper{bundle=org.apache.felix.webconsole_4.7.2 [50],contextId='context:1470141928',delegate=org.apache.felix.webconsole.internal.servlet.OsgiManagerHttpContext@57a095e8}}: C:\Users\MHERWEGE\AppData\Local\Temp\ROOT\context:1470141928
```

I am not sure if this is a core issue, or should be posted in the openhab-webui repository.
I also just saw https://github.com/openhab/openhab-webui/issues/1757. Could these be related?

**Comment by wborn** [comment] 2023-03-05 13:41
Probably the issue is that it cannot create the temp file on Windows because that OS doesn't like colons in filenames.

**Comment by wborn** [comment] 2023-03-05 14:03
The `JettyServerWrapper` [creates the dir](https://github.com/ops4j/org.ops4j.pax.web/blob/7c8c48e249c7235a04160ff69f37caee42de0582/pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapper.java#L943-L947) so it's a Pax Web issue as it should make sure the temp dir name is valid.
Perhaps you can create an issue for this in the Pax Web [issue tracker](https://github.com/ops4j/org.ops4j.pax.web/issues)?

**Comment by Mark-VG** [comment] 2023-04-18 08:56
Just wondering what would be the process to get this fix merged into OH?

https://github.com/ops4j/org.ops4j.pax.web/issues/1841 says that they have fixed the issue

**Comment by wborn** [comment] 2023-10-24 08:33
This got fixed by https://github.com/openhab/openhab-core/pull/3814.

**Closed by wborn** 2023-10-24 08:33 UTC
Labels: external bug
