### ISSUE TITLE
Add as Thing (with custom ID) - fails with no error message

### ISSUE THREAD

**Issue by ronisaacson** [openhab/openhab-core#2331] opened 2021-04-29 16:43 UTC
With 3.0.2 I've seen this issue in the UI. The Powermax binding creates Things for alarm zones, using the id format `powermax:zone:<panel id>:<zone number>`. For example: `powermax:zone:myalarm:2` for a sensor on zone 2.

When creating Things from the inbox, if you click on Add as Thing, then everything works fine. But if you click on Add as Thing (with custom ID) and leave the default id, then nothing happens. It takes you right back to the inbox without creating the Thing. If you look in the logfile you'll find this message:

```
2021-04-29 10:25:05.730 [WARN ] [g.discovery.internal.PersistentInbox] - Cannot create thing: ID segment 'alarm:2' contains invalid characters. Each segment of the ID must match the pattern [\w-]*.
```

Perhaps the binding needs to use a conforming id format, but the issue here is that the UI fails to create the Thing, and goes back to the inbox **without showing an error message**.

**Comment by lolodomo** [comment] 2021-04-30 06:47
The problem is certainly that the UI in this case is providing the last 2 segments rather than only the last one.

**Comment by ghys** [comment] 2021-04-30 12:35
I'm not sure about that, since the UID format is _bindingId:thingTypeId:thingId_ where thingId can itself have several colon-separated segments. In many cases the bridgeId at the time of creation is part of the thingId for things approved from the inbox. In other words everything after the second colon is the ID and it can contain colons too.

**Comment by ronisaacson** [comment] 2021-04-30 14:05
The request made by the UI is:

`http://xxx/rest/inbox/powermax:zone:alarm:2/approve?newThingId=alarm:2`

and it gets back an HTTP 409 response with this content:

`{"error":{"message":"No binding found that can create the thing","http-code":409}}`

I'm guessing I should open a new issue in openhab-webui for the ignored error message, although I don't think the error message is correct in this case. The "invalid characters" message from the logfile is far more descriptive and that's probably what should get sent back.

@lolodomo I tried your suggestion and changed the input to just "2" and that worked. The request was:

`http://xxx/rest/inbox/powermax:zone:alarm:2/approve?newThingId=2`

and the Thing was created correctly. Is this also a UI bug then? The custom id dialog uses this to get the default value for newThingId:

`entry.thingUID.substring(entry.thingUID.indexOf(':', entry.thingUID.indexOf(':') + 1) + 1)`

which takes everything after the second colon, resulting in `alarm:2` rather than just `2`.

**Comment by lolodomo** [comment] 2021-04-30 14:26
We have to decide where to fix the issue. 
But I can confirm my implementation of the API in the core framework did not cover id with several segments.

**Comment by lolodomo** [comment] 2021-05-01 12:45
> @lolodomo I tried your suggestion and changed the input to just "2" and that worked. The request was:
> 
> `http://xxx/rest/inbox/powermax:zone:alarm:2/approve?newThingId=2`
> 
> and the Thing was created correctly

What was your final thing UID ? I am afraid it would be powermax:zone:2 rather than powermax:zone:alarm:2.
If true, yes my code is not very good as it will remove the bridge segment from th ething UID.

**Comment by lolodomo** [comment] 2021-05-01 13:19
If the user modifies in the UI box the default value "alarm:2" by for example "toto:2", even if the UID "powermax:zone:toto:2" would be first built by the core framework and passed to the binding handler factory like that with also the bridge UID "powermax:zone:alarm". The powermax binding will finally create the thing with UID "powermax:zone:alarm:2", the "toto" segment is then ignored. But this is because this binding (like many others) builds again the thing UID in its `createThing` method.

But for bindsings not rebuilding the thing UID, I am not sure what would the final result.

Should I consider only the last segment of the provided value when handling the REST API approve ? It would work for the Powermax binding but I am not sure what would happen for any binding.

**Comment by lolodomo** [comment] 2021-05-01 14:26
I believe we should not change the API code. The parameter is called "new thing ID", this clearly references the last segment of a thing UID.
So the API is correct in my opinion.
IMHO, the UI should be fixed to provide in the UI box only the last segment.

**Comment by ronisaacson** [comment] 2021-05-01 21:45
I created two new issues in openhab-webui. Can we use this one to address the non-optimal error message being returned?

**Comment by lolodomo** [comment] 2021-05-02 11:31
Regarding the error message, in fact the underlying API used by the REST API should trigger an IllegalArgumentException in case the id contains multiple segments. Then the REST API will return the code 404 with message "Thing unable to be approved." (rather than the 409 code).
Additionnaly, I will update the build of the new thing UID. When a different id was provided, I build a thing UID with this id without considering the original UID that includes the bridge ID.
As explained yesterday, in practice it will make no difference with bindings like the powermax binding but maybe it could make a difference with certain bindings.

Just to be clear with my proposed change, if the thing to be approved is powermax:zone:alarm:2 and the REST API is called with the new ID "myZone2", the following thing UID: powermax:zone/alarm:myZone2 will be built by the core framework.
And if the REST API is called with the new id "alarm:2", the API will return code 404.

**Comment by lolodomo** [comment] 2021-05-02 13:20
An unit test was already existing to cover the case the newThingId is invalid because containing multiple segments.
The difference is that now IllegalArgumentException will be thrown rather than returning null.

**Comment by ronisaacson** [comment] 2021-05-02 15:20
I think that sounds like the right approach!

**Closed** 2021-05-04 17:11 UTC
Labels: PR pending

**Comment by fpap72** [comment] 2021-05-04 21:09
Is this issue somehow related to the issue I described here a few weeks ago: [#997](https://github.com/openhab/openhab-webui/issues/997)?
(In that post I described two problems caused by the 'Add as Thing (with custom ID)' menu option, one of those two problems was related to a misbehavior when setting Thing identifiers)

**Comment by lolodomo** [comment] 2021-05-04 21:45
Difficult to say, you will have to try again when everything is fixed. There are still related issues opened in webui repo to fix first.

**Comment by fpap72** [comment] 2021-06-02 11:54
I tried this morning with version 3.1.0M5 (which, according to the changelog, should fix this issue) and I'm still having the same problem (described here [#997](https://github.com/openhab/openhab-webui/issues/997)).

Another strange thing is that, as far as I understood, the 'Add as Thing (with custom ID)' menu option should now allow only modifying the last segment of the ID, instead it still allows me to change the last two segments (my ZWave Controller has ID equal to 'zwave:serial_zstick:Controller', this is the reason why the last two segments of the ID in the picture are 'Controller:node5').


![img4](https://user-images.githubusercontent.com/28343122/120475244-65382600-c3a9-11eb-89d3-27b10910a970.png)

**Comment by lolodomo** [comment] 2021-06-02 12:10
core framework was fixed but UI part was not yet fixed. There are 2 open issues in UI related to this problem.

Thank you to close again this issue in core framewxork and to add your comment to the UI issues.
