### ISSUE TITLE
validateThingUID in DiscoveryResultBuilder is wrong

### ISSUE THREAD

**Issue by mjagdis** [openhab/openhab-core#1800] opened 2020-11-06 00:06 UTC
The name is somewhat misleading. What validateThingUID actually does is check that the ID of the bridge specified using withBridge is a component of the UID of the Thing that is being built. This is incorrect. There is no requirement that the bridge ID is part of a Thing's UID. Not all devices are tied to a single bridge and a Thing's bridge is actually run-time selectable by the user. Having a bridge ID as part of the Thing's UID would make no sense.

**Comment by cweitkamp** [comment] 2020-11-07 08:54
Our recommended `ThingUID` naming convention for stand-alone things is `<binding_id>:<type_id>:<thing_id>`. For Things related to a bridge we agreed on `<binding_id>:<type_id>:<bridge_id>:<thing_id>`.

As discovery is an automated framework feature we want to make sure that this naming convention is valid every time. That is the basic idea behind this check. Be aware that the check will only be applied if a Bridge will be added to the discovery result.

This should not prevent a user to change the Bridge for a Thing during runtime.

**Comment by mjagdis** [comment] 2020-11-07 13:34
What was the thinking behind that?

What about thing not related to a bridge? Some devices are distinguishable by protocol and a unique id/address and may be "related" to a whole set of bridges.

Given that the Bridge for a Thing is user-changeable the bridge component of the UID must never be relied on, is a source of confusion and appears to serve no purpose?

What stops bindings managing their own namespace?

**Comment by J-N-K** [comment] 2022-04-29 15:56
The UID of things not attached to bridges is not validated by the method in question. So there is no problem. Since the change was done intentionally, I'm closing this issue.

**Closed by J-N-K** 2022-04-29 15:56 UTC
Labels: question

**Comment by mjagdis** [comment] 2022-04-29 17:36
You misunderstand. It's not _attached_ - it's _related_. Think of devices such as RF receivers - RFXcom, RFLink etc. To give good coverage you may need more than one receiver, each of which may "discover" the _same_ protocol:address. It's all the _same_  Thing, just seen by multiple bridges. Ergo, you can't require a ThingUID to be based on a BridgeUID. That's a showstopper.

**Comment by mjagdis** [comment] 2022-04-29 17:44
So you fill the inbox with multiple different Things that are all the
same thing... Why?

**Comment by J-N-K** [comment] 2022-04-29 18:04
IMO this should be prevented by using the representation property when adding the things to the inbox. I checked the code and this is currently not the case. @openhab/core-maintainers, WDYT?

**Comment by kaikreuzer** [comment] 2022-05-08 09:47
I would claim that it is a feature and not a bug, if there are multiple discovery results: The user then has the choice to decide, which of them to accept (i.e. which bridge to use). He can then simply ignore all other results.
Theoretically, the bridges can be of different types and offer different ways to access the device. You could even think further and say that the same device (a zigbee lightbulb) could e.g. be discovered by the zigbee binding, the hue binding and the mqtt binding - we nonetheless want to have the same bulb show up as three different discovery results (and we would technically not even stand a chance to identify that it is the same physical device).
