### ISSUE TITLE
Skipping setup causes issues due to locale not being set

### ISSUE THREAD

**Issue by mlobstein** [openhab/openhab-core#4266] opened 2024-06-01 23:39 UTC
When accessing the openhab ui for the first time, the user is prompted to complete the setup wizard. However they are also given the option to **Skip Setup**.
![image](https://github.com/openhab/openhab-core/assets/26532542/2a1fc169-1a24-4c81-a724-6a2f274469ee)
If setup is skipped this causes problems due to these settings being null. The most noticeable problem is that when clicking **Install Bindings**, the list of bindings does not load because of a javascript error caused by `region` being null.

![image](https://github.com/openhab/openhab-core/assets/26532542/da1e79d4-9e48-4cae-80f0-1874df8f5753)

![image](https://github.com/openhab/openhab-core/assets/26532542/4135f0ad-34ae-4994-8b6a-4f4fe3f7f09f)

Expected result: When the Setup Wizard is skipped, the Country / Region for the system should default to `world`, the Time Zone should default to `GMT` and the Language should default to `English`.

**Comment by mherwege** [comment] 2024-06-02 09:13
There shouldn't be a problem for language and timezone, as that will be picked up from the system locale (JVM default locale). The issue is probably when the default locale for the JVM is just language, and does not have the region set. The minimum definition of the locale is only language.
The issue got introduced with https://github.com/openhab/openhab-webui/pull/2582. It needs to be fixed there, otherwise existing installations that get upgraded without country set will also have this issue. I will fix it there.

**Comment by florian-h05** [comment] 2024-06-02 10:40
@openhab/core-maintainers Can you please close this issue? I have just merged the fix in Main UI.

**Closed** 2024-06-02 10:40 UTC
Labels: bug
