### ISSUE TITLE
[profiles] configuration change not activated

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#1645] opened 2020-09-14 07:47 UTC
Changes to profile configuration via UI are stored (checked that the new configuration is available in the REST API), but the used profile itself is not updated. Because of that the old configuration is used until the bundle providing the profile is restarted.

**Comment by kaikreuzer** [comment] 2020-12-05 21:37
@cweitkamp You have put this to the OH3 issue tracker - do you think it is necessary and/or realistic to tackle it for the release?

**Comment by cweitkamp** [comment] 2020-12-06 09:02
Yes, it is necessary. Because it is even worse than described in the opening post by @J-N-K . It was possible for me to reproduce it. And I found an additional error. In the situation when an Item is linked to a Channel and the link is configured to use a profile, after it will be unlinked and linked again the old profile will still be applied even if you change the profile on the new link.

But it looks like it only appears if using the REST API. When using textual configuration files everything is working fine.

**Comment by kaikreuzer** [comment] 2020-12-06 13:51
If it is necessary, we should have a volunteer to look into it and to assign this issue to.
Would you be willing to analyse it and think about a fix and shout for help if you think you can't make it?

**Comment by cweitkamp** [comment] 2020-12-06 21:12
Yes, I will look I to it. I will try to come up with a fix for it quickly.

**Comment by cweitkamp** [comment] 2020-12-12 20:09
I submitted #1917 to fix this issue.

**Closed** 2020-12-12 20:55 UTC
Labels: bug
