### ISSUE TITLE
Basic UI has no possibility to choose sitemap

### ISSUE THREAD

**Issue by lubeda** [openhab/openhab-core#121] opened 2017-02-19 08:38 UTC
I use the latest openhabian in Basic UI i have all the things listed but there is no possibily to choose a sitemap. Only wioth the manually entered URL http://openhabian:8080/basicui/app?sitemap i get the chance to select a sitemap.

**Comment by kaikreuzer** [comment] 2017-02-19 11:23
Duplicate of https://github.com/openhab/openhab-core/issues/118

**Closed by kaikreuzer** 2017-02-19 11:23 UTC
