### ISSUE TITLE
After upgrade to 4.2 units are not rendered implicitly in sitemaps

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-core#4321] opened 2024-07-15 17:53 UTC
Previously I had an mqtt thing:

> Type number  : r1_temperature "R 1"   [stateTopic="r1/status/switch:0", transformationPattern="JSONPATH:$.temperature.tC"]

an item:

> Number:Temperature        r1_temperature "Temp" <temp> ["Temperature", "Measurement"] {channel="mqtt:topic:r1:r1_temperature"}

and an entry in a sitemap:

> Text item=r1_temperature

This has renedered implicitly a terminating °C in the sitemap. After switching from OH 4.1 to 4.2, the °C are not shown any more, I can add then e.g. as unit="°C" to the thing, or by introducing `[%.1f °C]` to the presentation status of the item.

Likewise for Number:Potential and Volts.  Interesting, if I put unit="A" in an mqtt-thing, which I bind later on to Number:ElectricPotential, the value is not shown, as the units are not compatible.

**Comment by lolodomo** [comment] 2024-07-16 06:26
Is it specific to MQTT things ?
Is it specific to sitemap UIs, I mean do you get the unit for this item in Main UI ?

PS: As I am not using MQTT, I will not be of a big help.

**Comment by lolodomo** [comment] 2024-07-16 06:28
@mherwege : are you aware of changes in UoM with 4.2 ?

**Comment by dilyanpalauzov** [comment] 2024-07-16 06:33
All my things are MQTT-based.

**Comment by lolodomo** [comment] 2024-07-16 06:49
Maybe a change in MQTT stuff.
Was it OK in 4.2 milestones ?

@mherwege : maybe a link with your change openhab/openhab-addons#16866 ?

**Comment by lolodomo** [comment] 2024-07-16 06:50
And please comment if this is specific to sitemap UIs or the same even in Main UI.

**Comment by mherwege** [comment] 2024-07-16 07:28
Without defining a unit on the MQTT channel, the MQTT binding is providing a default state description pattern of %.1f as the channel has no info about the dimension. If you add a unit definition to the channel it will be solved.
It indeed is caused by https://github.com/openhab/openhab-addons/pull/16866, but I still think it is an improvement, as a default state description pattern of %s (as itwas before) creates many more issues downstream.

**Comment by lolodomo** [comment] 2024-07-16 07:41
Considering @mherwege answer, I propose to close the issue.
In case it is not closed, @openhab/core-maintainers please rename this issue into "After upgrade to 4.2 units are not rendered implicitly for MQTT things" and move it in the addons repo.

**Comment by dilyanpalauzov** [comment] 2024-07-16 16:54
I have an EnOcean device.  This Item:

> Number:Energy  e1_energy "Енергия" ["Energy", "Measurement"] {channel="enocean:measurementSwitch:ABC:01234:totalusage"}

and this Thing from jsondb, excerpt from a bigger definition
```json
        {
          "uid": "enocean:measurementSwitch:ABC:01234:totalusage",
          "id": "totalusage",
          "channelTypeUID": "enocean:totalusage",
          "itemType": "Number:Energy",
          "kind": "STATE",
          "label": "",
          "defaultTags": [],
          "properties": {},
          "configuration": {},
          "autoUpdatePolicy": "DEFAULT"
        },
```
in a Sitemap file as

> Text item=e1_energy

shows in implicit format  [%.1f kWh]

For the MQTT-Thing, but not the MQTT-broker binding itself, if unit="V" is part of the mqtt-thing definition, and the item has no state presentation, in the Sitemap on Android it is shown as "Integet V", so there is no "[%.1f V]" to print one digit after the decimal separator.  The value is rounded.  The statement, that the default in such cases is %.1f UNIT is not correct, the default state presentation for MQTT things, bound to items, is rounded value Integer, followed by unitname.

When I remove [%.1f V] from an Number:ElectricPotential item, bound to an mqtt-thing with unit=V, and put this item on the Overview page (MAin UI), then again it shown as [rounded Integer V],

If the same Number:ElectricPotential item, without presentation, with an mqtt-thing having unit="V", currently the Main UI does not show the unit (volts).  My statement is, that OpenHAB 4.1 under the same conditions has shown the implicit unit in the Sitemap.

**Comment by mherwege** [comment] 2024-07-16 17:38
> The statement, that the default in such cases is %.1f UNIT is not correct, the default state presentation for MQTT things, bound to items, is rounded value Integer, followed by unitname.

I stand corrected. The default is indeed %.0f %unit% for channels with a unit defined.
It worked before in 4.1 in the case no unit was defined because the state description was just %s. But that lead to problems when a unit is defined in 4.2 (showing the unit twice).
If no unit is defined, the channel will be assumed to represent a plain Number, hence no unit visible because the channel default state description will be %.0f, which you can then override for the item to include the unit.
So, yes, this is a breaking change. Restoring 4.1 behavior would need reverting the PR referred to, and other core PR’s. I believe the current behavior is much more consistent and logical, so I don’t think we should do that. Just adapt your configuration to your needs.

**Comment by dilyanpalauzov** [comment] 2024-07-16 17:59
There are two ways to imply volts for an entry in a sitemap, without using state presentations:
- if the mqtt thing has unit="V', or
- the item is of type Number:ElectricPotential

I think any of these options should be sufficient to render V implicitly in the state presentation. That is, only the secont point, excluding the first point, should by default render V.

**Comment by dilyanpalauzov** [comment] 2024-07-16 18:08
So, for items of type number with dimension, linked to channels, the default state presentation does not include the unit.  Buf for items of type number with dimensions, not linhed to a channel, the default state presentation does render the unit: https://github.com/openhab/openhab-core/issues/4071#issuecomment-2041584455 implied from the dimension, when the channel has no unit itself . I do not think this is very logical.

**Comment by mherwege** [comment] 2024-07-16 19:00
It is very logical. The channel can provide a default state description, and for the MQTT binding it always does. That has higher precedence than the default state description for items, as it is assumed the channel knows better what the default should be. Still higher priority are state descriptions defined on the Item or the Sitemap.
MQTT used to provide %s as default for anything. It now provides a meaningful default for the type of the channel. But if you not provide a unit on a Number type channel, the default will not include a unit.
These precedence rules have been in place since a long time. The MQTT binding caused problems because, while it always provided a default, it provided the wrong one.

**Comment by J-N-K** [comment] 2024-07-17 16:52
You should not send values without a number to an item with a dimension. It is only for backward compatibility that the "item unit" is added. 

Once you configure the MQTT channels correctly (with a unit) it should work, as @mherwege explained. If it does not work, then the MQTT binding is supplying a wrong state description and needs a fix. This is not a core bug.

**Closed by J-N-K** 2024-07-17 16:52 UTC
Labels: bug
