### ISSUE TITLE
NPE in ThreadedEventHandler

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-core#2231] opened 2021-03-08 17:03 UTC
Hi together,

I am facing some strange NPEs in ThreadedEventHandler for quite a while now.

The NPE occurs when i receive trigger events from my hue dimmer switch.
I use rules to catch those events and do some light scene stuff.
The NPE also occurs when my complete rule is disabled and not handled.

Error log from my productive environment 
- Ubuntu Server 20.04 VM 
- running a manual openhabian installation
-  openjdk 11.0.10 2021-01-19 LTS
- OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
- OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)

```
17:53:58.613 [ERROR] [.internal.events.ThreadedEventHandler] - Error on event handling.
java.lang.NullPointerException: null
        at java.lang.String.contains(String.java:2036) ~[?:?]
        at org.openhab.core.automation.internal.module.handler.ChannelEventTriggerHandler.apply(ChannelEventTriggerHandler.java:91) ~[?:?]
        at org.openhab.core.internal.events.EventHandler.dispatchEvent(EventHandler.java:143) ~[bundleFile:?]
        at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:111) ~[bundleFile:?]
        at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:84) ~[bundleFile:?]
        at org.openhab.core.internal.events.ThreadedEventHandler.lambda$0(ThreadedEventHandler.java:67) [bundleFile:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
17:53:59.134 [ERROR] [.internal.events.ThreadedEventHandler] - Error on event handling.
java.lang.NullPointerException: null
        at java.lang.String.contains(String.java:2036) ~[?:?]
        at org.openhab.core.automation.internal.module.handler.ChannelEventTriggerHandler.apply(ChannelEventTriggerHandler.java:91) ~[?:?]
        at org.openhab.core.internal.events.EventHandler.dispatchEvent(EventHandler.java:143) ~[bundleFile:?]
        at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:111) ~[bundleFile:?]
        at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:84) ~[bundleFile:?]
        at org.openhab.core.internal.events.ThreadedEventHandler.lambda$0(ThreadedEventHandler.java:67) [bundleFile:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Error in my test environment i have setup to exclude my setup as failure source:

- debian-10.8.0-i386 VM 
- running a manual openhabian installation
-  openjdk 11.0.10 2021-01-19 LTS
- OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
- OpenJDK Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)

Fresh install with a cli restored backup of my productive environment.

```

17:51:00.708 [ERROR] [.internal.events.ThreadedEventHandler] - Error on event handling.
java.lang.NullPointerException: null
        at java.lang.String.contains(Unknown Source) ~[?:?]
        at org.openhab.core.automation.internal.module.handler.ChannelEventTriggerHandler.apply(ChannelEventTriggerHandler.java:91) ~[?:?]
        at org.openhab.core.internal.events.EventHandler.dispatchEvent(EventHandler.java:143) ~[bundleFile:?]
        at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:111) ~[bundleFile:?]
        at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:84) ~[bundleFile:?]
        at org.openhab.core.internal.events.ThreadedEventHandler.lambda$0(ThreadedEventHandler.java:67) [bundleFile:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
17:51:01.239 [ERROR] [.internal.events.ThreadedEventHandler] - Error on event handling.
java.lang.NullPointerException: null
        at java.lang.String.contains(Unknown Source) ~[?:?]
        at org.openhab.core.automation.internal.module.handler.ChannelEventTriggerHandler.apply(ChannelEventTriggerHandler.java:91) ~[?:?]
        at org.openhab.core.internal.events.EventHandler.dispatchEvent(EventHandler.java:143) ~[bundleFile:?]
        at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:111) ~[bundleFile:?]
        at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:84) ~[bundleFile:?]
        at org.openhab.core.internal.events.ThreadedEventHandler.lambda$0(ThreadedEventHandler.java:67) [bundleFile:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

I first though of a malformed installation on my productive system, but since the error is occuring on a fresh install now too i wanted to document the behavior here.

**Comment by Confectrician** [comment] 2021-03-14 15:01
Example Trigger definition for completeness:

```
triggers:
  - id: "1"
    configuration:
      thingUID: hue:0820:001788708acd:8
      channelUID: hue:0820:001788708acd:8:dimmer_switch_event
    type: core.ChannelEventTrigger
``` 

Occurs for other hue switches too, but the trigger channel should be nearly the same except of the specific thing bound to it.

**Comment by kaikreuzer** [comment] 2021-03-14 15:36
Any chance you can step in with the debugger and see whether the config really does not contain a `channelUID` entry?

**Comment by Confectrician** [comment] 2021-03-14 16:08
If you point me to the right direction, i could try for sure.
I already had a look in karaf but it seems i am not able to set a log level over there.

Probably a bit out of my knowledge, but i am alway open to learns something. :)

**Comment by kaikreuzer** [comment] 2021-03-14 21:41
If you don't have an Eclipse IDE setup and never did remote debugging before, it might be a bit much for this issue here.
Nonetheless, if you are interested: Launch openHAB with `start_debug.sh/bat` and then simply launch Eclipse with a "Remote Java Application" as described [here](https://dzone.com/articles/how-debug-remote-java-applicat).

**Comment by StefanRG** [comment] 2021-03-22 18:44
I get this error too, but on Astro events.

- openHAB 3.1.0.M2
- Openhabian on a Pi 3b+
- openjdk 11.0.9 2020-10-20 LTS
- OpenJDK Runtime Environment Zulu11.43+88-CA (build 11.0.9+11-LTS)
- OpenJDK Client VM Zulu11.43+88-CA (build 11.0.9+11-LTS, mixed mod

```
triggers:
  - id: "1"
    configuration:
      thingUID: astro:sun:local
      event: END
      channelUID: astro:sun:local:civilDusk#event
    type: core.ChannelEventTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: PowerViewHub_StueNed
      command: ON
    type: core.ItemCommandAction
  - inputs: {}
    id: "3"
    label: Send besked
    configuration:
      message: Solnedgang
    type: notification.SendBroadcastNotification
```

```
2021-03-22 19:21:00.003 [ERROR] [internal.events.ThreadedEventHandler] - Error on event handling.
java.lang.NullPointerException: null
	at java.lang.String.contains(String.java:2036) ~[?:?]
	at org.openhab.core.automation.internal.module.handler.ChannelEventTriggerHandler.apply(ChannelEventTriggerHandler.java:91) ~[?:?]
	at org.openhab.core.internal.events.EventHandler.dispatchEvent(EventHandler.java:143) ~[bundleFile:?]
	at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:111) ~[bundleFile:?]
	at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:84) ~[bundleFile:?]
	at org.openhab.core.internal.events.ThreadedEventHandler.lambda$0(ThreadedEventHandler.java:67) [bundleFile:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by cweitkamp** [comment] 2021-05-04 08:59
With #2337 in place this NPE will not occur again. The fix changes logic for comparison. Instead of the topic (`contains(...)` - throws NPE) we now compare against the `ChannelUID` (`equals(...)` returns false).

The problem is the change does not solve the root cause of this issue - which btw is still not clear and known.

**Comment by Confectrician** [comment] 2021-05-04 17:51
Thanks for the update @cweitkamp 

>The problem is the change does not solve the root cause of this issue - which btw is still not clear and known.

Probably we have some indicator on where to search:
https://community.openhab.org/t/oh3-nullpointerexception-on-button-click/121390/11?u=confectrician

I have not checked it yet (i did a node-red workaround for my production system), but my setup may had some "unfinished" rules too, which may be the problem source.
Maybe you can also test the behavior with this information.

**Comment by J-N-K** [comment] 2022-04-30 17:27
@Confectrician Are you ok with closing this issue? Since the NPE has been solved, a new issue should be opened if problems occur.

**Comment by Confectrician** [comment] 2022-04-30 17:33
Yeah sure. :)

**Closed** 2022-04-30 17:33 UTC
Labels: bug, awaiting feedback
