### ISSUE TITLE
[Basic UI]: Webview - display URL from String item

### ISSUE THREAD

**Issue by mtzro2003** [openhab/openhab-core#315] opened 2018-03-14 09:46 UTC
The `Webview` element needs a `url` definition… Linking the `Webview` to a `String` item containing the URL does not work…

I do feel that this should be changed …
For example, the `Image` element accepts a String item - [Element Type ‘Image’](https://docs.openhab.org/configuration/sitemaps.html#element-type-image)

> `item` can refer to either an Image Item whose state is the raw data of the image, or a String Item whose state is an URL that points to an image. Some clients may not (yet) consider `item`.

**Comment by cweitkamp** [comment] 2018-09-04 07:44
Closing this as a duplicate of eclipse/smarthome#5766.

**Closed by cweitkamp** 2018-09-04 07:44 UTC
Labels: duplicate
