### ISSUE TITLE
Group items for binding still not working

### ISSUE THREAD

**Issue by macmeck** [openhab/openhab-core#257] opened 2017-12-12 10:43 UTC
@kaikreuzer, sure this #205 which should fix #113 is working properly? It doesn't give errors any more but it seems to me that it's also not firing the binding for the group.

Using the latest unstable version of OH2, I have a test setup as follows:
`Switch helloSwitch "Hello Switch" (helloGroup) {exec=">[*:echo Hello switch]"}
Group:Switch:OR(ON,OFF) helloGroup "Hello Group" {exec=">[*:echo Hello group]"}`

Toggeling the switch shows that the group is being properly updated but the log only shows 

    2017-11-30 16:22:13.354 [INFO ] [ab.binding.exec.internal.ExecBinding] - executed commandLine 'echo Hello switch'
    2017-11-30 16:22:16.032 [INFO ] [ab.binding.exec.internal.ExecBinding] - executed commandLine 'echo Hello switch'

So no exec binding is fired for the group. I also tested other bindings with just the same behaviour.

**Comment by macmeck** [comment] 2018-04-18 12:16
@kaikreuzer , any idea on that? This one is still bugging me...

**Comment by macmeck** [comment] 2018-12-18 12:08
open for a year now and still not fixed in OH2.4 😞 

The binding for the group is only being fired if I explicitly toggle the group item via UI but not if the group is being updated based on the underlying items.

**Comment by Rossko57** [comment] 2019-07-27 11:30
This is a misunderstanding.   The exec binding linked to the Group Item will be triggered when the Group receives a **command**.
This works, as you demonstrated by sending a command to the Group Item from UI.

It will not be triggered by the Group receiving a state **update**.
When a group Member Item changes state, the Group state is recalculated and updated.
Item/Group state updates do not trigger an exec binding run, because no command has arrived at the Item/Group.

When you send a command to a Member Item, the command acts only on that Item and is _never_ passed to the Group.
The command may of course eventually result in an Item state change, and that Member state change may in turn cause Group state change.  As already stated, Group state change will not cause exec binding to trigger.

Just to complete the picture, commands do propagate down from groups to member Items.  Sending a command to this Group Item will also result in the command being sent to all group Member Items.

This all seems to be working exactly as designed.

**Comment by J-N-K** [comment] 2022-02-26 18:54
IMO this can be closed. `Group` is not a compatible item type for any binding thing channel in OH3.

**Comment by kaikreuzer** [comment] 2022-03-01 08:21
> Group is not a compatible item type for any binding thing channel in OH3.

Well, it is, as groups can have sub-types - in the example above, it is a `Switch`.

But I agree that it should be closed as it all works as expected, just as @Rossko57 mentioned before.

**Closed by kaikreuzer** 2022-03-01 08:21 UTC

**Comment by J-N-K** [comment] 2022-03-02 17:17
@kaikreuzer If that should be allowed then there is a bug in the UI, because UI does not allow linking a `Group:Switch` item to a `Switch` type channel. Only `Switch` items show up in the list (same applies to other sub-types of `Group`).

**Comment by kaikreuzer** [comment] 2022-03-02 19:37
@J-N-K That's right, this has apparently never been implemented in the Main UI.
