### ISSUE TITLE
[Rule DSL] Introduce "newState" as a new implicit variable in rules with state triggers

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#925] opened 2019-07-15 21:53 UTC
Rules with state update/changed triggers currently have a `previousState` implicit variable defined. There is no reliable way though to get the new state. Using `triggeredItem.state` can lead to race conditions as discussed [here](https://github.com/openhab/openhab2-addons/pull/5807#issuecomment-510197771).

Introducing a dedicated implicit variable would solve this issue.

**Comment by lolodomo** [comment] 2019-08-12 14:52
Searching in the code how it is implemented, I think I can try to add the new "newState" implicit variable, even without understanding all the stuff with xtend.
This will be a clear improvment.

**Comment by openhab-5iver** [comment] 2019-08-12 18:47
If the new rule engine is to become a first class citizen in OH3, it would make sense to me to focus development efforts on it, rather than enhancing the rules DSL, which could potentially not be compatible with OH3. For example, scripts are currently not loading for Windows users (#841). I'm also investigating another issue reported in the forum where all OH logging stops for Windows users after enabling Jython. I reproduced this last night.

Just a friendly nudge in a different direction 🙂

**Comment by mhilbush** [comment] 2019-08-12 19:36
Yeah, I understand. But this will fix a pretty nasty race condition for which there's no workaround. I agree that this implicit variable also should be added to the NGRE. @kaikreuzer nixed a PR that would've worked around the issue in favor of the newState implicit variable.

**Comment by lolodomo** [comment] 2019-08-12 19:38
Working perfectly.

My rule:
```
rule "test newState 1"
when
	Item DesactiverSonos changed
then
	logInfo("Test.rules", "item state changed previousState= " + previousState.toString)
	logInfo("Test.rules", "item state changed newState= " + newState.toString)
end
```
I send an ON command. The result is:
```
2019-08-12 21:29:46.582 [INFO ] [se.smarthome.model.script.Test.rules] - item state changed previousState= OFF
2019-08-12 21:29:46.597 [INFO ] [se.smarthome.model.script.Test.rules] - item state changed newState= ON
```
Then I send an OFF command. The result is:
```
2019-08-12 21:30:45.153 [INFO ] [se.smarthome.model.script.Test.rules] - item state changed previousState= ON
2019-08-12 21:30:45.163 [INFO ] [se.smarthome.model.script.Test.rules] - item state changed newState= OFF
```

Now I change my rule to:
```
rule "test newState 1"
when
	Item DesactiverSonos received update
then
	logInfo("Test.rules", "item state updated newState= " + newState.toString)
end
```
I update the state to ON. The result is:
```
2019-08-12 21:37:32.952 [INFO ] [se.smarthome.model.script.Test.rules] - item state updated newState= ON
```
Then I update the state to OFF. The result is:
```
2019-08-12 21:37:56.604 [INFO ] [se.smarthome.model.script.Test.rules] - item state updated newState= OFF
```

**Comment by lolodomo** [comment] 2019-08-12 19:40
I will update the documentation as soon as my PR is merged.

**Comment by lolodomo** [comment] 2019-08-12 19:48
This is important to fix a major issue. DSL rules will still be in use by most users during several months.

**Comment by openhab-5iver** [comment] 2019-08-12 20:02
> I agree that this implicit variable also should be added to the NGRE.

This already exists in the NGRE... https://openhab-scripters.github.io/openhab-helper-libraries/Guides/Event%20Object%20Attributes.html

@lodomo, I was honestly just gently nudging and hopefully enticing you over to the ngre issues. Any improvement to automation is a win! You've been cranking out PRs recently, at a time when development seems to be waning. Thank you!

**Comment by mhilbush** [comment] 2019-08-13 01:18
@lolodomo Thanks for coming up with a solution for this issue.

Could you try testing with these rules, which are adapted from the rules I used [here](https://github.com/openhab/openhab2-addons/pull/5807#issuecomment-510228613) to demonstrate the issue with a race condition when using triggeringItem.

```
rule "Item Changed"
when
    Item A_String_Item changed
then
    logInfo("test", "newState={}", newState.toString)
end

rule "Post Update"
when
    System started
then
    logInfo("test", "TEST: Test rule is executing")

    for (var int i = 0; i < 20; i++) {
        TestItem_String.postUpdate(String::format("Test %03d", i))
    }
end
```

**Comment by lolodomo** [comment] 2019-08-13 05:43
Here is the result:
```
2019-08-13 07:40:32.587 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'maison.rules'
2019-08-13 07:41:23.228 [INFO ] [.eclipse.smarthome.model.script.Rule] - Démarrage
2019-08-13 07:41:23.228 [INFO ] [.eclipse.smarthome.model.script.test] - TEST: Test rule is executing
2019-08-13 07:41:23.288 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 000
2019-08-13 07:41:23.328 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 001
2019-08-13 07:41:23.354 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 002
2019-08-13 07:41:23.393 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 003
2019-08-13 07:41:23.454 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 004
2019-08-13 07:41:23.484 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 005
2019-08-13 07:41:23.523 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 006
2019-08-13 07:41:23.549 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 007
2019-08-13 07:41:23.581 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 008
2019-08-13 07:41:23.651 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 009
2019-08-13 07:41:23.683 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 010
2019-08-13 07:41:23.715 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 011
2019-08-13 07:41:23.735 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 012
2019-08-13 07:41:23.760 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 013
2019-08-13 07:41:23.781 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 014
2019-08-13 07:41:23.812 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 015
2019-08-13 07:41:23.827 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 016
2019-08-13 07:41:23.856 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 017
2019-08-13 07:41:23.877 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 018
2019-08-13 07:41:23.900 [INFO ] [.eclipse.smarthome.model.script.test] - newState=Test 019
```

**Comment by mhilbush** [comment] 2019-08-13 12:49
Thanks @lolodomo!

Ping @knikhilwiz Hopefully this will resolve the issue you were having.

**Closed** 2019-08-13 19:13 UTC
Labels: DSL rules

**Comment by knikhilwiz** [comment] 2019-08-14 00:02
Woot! Thank you.
