### ISSUE TITLE
Rules/Smarteditor sees an error in sendTelegram(ID,Text) although it is working

### ISSUE THREAD

**Issue by lubeda** [openhab/openhab-core#122] opened 2017-02-19 08:46 UTC
The Smarteditor (WIndows 32 Bit latest release) marks sendTelegram...  as "the method sendTelegram(String, String) is undefined"

```
rule "Send telegram when Backdoor is open"

when
    Item  WG_Tuer changed to OPEN
then
    sendTelegram("Ludger", "Die Wintergartentuer ist auf")
end

```

**Comment by kaikreuzer** [comment] 2017-02-19 11:21
Duplicate of https://github.com/eclipse/smarthome/issues/997

**Closed by kaikreuzer** 2017-02-19 11:21 UTC
