### ISSUE TITLE
Binding Uninstalled 

### ISSUE THREAD

**Issue by Josar** [openhab/openhab-core#278] opened 2018-01-15 12:15 UTC
When a Binding was installed via Karaf and you try to add a new Binding via PaperUI all other Bingings get uninstalled. 

```
[INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-astro' has been uninstalled.
[INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-alarmdecoder1' has been installed.
```

Installing Bindings via PaperUI and then install one via Karaf, navigate to the PaperUI Binding Page and waiting some time leads to an uninstall of the installed Binding.

```
openhab> feature:install openhab-binding-amazondashbutton
```
```
[INFO ] [.core.karaf.internal.FeatureInstaller] - Uninstalled 'openhab-binding-amazondashbutton'
[INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-amazondashbutton' has been uninstalled.
```

Sometimes a encountered that  a binding just uninstalled but could not find out why. Maybe this is related.

Others have also encountered this or a similar problem.
https://community.openhab.org/t/installing-binding-leads-to-automatic-uninstalling-another-binding/38777

**Comment by kaikreuzer** [comment] 2018-01-26 09:05
This is actually a duplicate of https://github.com/openhab/openhab-distro/issues/440 - feature installation through Console does indeed not work.

**Closed by kaikreuzer** 2018-01-26 09:05 UTC
