### ISSUE TITLE
[OH3] org.jupnp.transport.spi.StreamClient java.lang.NullPointerException: Missing SslContextFactory

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-core#1822] opened 2020-11-14 19:15 UTC
I get the same error every 10 minutes since moving to OH3.  All of my uPnP based devices seem ok so not sure if this is just cosmetic or something is breaking.

```
2020-11-14 18:06:48.043 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@55b5a9d failed
2020-11-14 18:16:48.127 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@7de761f0 failed
2020-11-14 18:26:48.223 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@1cbadce1 failed
2020-11-14 18:36:48.327 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@7aed1f6 failed
2020-11-14 18:46:48.408 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@548eca95 failed
2020-11-14 18:58:18.794 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@23f7d882 failed


2020-11-14 19:08:48.651 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@42724e05 failed
java.lang.NullPointerException: Missing SslContextFactory
        at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
        at org.eclipse.jetty.io.ssl.SslClientConnectionFactory.<init>(SslClientConnectionFactory.java:54) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpClient.newSslClientConnectionFactory(HttpClient.java:1175) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpDestination.newSslClientConnectionFactory(HttpDestination.java:137) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpDestination.<init>(HttpDestination.java:94) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.PoolingHttpDestination.<init>(PoolingHttpDestination.java:25) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.<init>(HttpDestinationOverHTTP.java:32) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.http.HttpClientTransportOverHTTP.newHttpDestination(HttpClientTransportOverHTTP.java:51) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpClient.destinationFor(HttpClient.java:546) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:579) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:728) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:681) ~[bundleFile:9.4.20.v20190813]
        at org.jupnp.transport.impl.jetty.JettyStreamClientImpl$1.call(JettyStreamClientImpl.java:155) [bundleFile:?]
        at org.jupnp.transport.impl.jetty.JettyStreamClientImpl$1.call(JettyStreamClientImpl.java:1) [bundleFile:?]
        at org.jupnp.transport.spi.AbstractStreamClient$RequestWrapper.call(AbstractStreamClient.java:204) [bundleFile:?]
        at org.jupnp.transport.spi.AbstractStreamClient$RequestWrapper.call(AbstractStreamClient.java:1) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by lolodomo** [comment] 2020-11-15 08:01
@kaikreuzer : issue to be moved in the correct repo (jupnp).
The problem is probably related to a device using UPnP with HTTPS. This is something I fixed (by rejecting HTTPS call) when I tried to improve jupnp for @morph166955 . I could push a specific PR for this.

**Comment by lolodomo** [comment] 2020-11-15 08:27
In fact, it can even be closed as it looks like a duplicate of https://github.com/jupnp/jupnp/issues/109

**Closed** 2020-11-15 09:49 UTC

**Comment by morph166955** [comment] 2020-11-15 14:58
@lolodomo given that you have the code to fix this, and add the org.jupnp:retryAfterSeconds config, could you PLEASE open the PR under jupnp#109 and submit it?
