### ISSUE TITLE
Changed Category not propagated reliably in sitemaps to BasicUI and OH-Android

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-core#3958] opened 2023-12-24 15:01 UTC
At https://github.com/openhab/openhab-android/issues/3427 and https://github.com/openhab/openhab-webui/issues/1938 I have asked to see updated icon, once I change the “category”.  I have this
```
rule "E1, E2, E3 on/off change"
when
  Item e1 changed or
  Item e2 changed or
  Item e3 changed
then
  (ir.getItem(triggeringItemName + "_power") as NumberItem).category = switch ir.getItem(triggeringItemName).state {
  case ON: 'on'
  case OFF: 'off'
  default: null
  }
end
```
The resolution of the above items, including https://github.com/openhab/openhab-core/pull/3819 and https://github.com/openhab/openhab-core/pull/3820, was to extend the syntax for icon in sitemaps, to support `AND`, `staticIcon` and others.  I have updated now to OpenHAB 4.1 .  I open a sitemap in two browsers and in openhab-android 3.8.1-beta.

With the above `rule` I change the status of an item (e2) in one of the browsers.  It appears in the sitemap as `Text item=e2_power label="E2" labelcolor=[e2==ON="olive", e2==OFF="orange"]`.  So any time I toggle the state I expect that the label colour and the icon (category) change in the other browser and in openhab-android.   I toggle the state many, many times.  The label color does change reliably, every time I toggle the item.

The icon however does not change reliably.  Often it does change, but sometimes it does not.  Moreover the behaviour of the icon is consistent in the browser (Basic IU) and in openhab-android. The only difference is that in the browser sometimes, once the icon is out of sync, on a later state toggle, the icon changes its state several times very fast, while in openhab-android I cannot observe this.

An the symptoms appears in both Basic UI and in OH-Android, the problem must be in OH-core.

**Comment by lolodomo** [comment] 2023-12-25 11:36
Please read updated documentation
https://www.openhab.org/docs/ui/sitemaps.html#icons
You need to add conditional rules to icon parameter in your sitemap.

**Comment by lolodomo** [comment] 2023-12-25 11:38
For question, community forum is a better place.

**Comment by dilyanpalauzov** [comment] 2023-12-26 07:47
Rewriting the sitemap to change the icon will certainly work.

But I am writing here, that setting the `category` from a rule shall also work for icons in sitemaps.  And indeed it does work sometimes.  But sometimes it does not.

**Comment by lolodomo** [comment] 2023-12-26 08:51
Already discussed. Changing/hacking the category of an item inside a rule, even if made available by few rule engines, is not recommended and not officially supported, so you can't expect any UI to monitor this kind of hack for an immediate update in UI. Even Main UI will not support that. The official and supported way to update an item characteristics is to use the item REST API. I also implemented in 4.1 a clean solution for sitemaps to cover your use case, with a new dedicated syntax so that you can define conditional rules for your sitemap element icon.
@openhab/core-maintainers @openhab/webui-maintainers : please tell me if I am wrong or please close this issue.
By the way, it is a duplicata of openhab/openhab-webui#1938.

**Comment by florian-h05** [comment] 2023-12-26 11:13
> Changing/hacking the category of an item inside a rule, even if made available by few rule engines, is not recommended and not officially supported, so you can't expect any UI to monitor this kind of hack for an immediate update in UI. Even Main UI will not support that.

This is the same as for other Item config, e.g. Item metadata. That configuration is meant to be static (at least was that the result from the discussion in https://github.com/openhab/openhab-webui/pull/1725). Therefore, UIs won‘t ever monitor changes to Item config, and I also doubt that unauthorized users are even allowed to subscribe to these events over SSE or WebSocket.

I therefore agree to @lolodomo to close this issue, and I would also propose to rewrite the sitemap to dynamically change the icon.

> Rewriting the sitemap to change the icon will certainly work.

Why? If it is a missing comparison operator, I am sure that someone is willing to work on that.

**Comment by J-N-K** [comment] 2023-12-26 11:16
@lolodomo and @florian-h05 have already explained why this is invalid. It is not expected to alter items this way.

**Closed by J-N-K** 2023-12-26 11:16 UTC
Labels: bug, invalid

**Comment by lolodomo** [comment] 2023-12-26 11:36
That being said and as we all agree, I am asking myself why some rule engines allow updating items in such a way ? IMHO, this is the root cause of all of this.

**Comment by florian-h05** [comment] 2023-12-26 12:21
Having this possibilities in the rule engines allows to programmatically create (or at least) modify Items. I mean that not in a way of dynamically changing configuration, but in a way of managing your Items.

E.g. if I want to change metadata or icon for a group of Items, in can just write a simple JS script instead of having to edit each Item manually. Of course better bulk editing in the UI would help here as well, but at least for me, writing a short JS script is the fastest way to bulk edit Items.

**Comment by dilyanpalauzov** [comment] 2023-12-28 20:24
> By the way, it is a duplicata of https://github.com/openhab/openhab-webui/issues/1938.

Yes it is.  But back then manual reload was always necessary, while now sometimes manual reload is, and sometimes is not necessary - it is random.  So something has improved in the meantime.

>> Rewriting the sitemap to change the icon will certainly work.
> 
> Why? If it is a missing comparison operator, I am sure that someone is willing to work on that.

I meant rewriting to use the syntax `icon=[e3==ON=oh:classic:on, e3==OFF=oh:classic:off]` does work.

**Comment by florian-h05** [comment] 2023-12-28 20:30
I am not sure what is your actual goal with the above example, but in case you want to perform some complex calculation to decide which icon to use, you can create a new icon where you store the result of that calculation to and decide based on the state of that Item which icon to use by using an icon rule.
