### ISSUE TITLE
Thing File based configuration not loaded correctly after changing

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-core#4201] opened 2024-04-28 20:20 UTC
Hello,

I changed the thing file

from

```javascript
Thing shelly:shellyplus1pm:441793cea354 "Plus1PM_Bett_links" @ "Bedroom" [deviceIp="ip", password="password"]
Thing shelly:shellyplus1pm:d4d4da7cbde0 "Plus1PM_Bett_rechts" @ "Bedroom" [deviceIp="ip", password="password"]

```

to

```javascript
Thing shelly:shellyplus1pm:441793cea354 "Plus1PM_Bett_linksd" @ "Bedroom" [deviceIp="ip", password="password"]
Thing shelly:shellyplus1pm:d4d4da7cbde0 "Plus1PM_Bett_rechtsd" @ "Bedroom" [deviceIp="ip", password="password"]

```

this is the log

```php
2024-04-10 13:53:54.527 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'shelly.things'
2024-04-10 13:53:54.549 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'shelly:shellyplus1pm:441793cea354' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Unerwarteter Fehler - WebSocket connection closed abnormal
2024-04-10 13:53:54.556 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'shelly:shellyplus1pm:d4d4da7cbde0' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Unerwarteter Fehler - WebSocket connection closed abnormal
2024-04-10 13:53:56.549 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'shelly:shellyplus1pm:441793cea354' changed from ONLINE to UNKNOWN (CONFIGURATION_PENDING): Initialisierung oder Gerät im Schlafmodus.
2024-04-10 13:53:56.556 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'shelly:shellyplus1pm:d4d4da7cbde0' changed from ONLINE to UNKNOWN (CONFIGURATION_PENDING): Initialisierung oder Gerät im Schlafmodus.
2024-04-10 13:53:56.772 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'shelly:shellyplus1pm:441793cea354' changed from UNKNOWN (CONFIGURATION_PENDING): Initialisierung oder Gerät im Schlafmodus. to ONLINE
2024-04-10 13:53:56.882 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'shelly:shellyplus1pm:d4d4da7cbde0' changed from UNKNOWN (CONFIGURATION_PENDING): Initialisierung oder Gerät im Schlafmodus. to ONLINE
```

than change it back to 

```javascript
Thing shelly:shellyplus1pm:441793cea354 "Plus1PM_Bett_links" @ "Bedroom" [deviceIp="ip", password="password"]
Thing shelly:shellyplus1pm:d4d4da7cbde0 "Plus1PM_Bett_rechts" @ "Bedroom" [deviceIp="ip", password="password"]

```

seeing this in the log

```javascript
2024-04-10 13:54:47.340 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'shelly.things'
```

but this in the ui

No update was loaded

**Comment by lolodomo** [comment] 2024-04-29 10:49
As I understand, you only change the thing label.
Can you please tell us if this is something that does not work only for Shelly things or for any thing ?

And what is your running OH version ?

**Comment by miloit** [comment] 2024-04-29 16:11
@lolodomo yes, for any binding/thing you do ..it doesn't matter if you only change the label or the settings of the thing....so just a change...

OH4.2M2 on latest openhabian release

**Comment by lolodomo** [comment] 2024-05-01 15:34
I was able to reproduce. You can change several times the thing label and it is properly updated. The problem is only when you try to restore the initial value.

**Comment by jimtng** [comment] 2024-05-01 20:02
I haven't tested this scenario specifically. Without tracing it at runtime, I "suspect" this is what's happening:

- Version 1 was loaded
- .things file changed, Version 2 loaded, but due to the leak, Version 1 is still retained in memory, and Version 2 added to the `thingsMap`. This issue/leak is fixed in #4076.
- .things changed back to Version 1, but because it wasn't cleared off `thingsMap` in the previous change, a match is found, and therefore the file isn't reloaded.

#4076 should fix this issue

**Comment by lolodomo** [comment] 2024-05-01 20:08
Ok, I will test again when #4076 is merged.

**Comment by jimtng** [comment] 2024-05-02 20:48
Yes it's merged, but it hasn't yet made it into the latest snapshot. Hopefully within the next 12 hours!

**Comment by lolodomo** [comment] 2024-05-03 07:06
Tested with snapshot 4064 including #4076. The problem is now different, it is now possible to restore the initial value. But now the very first change after startup is "ignored". The next ones are OK.
@jimtng : any idea ?

**Comment by lolodomo** [comment] 2024-05-03 07:18
Is it possible to update the issue title to precise that it concerns Thing files ?

**Comment by miloit** [comment] 2024-05-04 02:31
@lolodomo better title now?

**Comment by jimtng** [comment] 2024-05-04 03:36
> Tested with snapshot 4064 including #4076. The problem is now different, it is now possible to restore the initial value. But now the very first change after startup is "ignored". The next ones are OK.

I can't seem to reproduce this issue. Can you tell me the steps to reproduce it?

Here's what I did:

- Create a test.things file:
```
Thing astro:sun:home "test1" [ geolocation="52.5200066,13.4049540,100", interval=60 ]
Thing astro:moon:home "test1" [ geolocation="52.5200066,13.4049540", interval=60 ]
```
- Stop openhab
- Start openhab
- Run a script to show the label of the `astro:sun:home` - it logged it as "test1" 
- Modified the test.things file and changed the label to "test2"
- Rerun the script to show the label, it now logged as "test2" so it appears that it did get updated.

**Comment by lolodomo** [comment] 2024-05-04 09:26
My scenario was:

1. Having a file astro.things file in conf/things containing
```
Thing astro:sun:local "Astro" @ "Extérieur" [ geolocation="xxxx" ]
```
2. Start OH
3. Edit the file by changing the thing label and save the file => I see the log "Loading astro.things..." but when I refresh the page in Main UI showing the list of things, the label is unchanged. Confirmed by running the console command "things list".
4. Edit the file by changing the thing label and save the file => I see the log "Loading astro.things..." and now when I refresh the page in Main UI showing the list of things, the label is correct. Confirmed by running the console command "things list".

**Comment by jimtng** [comment] 2024-05-04 12:29
> My scenario was:
> 
> 1. Having a file astro.things file in conf/things containing
> 
> ```
> Thing astro:sun:local "Astro" @ "Extérieur" [ geolocation="xxxx" ]
> ```
> 
> 2. Start OH
> 3. Edit the file by changing the thing label and save & quit the file => I see the log about file loading but when I refresh the page in Main UI showing the list of things, the label is unchanged. Confirmed by running the console command "things list | grep astro".
> 4. Edit the file by changing the thing label and save & quit the file => I see the log about file loading and now when I refresh the page in Main UI showing the list of things, the label is correct. Confirmed by running the console command "things list | grep astro".


I'm still not able to reproduce the problem.

I tried your things file verbatim (including `geolocation="xxxx"`). As a result I got 
```
Astro parameters geolocation could not be split into latitude and longitude, disabling thing 'astro:sun:local'
```

But upon changing the label, it did get updated on the Main UI (I had to refresh the browser).

I then tried entering an actual coordinate in the .things file:
```
Thing astro:sun:local "Astro" @ "Extérieur" [ geolocation="52.5200066,13.4049540,100" ]
```
Stopped openhab
Started it, confirming the label in Main UI
Then this time using vim to edit the file locally (not over samba), then saved the changes with `:wq`
the new label showed up on main ui.

**Comment by lolodomo** [comment] 2024-05-04 12:41
Of course, I do not use "xxxx" as geolocation, it was just to not provide a real position.

If you are sure it works, I will try again.

**Comment by miloit** [comment] 2024-05-05 09:07
I am on `openHAB 4.2.0 (Build #4065)`

I changed the file shelly.things from
`Thing shelly:shellyplus1pm:441793cea354 "Plus1PM_Bett_links" @ "Bedroom" [deviceIp="ip", password="password"]
Thing shelly:shellyplus1pm:d4d4da7cbde0 "Plus1PM_Bett_rechts" @ "Bedroom" [deviceIp="ip", password="password"]
`

to

`Thing shelly:shellyplus1pm:441793cea354 "Plus1PM_Bett_linkse" @ "Bedroom" [deviceIp="ip", password="password"]
Thing shelly:shellyplus1pm:d4d4da7cbde0 "Plus1PM_Bett_rechtse" @ "Bedroom" [deviceIp="ip", password="password"]
`

in the log I see
`2024-05-05 10:57:28.575 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'shelly.things'`

But still the old description in the UI

I stopped openhab started new now it was changed....tried it 2 times the same scenario....means only new loaded with a restart

**Comment by lolodomo** [comment] 2024-05-05 09:41
Is it only at the first change or at any next change ?
For me, it works well except the first change.

Please note that the list of things in Main UI is not automatically updated, you have to refresh it.

**Comment by miloit** [comment] 2024-05-05 09:48
Only first change

**Comment by lolodomo** [comment] 2024-05-05 10:49
> Only first change

Well, we have the same result.

@jimtng : that is strange that you can't reproduce it.

**Comment by miloit** [comment] 2024-05-05 13:40
Can I log it somehow more?

**Comment by jimtng** [comment] 2024-05-05 13:45
I was testing it on snapshot build 4064 and couldn't replicate the problem.
I then tried installing build 4065 but encountered a problem when installing the astro binding, maybe because the addon build wasn't done yet (I don't quite understand how the packaging system works). So I tried build 4064 again and still cannot reproduce the problem.

- I stopped openhab
- Then started it again
- Loaded the Main UI page to see the thing label as set in the file
- Then edited the .things file to change the label (add / remove a letter or so)
- Then refreshed the Main UI page, the change of label I made is reflected on the Things page

**Comment by jimtng** [comment] 2024-05-05 15:10
I think there's still a bug. I'm now able to reproduce this under a different set of conditions. Looking into it more!

**Comment by jimtng** [comment] 2024-05-05 15:54
The Bug I found was this:
- When you have a .things file that contain Things from multiple bindings (e.g. Astro and Shelly), it won't work properly. This is a regression that was introduced in #4076

However, I still haven't been able to reproduce the problem when the .things file only contain things from the same binding.

In any case, could you please test this jar file? You will need to clear openhab cache and tmp dirs. Note I had to add a fake .zip extension. This is not a zip file. Just rename and remove the .zip extension and do not unzip it.

[org.openhab.core.model.thing-4.2.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab-core/files/15213572/org.openhab.core.model.thing-4.2.0-SNAPSHOT.jar.zip)

This file needs to be placed inside `./runtime/system/org/openhab/core/bundles/org.openhab.core.model.thing/4.2.0-SNAPSHOT/` - please back up your original `org.openhab.core.model.thing-4.2.0-SNAPSHOT.jar` file first!

**Comment by miloit** [comment] 2024-05-05 19:20
@jimtng Which one do I need to replace?

**Comment by miloit** [comment] 2024-05-05 19:35
in the meantime i tested also other thing files....the first time it's not changing but than it seems to be fine

**Comment by jimtng** [comment] 2024-05-05 19:57
> @jimtng Which one do I need to replace?

The one with the exact same name.
I don't know why you have two.

**Comment by miloit** [comment] 2024-05-05 20:20
the second one is just a link :) so I have only one.....I used `find` to find the location

**Comment by miloit** [comment] 2024-05-05 20:31
@jimtng looks good for me.....now

**Comment by jimtng** [comment] 2024-05-05 22:34
@lolodomo would you mind testing too please

**Comment by jimtng** [comment] 2024-05-06 00:07
@miloit thanks for testing. I take it that the jar I supplied did fix the problem? 

Would you mind testing the following:
1. only change the first thing then save the file and watch the log, and 
2. only change the second thing then save the file and watch the log

It should log that only the changed thing would go offline -> online and the unchanged thing should remain online.

**Closed** 2024-05-06 07:24 UTC
Labels: bug
