### ISSUE TITLE
ephemeris.WeekdayCondition off by a number of hours

### ISSUE THREAD

**Issue by DanielMalmgren** [openhab/openhab-core#2132] opened 2021-01-18 17:07 UTC
I've noticed strange behaviour for rules set up to execute only on weekdays, they also get executed on saturday mornings. So I did a test rule doing the following:

> triggers:
>   - id: "1"
>     configuration:
>       cronExpression: 0 0 * * * ? *
>     type: timer.GenericCronTrigger
> conditions:
>   - inputs: {}
>     id: "2"
>     configuration: {}
>     type: ephemeris.WeekdayCondition
> actions:
>   - inputs: {}
>     id: "3"
>     configuration:
>       type: application/vnd.openhab.dsl.rule
>       script: |
>         logInfo("weekday", "Today it's a week day!")
>     type: script.ScriptAction
> 

...which should write a log row every hour on week days. I haven't yet let it run a full week (I started it this sunday and now it is monday evening) but it seems the WeekdayCondition is off in some way, because it started writing log posts from 16:00 and forward. So from somewhere after saturday morning (my guess would be 16:00) to 16:00 on a monday it seems like it thinks it's weekend. Like the weekend calculation is off by 16 hours. Seems like it would be time zone related in some way? I'm in Sweden, ie +1.

Regional settings:
Country/Region: Sverige (Sweden)
Time Zone: (GMT + 1:00) Europe/Stockholm

Ephemeris settings:
Weekend days: lördag, söndag (ie saturday, sunday)
Country: Sweden

**Comment by DanielMalmgren** [comment] 2021-01-26 05:50
This is just getting weirder... I made two rules, one only running on weekend days, writing out "Today it's a weekend day!" to my log and one running on week days, writing out "Today it's a week day!". And then I set up both rules to run at "0 0,5,55 * * * ? *", ie every whole hour and five minutes before and after. And then I let them run.

I struggle to find any logic in my findings. It seems it turned from being a week day to being a week end at midnight between saturday and sunday, so exactly 24 hours too late. Yesterday it was monday and most of the day it claimed it to be a weekend. Some time between 18:05 and 18:55 it changed into being a week day. So somewhere around 18.5 hours too late.

It might be worth noticing that my OH server (for other reasons) was restarted somewhere around 18:30. Could it be affecting things?

**Comment by DanielMalmgren** [comment] 2021-01-28 08:48
After upgrading 3.0 to 3.0.1 this got even worse. Now any rules with this condition completely refuses to run, they just give a stacktrace in my log:

> 2021-01-28 09:17:46.182 [ERROR] [org.openhab.core.ephemeris          ] - bundle org.openhab.core.ephemeris:3.0.1 (143)[org.openhab.ephemeris(64)] : The activate method has thrown an exception
> java.lang.IllegalArgumentException: No enum constant java.time.DayOfWeek.( "MONDAY"
>        at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]

**Comment by MikeJMajor** [comment] 2021-02-16 07:16
Have you tried disabling and then enabling your rules after OH has started?

I'm seeing an issue that after an OH restarts my rule with a weekday and time condition does not work. The rule doesn't show any error at startup or when it's supposed to run. Disabling/enabling the rule gets it working again.

**Comment by DanielMalmgren** [comment] 2021-02-20 09:01
Tried that now, it makes no difference. Today it's saturday and ephemeris.WeekendCondition still returns false and ephemeris.WeekdayCondition returns true.

Judging by the response on this issue I suspect that either I'm the only one with this problem (which makes me wonder what's special with my system) or simply nobody else is using these conditions...

**Comment by Barthoxx** [comment] 2021-02-22 16:57
I actually just created an account to say I got the same problem. I have two rules, one that fires on weekdays at 7am and one that fires on weekends at 8am. I couldn't figure out any kind of logic behind the wrong behavior. Two weeks ago I investigated, double checked and saved the rules again. From that day on, both rules fired every day. Two days ago after ready the suggestion to disable/enable the rules, I did that, now the weekday rule is fireing every day, the weekend rule not at all.
What I found weird from the beginning: in the schedule both rules appear for every day.

Maybe the error is related to ceratin ephemeris locations/timezones? I am in Germany

**Comment by DanielMalmgren** [comment] 2021-02-22 17:52
Either that, or it has something with first day of week to do. Since it says weekend is sunday and monday for me, ie the first an last day of the week. If my week should start on mondays (like in USA) it would be correct. Does that make sense?

**Comment by dae3** [comment] 2021-03-06 04:56
@DanielMalmgren I think I'm experiencing this too. This morning (Saturday) a rule scheduled for weekdays at 6:55 AM was triggered. My location and timezone are Australia, GMT+11.

I'll setup some more logging and report the results

**Comment by dae3** [comment] 2021-03-08 09:40
OK I'm seeing something different, apparently configuration related:

`userdata/logs/openhab.log:2021-03-07 00:01:00.579 [WARN ] [emeris.internal.EphemerisManagerImpl] - This dayset is not configured : weekend`

every time the rule runs, although it is configured in Settings > Ephemeris AND I can't reproduce it on a clean setup.

**Comment by Barthoxx** [comment] 2021-03-08 18:10
I can't see any warnings in my logs at all and nothing related to Ephemeris. Since my last restart of openhab the weekend rule was never triggered, but the weekday rule got triggered every day, even on weekends. I did now disable/enable only the weekend rule and will observe this further.

**Comment by dae3** [comment] 2021-07-14 09:00
After upgrading to from 3.1.0.M3 to 3.1.0 last night, my weekday-condition rules worked perfectly today. #2398 looks like it might be the solution.

**Comment by DanielMalmgren** [comment] 2021-07-17 08:58
Hmmm, I thought I'd try it out now (on 3.1.0), but now it doesn't execute those rules at all, I just get "Missing handler 'ephemeris.WeekendCondition' for module '2'". Kinda like it's even more broken now for me... Anyone knows what's happening?

**Comment by J-N-K** [comment] 2022-05-14 15:43
Since the original issue seems to be solved with #2398 and `Missing handler ...` seems to be an configuration issue (I suggest checking if the daysets can be read properly, this should be improved with #2949), I'm closing here. Please open a new issue if the original problem occurs again.

**Closed by J-N-K** 2022-05-14 15:43 UTC
