### ISSUE TITLE
[serial] dropdown of choices collapses to first selected port

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-core#805] opened 2019-05-07 19:09 UTC
Currently running S1585, but this may go back to 2.4. I have only observed this using the zigbee and zwave bindings, but there have been reports in the forum where this occurs for other bindings. [Here's one for jeelink and zwave](https://community.openhab.org/t/snapshot-version-of-zwave-cannot-find-serial-port-after-oh-restart/73638/25?u=5iver). 

**To reproduce**
1) install the zwave and zigbee bindings with controllers for each, but don't configure yet
2) observe that the serial port dropdown for both bindings contain all ports
3) configure a port for zwave
4) observe that the serial prort dropdown for the zwave and zigbee bindings now only contain the port that had been selected for the zwave binding
5) after an OH restart, observe all ports are in the dropdown again for both bindings
6) configure a port for zigbee
7) observe the serial port dropdown for both bindings now only contain the port selected for zigbee

Possibly related, I also observe the zigbee binding losing it's serial port connection about once a day. The zigbee binding uses [gnu.io.SerialPort](https://github.com/openhab/org.openhab.binding.zigbee/blob/master/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/handler/ZigBeeSerialPort.java#L28) and zwave uses [org.eclipse.smarthome.io.transport.serial.SerialPort](https://github.com/openhab/org.openhab.binding.zwave/blob/master/src/main/java/org/openhab/binding/zwave/handler/ZWaveSerialHandler.java#L22). So, possibly a conflict in using the different transports?

More details can be found here (see issue 2)... https://github.com/openhab/org.openhab.binding.zwave/issues/1165. 

Note: After manually installing the bindings, the dropdowns have disappeared completely and allow free-text entries for the port. When doing the manual install, I only installed the openhab-core-io-transport-serial and openhab-core-config-discovery-usbserial features to resolve serial dependencies. However, zigbee still looses connection to its port at least once a day.

**Comment by maggu2810** [comment] 2019-05-08 07:12
> After manually installing the bindings, the dropdowns have disappeared completely and allow free-text entries for the port. When doing the manual install, I only installed the openhab-core-io-transport-serial and openhab-core-config-discovery-usbserial features to resolve serial dependencies.

You need to install `org.openhab.core.config.serial` if you want serial configuration support.
If you want to install the whole serial support you just need to install: [openhab-transport-serial](https://github.com/openhab/openhab-core/blob/0168145/features/karaf/openhab-core/src/main/feature/feature.xml#L495)

If you install some `openhab-core-...` features you only install a specific function only.

There are other features that aggregate specific functions to provide a better user experience: https://github.com/openhab/openhab-core/blob/0168145/features/karaf/openhab-core/src/main/feature/feature.xml#L403-L503

**Comment by openhab-5iver** [comment] 2019-05-08 08:10
Thank you, Markus... that helps a lot! I incorrectly thought that with the move to the newer transport that I needed to install those other features rather than openhab-transport serial. Serial in OH is still an unknown for me.

I just updated to S1587 and I'm back to unmanaged bindings and dropdowns. Shouldn't this be marked as a bug?

**Comment by maggu2810** [comment] 2019-05-08 08:13
> unmanaged bindings and dropdowns

You have written a good explanation of the buggy dropdown behaviour. Yes, I assume it is a bug (at least "somewhere").

What do you mean by unmanaged bindings?
It is related to this topic or is it another issue?

**Comment by openhab-5iver** [comment] 2019-05-08 08:24
Typo... managed bindings... as in not manually installed. That may not be the correct way to describe this, but similar to managed/unmanaged Items and Things.

**Comment by openhab-5iver** [comment] 2019-05-11 13:30
After reading through some code, especially [SerialPortUtil](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortUtil.java), on a whim I added my ports into EXTRA_JAVA_OPTS. After a restart, the dropdown shows all ports. So, in reproducing this, be sure not to have any ports in there.

**Comment by wborn** [comment] 2019-06-10 21:03
The issue is that `SerialPortUtil` sets the environment variable `gnu.io.rxtx.SerialPorts` to a value when it's not set:

https://github.com/openhab/openhab-core/blob/7f5ceefa26ffdf6ea290c9717868814b6318ff13/bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortUtil.java#L44

After that, whenever nrjavaserial is used to get the serial port identifiers (`CommPortIdentifier.getPortIdentifiers()`), it will only return the ports set in that environment variable (see [nrjavaserial code](https://github.com/NeuronRobotics/nrjavaserial/blob/e06ed10e23284c36d19225b907e0b7a3b2736833/src/main/java/gnu/io/RXTXCommDriver.java#L418-L422)). So maybe it can be fixed by making sure the environment variable is restored to its original value after using it for creating the `SerialPortIdentifierImpl`?

https://github.com/openhab/openhab-core/blob/7f5ceefa26ffdf6ea290c9717868814b6318ff13/bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/RxTxPortProvider.java#L49-L58

**Closed** 2019-06-12 06:58 UTC
Labels: bug
