### ISSUE TITLE
Rules in OH2.1.0-SNAPSHOT stop working

### ISSUE THREAD

**Issue by Spybyte** [openhab/openhab-core#127] opened 2017-03-15 05:53 UTC
I was not able to find out a pattern, but rules in OH2.1.0-SNAPSHOT (and also OH2) suddenly stop working. But it seems not all of them. E.g. tonight all of my "Time cron" rules just stopped. At least some of the other rules were running. Sometimes it helps if you just save the rule again. Sometimes I have to restart openHAB.

See also [this diksussion](https://community.openhab.org/t/rules-stop-processing/24655/16)

**Comment by kaikreuzer** [comment] 2017-03-15 06:32
There is no code in this repo that is related to rule execution at all.
I also guess you will have to analyse a bit deeper and come up with a reproducible scenario.
Possibly your issue is a duplicate of https://github.com/eclipse/smarthome/issues/3132.

**Closed by kaikreuzer** 2017-03-15 06:32 UTC
