### ISSUE TITLE
QuantityType unit conversion for pressure adds false precision

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#2206] opened 2021-02-17 21:05 UTC
Given the following example:
```
import org.openhab.core.library.types.QuantityType;

public class UnitConverter {
    public static void main(String[] args) {
        convert("1025.5 hPa", "inHg");
        convert("30.283 inHg", "hPa");

        System.out.println("----------");
        convert("1025.5 hPa", "mmHg");
        convert("769.19 mmHg", "hPa");

        System.out.println("----------");
        convert("1025.5 mbar", "inHg");
        convert("30.283 inHg", "mbar");

        System.out.println("----------");
        convert("1025.5 mbar", "mmHg");
        convert("769.19 mbar", "hPa");
    }

    public static void convert(String from, String to) {
        QuantityType<?> q = new QuantityType<>(from);
        System.out.println(q + " -> " + q.toUnit(to));
    }
}
```
It produces the following output which includes false precision:
```
1025.5 hPa -> 30.28300360147744440388992637583171 inHg
30.283 inHg -> 1025.49987804 hPa
----------
1025.5 hPa -> 769.1882580423414021569133845567459 mmHg
769.19 mmHg -> 1025.5023224192 hPa
----------
1025.5 mbar -> 30.28300360147744440388992637583171 inHg
30.283 inHg -> 1025.49987804 mbar
----------
1025.5 mbar -> 769.1882580423414021569133845567459 mmHg
769.19 mbar -> 769.19 hPa
```

**Comment by rkoshak** [comment] 2021-02-17 21:27
Computers are bad at floating point math. Or to be specific, there are just some floating point numbers that are impossible for the computer to represent. What you are seeing is not false precision. At some point in the conversion between units a non-representable number was encountered. When that occurs a value that is *really* close to the actual number is used. That's why you end up with all those decimal places. 

This is a common and universal problem with most floating point operations in most programming languages (any that uses IEEE 754 to represent floating point numbers at least). It is to be expected.

**Comment by J-N-K** [comment] 2021-02-17 21:49
See my comment in the other issue. This is not a bug, this is math and should be fixed by chosing the correct state description when formatting the value.

**Comment by robnielsen** [comment] 2021-02-17 23:53
@J-N-K, this is a bug, openHAB should be scaling the result after the conversion.

**Comment by Rossko57** [comment] 2021-02-25 11:55
And then we'd get complaints about loss of precision.

Can you give some justification - what actual problem is this causing you, that is not about presentation? (where the correct "fix"is presentation control)

**Comment by robnielsen** [comment] 2021-02-25 12:45
@Rossko57, easy enough.  Look at the specifications for the the Netatmo indoor module (https://www.netatmo.com/en-us/weather/weatherstation/specifications):

> Barometer:
> Ranges from: 260 to 1260 mbar / 7.7 to 37.2 inHg
> Accuracy: ± 1 mbar / ± 0.03 inHg

And here are a few examples from the events.log file:

```
2021-02-25 05:44:22.450 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'nIndoorPressure' changed from 30.27709760370046196714611556620210 inHg to 30.28005060258895318551802097101691 inHg
2021-02-25 05:54:24.580 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'nIndoorPressure' changed from 30.28005060258895318551802097101691 inHg to 30.28595660036593562226183178064652 inHg
2021-02-25 06:04:26.797 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'nIndoorPressure' changed from 30.28595660036593562226183178064652 inHg to 30.29186259814291805900564259027613 inHg
2021-02-25 06:34:37.978 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'nIndoorPressure' changed from 30.29186259814291805900564259027613 inHg to 30.28890959925442684063373718546132 inHg
```

The values imply a precision that is no way supported by any barometer that I'm aware of. 

The correct fix is not in the presentation, false precision should not be introduced during the conversion.  BTW, here's the definition of [False Precision](https://en.wikipedia.org/wiki/False_precision) from Wikipedia: 

> False precision (also called overprecision, fake precision, misplaced precision and spurious precision) occurs when numerical data are presented in a manner that implies better precision than is justified; since precision is a limit to accuracy (in the ISO definition of accuracy), this often leads to overconfidence in the accuracy, named precision bias.

**Comment by rkoshak** [comment] 2021-02-25 19:24
Well, given that the calculation to convert quantity types and do math with quantity types is done using a third party library, you probably need to go and file your issue over there. As for the false precision, the way I was trained to do it way back under my first computer science degree program's numerical analysis class was to not throw away that "false precision" until you display the value to a human. It's only the human that cares and if you prematurely throw away the decimal points the rounding errors build up *way* faster than you would expect.

**Comment by robnielsen** [comment] 2021-02-25 19:50
@rkoshak, the issue isn't with the third party library, it's the lack of applying precision after the conversion.

**Comment by rkoshak** [comment] 2021-02-25 20:25
Here is the function in openHAB's code that converts between units.

```
    /**
     * Convert this QuantityType to a new {@link QuantityType} using the given target unit.
     *
     * @param targetUnit the unit to which this {@link QuantityType} will be converted to.
     * @return the new {@link QuantityType} in the given {@link Unit} or {@code null} in case of a
     */
    @SuppressWarnings("unchecked")
    public @Nullable QuantityType<T> toUnit(Unit<?> targetUnit) {
        if (!targetUnit.equals(getUnit())) {
            try {
                UnitConverter uc = getUnit().getConverterToAny(targetUnit);
                Quantity<?> result = Quantities.getQuantity(uc.convert(quantity.getValue()), targetUnit);

                return new QuantityType<T>(result.getValue(), (Unit<T>) targetUnit);
            } catch (UnconvertibleException | IncommensurableException e) {
                logger.debug("Unable to convert unit from {} to {}", getUnit(), targetUnit);
                return null;
            }
        }
        return this;
    }
```

Where is the openHAB code that would be able to apply any precision after the conversion? `Unit` comes from javax.measure. `UnitConverter` comes from javax.measure.  `Quantities` comes from tec.uom.se.quantity. 

It's `UnitConverter` that does the calculation. None of this is openHAB code, it's code that openHAB uses from third party libraries. I believe you can find that code at https://github.com/unitsofmeasurement/unit-api/tree/master/src/main/java/javax/measure. That's where you need to file your issue.

**Comment by robnielsen** [comment] 2021-02-25 20:54
The defect is still with openHAB since it's using a library that doesn't properly scale after the conversion. @rkoshak, your continual negative comments is what is pushing people away from openHAB and issues like this is why non-technical people say it's hard to use. If you take the time to do any research, you'll find terms such as [significance arithmetic](https://en.wikipedia.org/wiki/Significance_arithmetic):

> Significance arithmetic is a set of rules (sometimes called significant figure rules) for approximating the propagation of uncertainty in scientific or statistical calculations. These rules can be used to find the appropriate number of significant figures to use to represent the result of a calculation. If a calculation is done without analysis of the uncertainty involved, a result that is written with too many significant figures can be taken to imply a higher precision than is known, and a result that is written with too few significant figures results in an avoidable loss of precision. Understanding these rules requires a good understanding of the concept of significant and insignificant figures.

**Comment by J-N-K** [comment] 2021-02-25 20:55
@rkoshak As you perfectly pointed out: rounding is performed at the end of a calculation, not at intermediate steps.

This can be fixed by applying a proper state description for displaying the value.

**Comment by robnielsen** [comment] 2021-02-25 21:00
@J-N-K, it needs to happen before display, immediately after conversion. So you are expecting non-technical people to know how to do this? There is no reason that this can't be done properly by openHAB.

**Comment by J-N-K** [comment] 2021-02-25 21:07
That depends on what you convert for. If you convert to do other calculations afterwards (e.g. convert a temperature between degree Fahrenheit and Kelvin to use it in the calculation of absolute humidity from a relative humidity value) it‘s wrong.

**Comment by J-N-K** [comment] 2021-02-25 21:10
And how should openHAB know about the correct precision? Take e.g. a value of 24 degree Celsius. Could be that the sensors precision really is 1 degree. But it could also be 0.01 degree. Or 0.1 degree.

**Comment by rkoshak** [comment] 2021-02-25 21:15
Yes, yes we do expect non-technical people to do this. It's one of the reasons we have such an extensive set of features for changing the state of an Item *before display to the user*, all of which are well documented. There are technical and mathematical reasons why it is this way and why it must remain this way. A "falsely precise" result of a calculation is *way* better than an incorrect result, which is what you would have if you need to do more than just a couple of calculations. You can correct the falsely precise aspect prior to displaying the number to a human, which is the *only* place where it's a problem with the extensive set of tools openHAB provides to you through transformations and formatters on the label.

We can and have done a lot to make building your home automation system easier for less technical people. But at the end of the day creating your openHAB config is an exercise in software development. We can't eliminate all the technical aspects. And even more importantly, we can not change fundamental limitations of doing math with computers. 

And if my pointing out that this is:

- not an issue
- if it were an issue, it is an issue that needs to be filed on an upstream library

constitutes "continual negative comments" then we appear to have a significantly different understanding of the English language (there, now *that's* a negative comment for you).

**Comment by robnielsen** [comment] 2021-02-25 22:02
Wow, such big comments from Dick in a stupid hat! This is a defect and should be fixed, there is no value in keeping the extra precision around and could be addressed.

**Comment by rkoshak** [comment] 2021-02-25 22:27
Then fix it yourself and see if you can get is accepted.

Feel free to block me on the forum. I've already blocked you.

**Comment by Rossko57** [comment] 2021-02-26 13:13
> it needs to happen before display

Why?  Who cares how it's stored internally?   Can you outline the problem this is causing you?

**Closed** 2022-04-25 16:06 UTC
Labels: won't fix, UoM
