### ISSUE TITLE
OH3 cron expression in rule causes exception - issue with DayOfWeek in cron expression?

### ISSUE THREAD

**Issue by deibl** [openhab/openhab-core#2023] opened 2020-12-28 23:30 UTC
I am using the following cron expression within a rule, which worked with OH2: "0 0 7 ? * SAT-SUN"
Error sounds like "off by one" issue :-)
```
java.lang.IllegalArgumentException: Value too high in range in cron expression '0 0 7 ? * SAT-SUN' in field 'DayOfWeek': value 8, minimum: 7
	at org.openhab.core.internal.scheduler.CronAdjuster.parseRange(CronAdjuster.java:444) ~[bundleFile:?]
	at org.openhab.core.internal.scheduler.CronAdjuster.parseSub(CronAdjuster.java:281) ~[bundleFile:?]
	at org.openhab.core.internal.scheduler.CronAdjuster.parse(CronAdjuster.java:228) ~[bundleFile:?]
	at org.openhab.core.internal.scheduler.CronAdjuster.<init>(CronAdjuster.java:97) ~[bundleFile:?]
	at org.openhab.core.internal.scheduler.CronSchedulerImpl.schedule(CronSchedulerImpl.java:67) ~[bundleFile:?]
	at org.openhab.core.internal.scheduler.CronSchedulerImpl.schedule(CronSchedulerImpl.java:61) ~[bundleFile:?]
	at org.openhab.core.automation.internal.module.handler.GenericCronTriggerHandler.scheduleJob(GenericCronTriggerHandler.java:60) ~[?:?]
	at org.openhab.core.automation.internal.module.handler.GenericCronTriggerHandler.setCallback(GenericCronTriggerHandler.java:56) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.lambda$0(RuleEngineImpl.java:636) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.register(RuleEngineImpl.java:633) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.activateRule(RuleEngineImpl.java:850) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.setRule(RuleEngineImpl.java:504) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.addRule(RuleEngineImpl.java:464) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl$2.added(RuleEngineImpl.java:271) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl$2.added(RuleEngineImpl.java:1) ~[?:?]
	at org.openhab.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:367) [bundleFile:?]
	at org.openhab.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:400) [bundleFile:?]
	at org.openhab.core.automation.internal.RuleRegistryImpl.notifyListenersAboutAddedElement(RuleRegistryImpl.java:252) [bundleFile:?]
	at org.openhab.core.automation.internal.RuleRegistryImpl.notifyListenersAboutAddedElement(RuleRegistryImpl.java:1) [bundleFile:?]
	at org.openhab.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:175) [bundleFile:?]
	at org.openhab.core.automation.internal.RuleRegistryImpl.added(RuleRegistryImpl.java:417) [bundleFile:?]
	at org.openhab.core.automation.internal.RuleRegistryImpl.added(RuleRegistryImpl.java:1) [bundleFile:?]
	at org.openhab.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:1) [bundleFile:?]
	at org.openhab.core.model.rule.runtime.internal.DSLRuleProvider.addRule(DSLRuleProvider.java:190) [bundleFile:?]
	at org.openhab.core.model.rule.runtime.internal.DSLRuleProvider.onReadyMarkerAdded(DSLRuleProvider.java:407) [bundleFile:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.lambda$0(ReadyServiceImpl.java:52) [bundleFile:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) [?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) [?:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.notifyTrackers(ReadyServiceImpl.java:79) [bundleFile:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.markReady(ReadyServiceImpl.java:52) [bundleFile:?]
	at org.openhab.core.model.rule.jvmmodel.RulesRefresher.lambda$0(RulesRefresher.java:182) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by kaikreuzer** [comment] 2020-12-29 08:17
Duplicate of https://github.com/openhab/openhab-core/issues/1813.

**Closed by kaikreuzer** 2020-12-29 08:17 UTC
