### ISSUE TITLE
OH #1518: issues with "now" implementations

### ISSUE THREAD

**Issue by nesys** [openhab/openhab-core#553] opened 2019-02-09 11:29 UTC
Hi team,

after updating to #1518 I've encountered issues in all my rules where I implement solutions with persistence (eg. lastUpdate.isAfter(now.minusSeconds(6)) or averageSince(now.minusMinutes(2)) )

Let me share an example:

2019-02-09 12:14:43.879 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'presence.rules', using it anyway:
The method createTimer(Object, Procedure0) from the type ScriptExecution refers to the missing type Object
The method lastUpdate(Item) from the type PersistenceExtensions refers to the missing type Object
The method lastUpdate(Item) from the type PersistenceExtensions refers to the missing type Object
The method lastUpdate(Item) from the type PersistenceExtensions refers to the missing type Object

My rule is:

```
rule "Welcome home my dear"
when
    Member of gPhones changed to ON
then
    if(cameHomeTimer !== null) {
        return; // do nothing if there is already a Timer
    }
    logInfo("test", "Rule triggered by " + triggeringItem.name + " at " + now.toString)
    cameHomeTimer = createTimer(now.plusSeconds(5), [ |

        val cameHome = gPhones.members.filter[ p | p.state == ON && (p.name == triggeringItem.name || (p.lastUpdate !== null && p.lastUpdate.isAfter(now.minusSeconds(6)))) ].map[ name.replace("_Phone_Home_Unifi_online", "") ]

        gPhones.members.forEach[ p | logInfo("test", "Values for " + p.name + "\n" + "State = " + p.state.toString + "\n" + "LastUpdate = " + p.lastUpdate.toString)]

        var message = "Benvenuti a casa, "

        switch(cameHome.size) {
            case 0: {
                logError("came home", "Unexpected number of phones: " + cameHome.size)
                return;
            }
            case cameHome.size == 1 && cameHome.get(0) == "Andrea": message = "Benvenuto a casa, Andrea"
            case cameHome.size == 1 && cameHome.get(0) == "Cate": message = "Benvenuta a casa, Caterina"
            case cameHome.size == 1 && cameHome.get(0) == "Sofia": message = "Benvenuta a casa, Sofia"
            case cameHome.size == 1 && cameHome.get(0) == "Edo": message = "Benvenuto a casa, Edoardo"
            default: {
                message = message + cameHome.members.reduce[ String list, String name | list + ", " + name ]
                val ind = message.lastIndexOf(",")
                message = new StringBuilder(str).replace(ind, ind+1," e").toString();
            }
        }
        logInfo("check message", "message is: " + message)

        Echo_Living_Room_TTS_Volume.sendCommand('90')
        Echo_Living_Room_TTS.sendCommand('<speak><break time="2s"/>' + message + '</speak>')
        //Echo_Living_Room_TTS.sendCommand(message)      
        cameHomeTimer = null
    ])
end
```

When the rule is triggered, I see this error in my logs (and the rule not works):

2019-02-09 12:18:22.223 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'Welcome home my dear': The name 'now' cannot be resolved to an item or type; line 28, column 75, length 3

Any suggestion? is that related to ESH bundles?

I've also a community topic open:
https://community.openhab.org/t/issues-in-rules-after-upgrading-to-1518/67136/5

Thanks for your support

Kind Regards

Andrea

**Comment by jimduchek** [comment] 2019-02-11 20:23
Same issue here.  Tried a number of things, really, it looks like a great deal of Joda seems to be broken.  This issue completely breaks the rules for heating/cooling my house so it's quite a problem.  Temporary workaround for me (really I just need the current epoch time) is to revert to some deprecated stuff.

`var millis = new DateTimeType().calendar.timeInMillis
`

**Comment by toffyrn** [comment] 2019-02-12 05:52
For me I resolved it by reverting to snapshot 1512.

**Comment by kaikreuzer** [comment] 2019-02-12 07:46
@maggu2810 I assume this must be in some way related to the fact that Jodatime is not part of model.persistence anymore. I can see that Jodatime is installed as a separate bundle and there are import-package statements in model.persistence, so I don't see any obvious problem. Do you have an idea, why this broke?

**Comment by maggu2810** [comment] 2019-02-12 14:11
@nesys I fixed your initial comment. Please use triple backticks for multiline preformatted text.

**Comment by maggu2810** [comment] 2019-02-12 14:21
@kaikreuzer Can you point me to the location where variables and packages are added to the rules?

**Comment by maggu2810** [comment] 2019-02-12 14:24
`ScriptImportSectionNamespaceScopeProvider`?

**Comment by kaikreuzer** [comment] 2019-02-12 16:13
> Wasn't the intention to get rid of Joda time at all?

Yes, but that hasn't been implemented yet, so I guess we have to fix this regression first...

**Comment by maggu2810** [comment] 2019-02-12 16:26
I had a look at the ESH manifests.

joda time has been added to the persistence model bundle.
So it should not matter if bundled or not, from a script / rule perspective it should be the same if provided by persistence or a separate one.

Perhaps an import gets lost.

**Comment by kaikreuzer** [comment] 2019-02-12 16:31
Yes, that's also what I saw and mentioned above:

> I can see that Jodatime is installed as a separate bundle and there are import-package statements in model.persistence

The model.persistence bundle is fully resolved and active, so it does not seem to miss anything. 

I am still struggling to get the app.bndrun working, so I currently cannot test & debug in the IDE... Will try to get that working first.

**Comment by maggu2810** [comment] 2019-02-12 16:55
> [maggu2810](/maggu2810) closed this in ` [maggu2810/openhab-core.bnd-playground@fd2bd9e](/maggu2810/openhab-core.bnd-playground/commit/fd2bd9edc85bb8bcee3b0674d715858c5de75b60) ` [3 minutes ago](#event-2134309153)

Strange, why is this issue closed if I commit to a repository of mine?

**Comment by nesys** [comment] 2019-02-12 17:12
guys thanks for your support here. @maggu2810 understood and will do next time

**Comment by kaikreuzer** [comment] 2019-02-13 08:27
> Strange, why is this issue closed if I commit to a repository of mine?

Because you say it fixes this issue and you have write access to this repo here - that's how the Github auto-closing feature works :-)

**Closed** 2019-02-13 08:29 UTC

**Comment by maggu2810** [comment] 2019-02-13 08:32
If I commit to branch "fit-xyz" into my repository the issue get's not closed. Otherwise I will never  be able to create PRs without already closing the issue.
I assume it has been caused because I added it to the master branch of my repository.

But that's annoying.
This will make it much harder to work on forks while having write permission.
Just because I fix an issue in my repo it does not solve it in the repo of the upstream project.

**Comment by kaikreuzer** [comment] 2019-02-13 12:16
Many thanks for the fix, @maggu2810, I can confirm that "now" now works smoothly in the latest distro 1522!
