### ISSUE TITLE
ignore temporary config files

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-core#112] opened 2017-01-24 20:15 UTC
I am using mcedit to create and modify my configuration files via console.
This editor creates temorary files.
like `.#addons.cfg` for `addons.cfg`.

This creates an error in the log.

> 2017-01-24 21:07:34.363 [WARN ] [ore.service.AbstractWatchQueueReader] - Could not process config file '.#addons.cfg': java.io.FileNotFoundException: /etc/openhab2/services/.#addons.cfg (Datei oder Verzeichnis nicht gefunden)

I would suggest to create some exceptions to the config file detection.

I guess other editors like vim and nano might have similar problems.

**Comment by kaikreuzer** [comment] 2017-01-25 08:06
Duplicate of https://github.com/eclipse/smarthome/issues/2100

**Closed by kaikreuzer** 2017-01-25 08:06 UTC
Labels: duplicate
