### ISSUE TITLE
System Started Event very often triggers under Windows without changing the configuration

### ISSUE THREAD

**Issue by DiKaY1969** [openhab/openhab-core#1529] opened 2020-06-22 09:07 UTC
The system started event very often triggers on older versions x64 without changing the configuration under Windows 10 V2004 / V1909.

After analyzing my log files, this problem occurred after the update to version ~ 2.5.3 and is still present in the current version 2.5.5.

All rules are then reinitialized and especially battery operated Z-Wave sensors then have no current status in OH until the sensor gives a new sign of life which is very unpleasant especially if you are working sensors for an alarm system.

The system started event occurs cyclically in an indefinite interval between 4 minutes up to approx. 50 minutes and all rules then execute the system started event!

There are no further entries in the log files that indicate a serious error that could trigger this problem.

According to the documentation, the event should only be triggered when the system is started and when there are changes to the rules or items or things.

E.g. If a rule is changed, then only this rule is reinitialized and the system-started event is triggered in this rule, which is correct.

I have also tried my installation on another Windows 10 V2004 x64 and the same problem occurs here. The same problem also occurs on another completely new Windows 10 V2004 x86 system.

I have currently installed Java JDK 8.0.251. But the problem also occurs with JDK 8.0.241.

Can you take a closer look at that?

If you need more information, log files, etc., I can provide you with them.

Many thanks for your help.

**Comment by DiKaY1969** [comment] 2020-06-23 10:00
Here is the status of another test.

OH 2.5.5 now on another computer with Windows 10 V2004 x86 almost without hardware (no Z-Wave controller and no persistence connection).

The bindings such as SMTP,, FritzBox, FritzBoxTR64, FSInternetRadio, OpenWeatherMap, Astro, HTTP, Mail and Network are active and therefore work error-free.

The Habpanel and Hab app occasionally access the server.

The problem described does not arise with this constellation.

I will now add the database (MySQL Persistence) and test it followed by the Z-Wave controller a day later.

**Comment by openhab-5iver** [comment] 2020-06-23 17:52
Duplicate of #1365 (and a couple others). This has also been discussed many times in the forum.

**Comment by kaikreuzer** [comment] 2020-06-24 20:15
Looks indeed like a duplicate, so closing this here.

**Closed by kaikreuzer** 2020-06-24 20:15 UTC
